### PR TITLE
Read usernames and passwords from file

### PR DESCRIPTION
**Pull request by springjools**
## Description
Provide a means for reading login credentials from file. It works like this: let the username field begin with 'file:' and it will use the rest of that field as the path to your credentials file. The works both as python runserver.py -u file:somepath/accounts.csv as well as from config.ini. The path can be absolute or relative (to runserver.py).

## Motivation and Context
It is the belief of the author that this is a feature that has been requested and that will be welcomed

## How Has This Been Tested?
Tested with powershell on windows 7. Not tested with unix/linux, it would be nice if someone could test that part. Mostly how the dashes in filename paths work. But I assume that the user can form the filename path to such a string that it works on any system.

## Screenshots (if appropriate):
readfromfile

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Will update the documentation in a timely manner 

when it is needed and topical.

### CODE REVIEW

**Comment by springjools** [comment]
Forgot to mention that the only requirement of the accounts file is that it is comma separated, and that each line begins like this:
auth-service,username,password

Each line can contain more stuff. It is read as line and separated by commas, and the first 3 fields are used.

**Comment by springjools** [comment]
untitled
In case the file cannot be read...

**Comment by Albert62** [comment]
THANK YOU!

**Comment by aldarund** [comment]
Please add a error handling for not proper files

**Comment by justsomedudeonthenet** [comment]
#1067 already handles CSV files, with proper error checking.

**Comment by FrostTheFox** [comment]
#1067 was merged, replaces this.

**Pull request closed without merging**
