### PR TITLE
PokestopDetails - Names and Images

### PR DESCRIPTION
**Pull request by KoffeinKaio**
## Description
Added the functionality to get Names/Images and desription into the Database and show them on the Map (if available).

## Motivation and Context
I have a really bad orientation, so I wanted to see the Images of Pokestops.
Also people tend to say "hey, Pokestop <name> is lured!" not "Hey Pokestop at [lat, lng] is Lured!"

## How Has This Been Tested?
Testet it on my Map with MySQL (should work with sqlite too)

## Screenshots (if appropriate):
pokestop

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jchristi** [comment]
Don't forget to bump the schema version for db changes.

**Comment by KoffeinKaio** [comment]
reworking script to support multiple accounts/proxys + pokestop queue for large DB's.

**Comment by CoolCanuck** [comment]
I can't thank you enough for this. THANK YOU THANK YOU THANK YOU.

**Comment by CoolCanuck** [comment]
FYI to all: Doesn't seem to be automatic. It's a separate script you run :'(

**Comment by KoffeinKaio** [comment]
Automatic scanning will be included in the rework. First I need to get this thing working again :P

**Comment by CoolCanuck** [comment]
requires
pip install MySQL-python
:)

**Comment by CoolCanuck** [comment]
Please consider adding =s100   onto the image url's :) 
Eg:   http://lh6.ggpht.com/3ChNAJORfZki8vEnhDhvcrKW3KhNOSJI256bC0wC45I9I9lMNOB4UnjNwQQH2233mZiqchTfGM5h_8yOEIlx=s100

This reduces loading images that can be upwards of 8000px and 10's of MB. 
Thanks for your hard work
NOTE: This probably wont work on Panorama/other source images. (if used.. Ingress uses more than google hosted images)

**Comment by KoffeinKaio** [comment]
pgo uses also more than google picasa, so I dont think I'll implement this. (I'll will try to work out something)

MySQLdb was a leftover, its not needed, just forgot to remove it.

The new implementation will be like -gi, it only parses pokestops if they are not in the database.

Thanks for the feedback!

**Comment by CoolCanuck** [comment]
Okay. Here is another option.  Use something line https://images.weserv.nl

eg: https://images.weserv.nl/?url=lh6.ggpht.com/OdAhIEMhitKoBecEKM8fMJyreB239blHQNPjZJ9e9KY3EmKwtk1nPtU3hUu0xFyhzEv130l682wOqq9wjUV0KQ**&h=100**

^^MUST remove http:// or https:// from image url. 

Please also consider using the image src with // or https://    -- the https is "broken https" (not truely secure) on map which utilize https.

**Pull request closed without merging**
