### PR TITLE
Stagger account logins over scan_delay

### PR DESCRIPTION
**Pull request by marumari**
## Description
This is a minor change that staggers the PTC/Google logins over the entirety of scan_delay, to prevent any kind of login throttling and reduce load on the PTC login servers.

```
2016-08-07 20:45:12,555 [      MainThread][     utilities][    INFO] Location for 'some place, some nation'
2016-08-07 20:45:12,555 [      MainThread][     utilities][    INFO] Coordinates (lat/long/alt) for location: xx.xxxxxx yy.yyyyyy 0.0
2016-08-07 20:45:12,555 [      MainThread][     runserver][    INFO] Parsed location is: xx.xxxx/yy.yyyy/0.0000 (lat/lng/alt)
2016-08-07 20:45:12,558 [      MainThread][        models][    INFO] Connecting to local SQLite database
2016-08-07 20:45:12,561 [   search_thread][        search][    INFO] Search overseer starting
2016-08-07 20:45:12,562 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-07 20:45:12,563 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-07 20:45:12,567 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 270)
2016-08-07 20:45:12,568 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: account1
2016-08-07 20:45:12,937 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-07 20:45:12,937 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-07 20:45:13,048 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-07 20:45:13,424 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 50 pokestops, and 17 gyms
2016-08-07 20:45:13,939 [ search_worker_1][        search][    INFO] Search step 2 beginning (queue size is 269)
2016-08-07 20:45:13,939 [ search_worker_1][      auth_ptc][    INFO] PTC User Login for: account2
2016-08-07 20:45:14,302 [ search_worker_1][      auth_ptc][    INFO] PTC User Login successful.
2016-08-07 20:45:14,304 [ search_worker_1][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-07 20:45:14,413 [ search_worker_1][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-07 20:45:14,780 [ search_worker_1][        models][    INFO] Upserted 0 pokemon, 52 pokestops, and 16 gyms
2016-08-07 20:45:15,315 [ search_worker_2][        search][    INFO] Search step 3 beginning (queue size is 268)
2016-08-07 20:45:15,316 [ search_worker_2][      auth_ptc][    INFO] PTC User Login for: account3
2016-08-07 20:45:15,691 [ search_worker_2][      auth_ptc][    INFO] PTC User Login successful.
2016-08-07 20:45:15,692 [ search_worker_2][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-07 20:45:15,804 [ search_worker_2][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-07 20:45:16,140 [ search_worker_2][        models][    INFO] Upserted 0 pokemon, 44 pokestops, and 16 gyms
2016-08-07 20:45:16,692 [ search_worker_3][        search][    INFO] Search step 4 beginning (queue size is 267)
2016-08-07 20:45:16,693 [ search_worker_3][      auth_ptc][    INFO] PTC User Login for: account4
2016-08-07 20:45:17,048 [ search_worker_3][      auth_ptc][    INFO] PTC User Login successful.
2016-08-07 20:45:17,048 [ search_worker_3][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-07 20:45:17,153 [ search_worker_3][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-07 20:45:17,548 [ search_worker_3][        models][    INFO] Upserted 1 pokemon, 49 pokestops, and 15 gyms
2016-08-07 20:45:18,068 [ search_worker_4][        search][    INFO] Search step 5 beginning (queue size is 266)
2016-08-07 20:45:18,068 [ search_worker_4][      auth_ptc][    INFO] PTC User Login for: account5
2016-08-07 20:45:18,431 [ search_worker_4][      auth_ptc][    INFO] PTC User Login successful.
2016-08-07 20:45:18,431 [ search_worker_4][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-07 20:45:18,536 [ search_worker_4][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-07 20:45:18,830 [ search_worker_4][        models][    INFO] Upserted 0 pokemon, 53 pokestops, and 15 gyms
2016-08-07 20:45:19,445 [ search_worker_5][        search][    INFO] Search step 6 beginning (queue size is 265)
2016-08-07 20:45:19,445 [ search_worker_5][      auth_ptc][    INFO] PTC User Login for: account6
2016-08-07 20:45:19,814 [ search_worker_5][      auth_ptc][    INFO] PTC User Login successful.
2016-08-07 20:45:19,814 [ search_worker_5][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-07 20:45:19,920 [ search_worker_5][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-07 20:45:20,224 [ search_worker_5][        models][    INFO] Upserted 0 pokemon, 54 pokestops, and 16 gyms
2016-08-07 20:45:20,821 [ search_worker_6][        search][    INFO] Search step 7 beginning (queue size is 264)
2016-08-07 20:45:20,821 [ search_worker_6][      auth_ptc][    INFO] PTC User Login for: account7
2016-08-07 20:45:21,187 [ search_worker_6][      auth_ptc][    INFO] PTC User Login successful.
2016-08-07 20:45:21,187 [ search_worker_6][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-07 20:45:21,295 [ search_worker_6][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-07 20:45:21,623 [ search_worker_6][        models][    INFO] Upserted 0 pokemon, 59 pokestops, and 18 gyms
2016-08-07 20:45:22,206 [ search_worker_7][        search][    INFO] Search step 8 beginning (queue size is 263)
2016-08-07 20:45:22,206 [ search_worker_7][      auth_ptc][    INFO] PTC User Login for: account8
2016-08-07 20:45:22,580 [ search_worker_7][      auth_ptc][    INFO] PTC User Login successful.
2016-08-07 20:45:22,580 [ search_worker_7][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-07 20:45:22,685 [ search_worker_7][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-07 20:45:22,992 [ search_worker_7][        models][    INFO] Upserted 1 pokemon, 55 pokestops, and 16 gyms
2016-08-07 20:45:24,437 [ search_worker_0][        search][    INFO] Search step 9 beginning (queue size is 262)
2016-08-07 20:45:24,567 [ search_worker_0][        models][    INFO] Upserted 1 pokemon, 53 pokestops, and 16 gyms
2016-08-07 20:45:25,793 [ search_worker_1][        search][    INFO] Search step 10 beginning (queue size is 261)
2016-08-07 20:45:25,928 [ search_worker_1][        models][    INFO] Upserted 0 pokemon, 50 pokestops, and 18 gyms
```

In the above, there are 8 accounts and scan_delay is 11:

```
2016-08-07 20:22:36,520 [ search_worker_0][        search][   DEBUG] Delaying thread startup for 0.00 seconds
2016-08-07 20:22:36,520 [ search_worker_1][        search][   DEBUG] Delaying thread startup for 1.38 seconds
2016-08-07 20:22:36,521 [ search_worker_2][        search][   DEBUG] Delaying thread startup for 2.75 seconds
2016-08-07 20:22:36,521 [ search_worker_3][        search][   DEBUG] Delaying thread startup for 4.12 seconds
2016-08-07 20:22:36,521 [ search_worker_4][        search][   DEBUG] Delaying thread startup for 5.50 seconds
2016-08-07 20:22:36,521 [ search_worker_5][        search][   DEBUG] Delaying thread startup for 6.88 seconds
2016-08-07 20:22:36,521 [ search_worker_6][        search][   DEBUG] Delaying thread startup for 8.25 seconds
2016-08-07 20:22:36,525 [ search_worker_7][        search][   DEBUG] Delaying thread startup for 9.62 seconds
```

## Motivation and Context

Reduces load on the PTC login servers, and can prevent login throttling caused by too many login attempts from a single IP address in too short of a time.

## How Has This Been Tested?
Ran many startups, all of which had fewer login issues than normal.

This was run on Ubuntu 16.04.1, but I don't think it should affect any platforms or environments differently.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by hhu94** [comment]
I like the idea, but this is only noticeable for the use case of less than 10 accounts. Why not set a hardcoded delay value of say 1 second instead?

**Comment by marumari** [comment]
You could do that, but if you have, say, 100 accounts and a scan_delay of 10, then the map will fill out somewhat awkwardly.  And if you have that many accounts, you'll be pushing so many requests per second per IP that it won't make much difference once all the threads have started.

**Comment by marumari** [comment]
And by awkwardly, if you have 100 accounts and a scan delay of 10, thread 0 will have filled out grid position #1, 101, 201, 301, 401, 501, 601, 701, 801, and 901 by the time thread 100 starts up and scans grid position #100.

**Comment by hhu94** [comment]
The awkwardness would only be at startup. After rethinking it, hardcoding the value would make testing more annoying because of the slower startup.

That aside, I feel like this is a fix to a non-existent problem, I haven't experienced any kind of login throttling, and the login process is fail safe as it retries when it fails.

**Comment by marumari** [comment]
It has happened to me on occasion, and throttling aside, it's about being a good network citizen. This is especially important for the PTC servers, which are much less robust than Niantic's API servers.

Even if you _do_ have 100 accounts and a scan delay of 10, with this patch you're doing 10 logins per second instead 100 logins all at once.

**Comment by hhu94** [comment]
I'll leave this one for other members to judge :)

**Comment by marauder37** [comment]
+1 on this, it would smooth various things out and we had to implement it hackishly in beehive

**Comment by invisiblek** [comment]
+1 i'm on board with this

**Comment by chuyskywalker** [comment]
I think @hhu94's idea of a hard coded 1 second per thread delay would work fine. IE: for thread 0, delay 0 seconds, for thread 3, 3 seconds, and so on. 100 threads would all be fully in the processing set by < 2 minutes, but it'd spread the logins out nicely.

> Thread 0 will have filled out grid position number 1, 101, 201, 301, 401, 501, 601, 701, 801, and 901 by the time thread 100 starts up and scans grid position number 100.

The threading doesn't work like that. It creates on large queue of items in the spiral hex order and any thread running picks "the next one". Cells are not assigned to specific threads.

**Comment by marumari** [comment]
Fair enough. If folks would prefer a hard-coded limit of a second or
half-second or whatever, just let me know. Would be super quick to change
it.

On Aug 7, 2016, at 11:07 PM, Jeff Minard <notifications@github.com> wrote:

I think @hhu94 <https://github.com/hhu94>'s idea of a hard coded 1 second
per thread delay would work fine. IE: for thread 0, delay 0 seconds, for
thread 3, 3 seconds, and so on. 100 threads would all be fully in the
processing set by < 2 minutes, but it'd spread the logins out nicely.

Thread 0 will have filled out grid position number 1, 101, 201, 301, 401,
501, 601, 701, 801, and 901 by the time thread 100 starts up and scans grid
position number 100.

The threading doesn't work like that. It creates on large queue of items in
the spiral hex order and any thread running picks "the next one". Cells are
not assigned to specific threads.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PokemonGoMap/PokemonGo-Map/pull/55#issuecomment-238137896>,
or mute the thread

**Comment by DomGrieco** [comment]
Why not make that hard coded delay a flag so people can choose to set it to whatever they would like. Something along the lines of --auth-delay. People who want to keep it the way it is won't be bothered and people like you and I can set it to whatever number we please :+1:

**Comment by marumari** [comment]
My only concern with making it a flag is that eventually you end up with something like curl, where there are so many flags that it becomes a bit unwieldy and the documentation becomes too verbose.  The nice thing about the current patch is that it doesn't really cause any changes significant enough to require a switch.  Most people's scan delays are 7-10, so it just spreads those logins out a bit.

If we make it one login per second, that could be annoying for people with large numbers of accounts who are mapping very large areas.  In that case, I suppose I could see having the default be one second, but allowing people to lower it.  We'd be adding in an option to allow people to continue to be bad network citizens, but if they're making 100 requests/sec, then they're already pushing things.

Any of these options are simple enough to implement, just need somebody to make a decision on direction.

**Comment by invisiblek** [comment]
Yea, we're not making another command line option for this. We have too many as it is imo

**Comment by marauder37** [comment]
Decision made, cheerio ;-)

**Comment by marauder37** [comment]
(We can always fiddle with it again if necessary)

**Pull request merged**
