### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ryanzab**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by medghaim** [comment]
Squash

**Comment by ryanzab** [comment]
What?

**Comment by Octylpy** [comment]
@ryanzab Please squash and merge everything into a single commit

**Comment by ryanzab** [comment]
@Octylpy didn't mean to click this... how do I delete this. Sorry for the inconvenience.

**Pull request closed without merging**
