### PR TITLE
Added method to only allow a single info window.

### PR DESCRIPTION
**Pull request by joshluongo**
## Description
_This was from the [previous repo](https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2688)._

I've made it so you can only open one info window at a time if you're on a compact device. All of the info windows are stored in a hash map within `map_data`.

I've also added a convince function `clearInfoWindows()` to close all open info windows.

A compact device is defined as a viewport that is less than 768px.

## Motivation and Context
On a phone the screen get's very crowded with multiple info windows open. If the user keeps tapping the marker multiple times then it can be frustrating to close all of the windows.

## How Has This Been Tested?
This is a minor change but I've tested it on iOS and Safari on Mac OS X.

## Screenshots (if appropriate):
_Can't show the change in a screenshot._

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by joshluongo** [comment]
I've rebased this pull request.

**Comment by Cy4n1d3** [comment]
Would be a great addition for mobile devices.

**Comment by primaxius** [comment]
-1 as users should be allowed to open as many infowindows as they want.

**Comment by joshluongo** [comment]
This was a fix for mobile users. The small "X" on the info windows makes it a pain to close multiple open windows.

**Comment by jchristi** [comment]
+1, this feature is definitely better usability (I'd apply to desktop browsers too). Who wants to open up a ton of info windows??

**Comment by nunopitbull** [comment]
Maybe add a button to enable/disable it under Style?

**Pull request closed without merging**
