### PR TITLE
Heatmap based on PR 3224 of the original repository.

### PR DESCRIPTION
**Pull request by visusnet**
Implemented heatmap based on PR 3224 of the original repository.

## Description
I've taken the changes of PR 3224 (https://github.com/AHAAAAAAA/PokemonGo-Map/pull/3224/files) and separated the heatmap's pokemon from pokemon that are used for notifications and exclusions.

## Motivation and Context
Because... well, I can.

## How Has This Been Tested?
Manually.

## Screenshot:
Screenshot

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by G1K** [comment]
Experience problems when connecting heatmap.
1) retain or reset value when you refresh the page (cookies)
2) With an empty field, a request or a list of likely kakimto alert, or no indication of Pokemon that provokes a huge request not limited to the territorial base. In these 700 000 records get a huge load

**Comment by visusnet** [comment]
@G1K Do you have a suggestion how to improve the heatmap based upon the issues you've experienced?

**Comment by eborned** [comment]
@visusnet I would send the current bounding box of the Google Map to the API, selecting only the Pokemon that are visible. Another option is using a WeightedLocation object for Google Maps. You can then group on lat/long and only send the number of spawns for that location. In my case, this brings the number of unique datapoints from 17.889 to 1781.

**Comment by visusnet** [comment]
@eborned I guess I will implement your first suggestion. The second one requires that the server-side needs to aggregate spawn points that are close because Pokémon never really spawn at the same location.

**Comment by eborned** [comment]
@visusnet In my case, they do. Every spawn location (exact lat, long) has about 10 spawns.

**Comment by visusnet** [comment]
@eborned You are right that Pokémon spawn at the same location multiple times (~10 times), e.g.:

```
mysql> select pokemon_id, count(pokemon_id) as number_of_pokemon, latitude, longitude from pokemon group by pokemon_id, latitude, longitude having number_of_pokemon > 1 order by number_of_pokemon desc, pokemon_id asc limit 30;
+------------+-------------------+------------------+------------------+
| pokemon_id | number_of_pokemon | latitude         | longitude        |
+------------+-------------------+------------------+------------------+
|         16 |                11 | 51.4423849999386 | 7.00497044932601 |
|         96 |                11 | 51.4431150696644 | 7.01342350460574 |
|         96 |                11 | 51.4420446956382 | 7.02027169174981 |
|         96 |                11 | 51.4377022249979 | 7.00745268801107 |
|         16 |                10 | 51.4367613045074 | 7.01077349356946 |
|         16 |                10 | 51.4395135366184 | 7.00749084743098 |
|         96 |                10 | 51.4416973567069 |  7.0136937271761 |
|         96 |                10 | 51.4366137883899 | 7.00498071127562 |
|         96 |                10 | 51.4390642463785 | 7.00811012912863 |
|         96 |                10 | 51.4410459668259 | 7.01080790425856 |
|         96 |                10 | 51.4426595361337 | 7.01414595163875 |
|         19 |                 9 | 51.4377057363939 |  7.0128956166796 |
|         19 |                 9 | 51.4367065075794 | 7.02405213822739 |
|         19 |                 9 | 51.4398497075685 | 7.01563479166835 |
|         96 |                 9 | 51.4385167032092 | 7.00211177431805 |
|         96 |                 9 | 51.4415217305956 | 7.01249799615915 |
|         96 |                 9 | 51.4400075131345 | 7.01850087184719 |
|         96 |                 9 | 51.4399580085341 | 7.01932579823391 |
|         96 |                 9 | 51.4391286868598 | 7.01116147457249 |
|         13 |                 8 | 51.4360523594862 | 7.01572272300446 |
|         16 |                 8 | 51.4397348579766 | 6.99415226935886 |
|         16 |                 8 | 51.4367065075794 | 7.02405213822739 |
|         16 |                 8 | 51.4394190546265 | 7.00631582576376 |
|         16 |                 8 | 51.4353039957651 | 7.00758043745337 |
|         19 |                 8 |  51.435195393886 | 7.01351793111383 |
|         19 |                 8 | 51.4363204446403 | 7.02636215940936 |
|         19 |                 8 | 51.4492603401547 | 7.01131033575943 |
|         19 |                 8 | 51.4399708083718 | 7.00949002677699 |
|         19 |                 8 | 51.4673697123851 | 7.01734855682115 |
|         19 |                 8 | 51.4356084228686 | 7.01487804157087 |
+------------+-------------------+------------------+------------------+
```

I didn't know that this is the case since a nest consists usually of multiple spawn points for the same Pokémon. I have implemented the weighted locations and bounding box.

**Comment by Cy4n1d3** [comment]
Generally it does work on my local install, I do get some errors from time to time though:
```
[2016-08-12 11:56:09,259] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch
_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_e
xception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1637, in full_dispatch
_request
    rv = self.preprocess_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1837, in preprocess_re
quest
    rv = func()
  File "C:\Python27\lib\site-packages\playhouse\flask_utils.py", line 165, in co
nnect_db
    self.database.connect()
  File "C:\Python27\lib\site-packages\peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "C:\Python27\lib\site-packages\playhouse\pool.py", line 127, in _connect
    raise ValueError('Exceeded maximum connections.')
ValueError: Exceeded maximum connections.
2016-08-12 11:56:09,259 [      Thread-305][           app][   ERROR] Exception o
n /raw_data [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch
_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_e
xception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1637, in full_dispatch
_request
    rv = self.preprocess_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1837, in preprocess_re
quest
    rv = func()
  File "C:\Python27\lib\site-packages\playhouse\flask_utils.py", line 165, in co
nnect_db
    self.database.connect()
  File "C:\Python27\lib\site-packages\peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "C:\Python27\lib\site-packages\playhouse\pool.py", line 127, in _connect
    raise ValueError('Exceeded maximum connections.')
ValueError: Exceeded maximum connections.
```
Corresponding browser log:
```
jquery.min.js:4 GET https://MY-URL/raw_data?[SNIPPED] 500 ()
```
My educated guess: `/raw_pokemons_history` is being called every `updateMap()`. As fetching the data from MariaDB takes a while, the previous request is not even finished as the next one is queued already. It seems like the heatmap database calls are blocking the regular update calls (thus the connection exception).

As `/raw_pokemons_history` is already returning around ~200 KB of data in my case (and my database does not have millions of entries), it might be a good idea to do such calls on a different thread - and surely not on every `mapUpdate()`! I would either add a button to generate the heatmap or use a different refresh interval (more like every 5 minutes).

Those JSON responses are that huge, I can't even format (pretty print) them using Notepad++...

Another solution could be the aggregation of pokemon data on the database call, which would require some logic though. Furthermore I need to read up on Google's heatmap API I guess...

**Pull request closed without merging**
