### PR TITLE
Notification Improvements

### PR DESCRIPTION
**Pull request by DiscoTim**
## Description
Fixes notification bugs on mobile and desktop and includes a number of new features.
-sound packs
-voice (text to speech) notifications
-notifications based on distance
-functional service worker on mobile

## How Has This Been Tested?

Basic table of supported/tested features:

Windows:

Chrome: Notifications, Sound, Voice
Firefox: Notifications, Sound, Voice (with about:config, media.webspeech.syth.enabled set to true)
Edge: Notifications (must have the anniversary update installed), Sound, Voice
 
Android: 

Chrome: Notifications (With SSL, ie. site uses https), Sound, Voice
Firefox: Notifications, Sound,  (Voice not supported by Firefox on Android yet)

IOS (browser notifications are not supported by iOS):

All: Sound, Voice

On Firefox the setting in about:config , media.webspeech.syth.enabled must be changed to true for voice notifications to work. They will work with no changes on chrome.

Chrome/Android push notifications require SSL (HTTPS) to work, this is a requirement of chrome. Sound and Voice notifications will work without SSL.

iOS/All - iOS does not support local web notifications. Sound and Voice will work.

## Screenshots (if appropriate):
notifications

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Becold** [comment]
Does it work on mobile ?
This might conflict https://github.com/PokemonGoMap/PokemonGo-Map/pull/623

**Comment by Studio-XP** [comment]
Would it be possible to make this into it's own js file and load it from map.html? I feel that it would clutter up the already messy map.js

**Comment by DiscoTim** [comment]
@Becold it does work on mobile. It shouldn't conflict with #623, as it uses the same basic libraries except newer versions that have some fixes. it does superceed #623 though, in that it does all that it does + additional features. additionally the notification in mobile is functional and will open the map when clicked, and has a some mechanisms to prevent notification flooding.
 
if you've used #623 you'll need to stop/uninstall the service worker as they are somewhat persistent.

if you are using firefox you'll will need to change the setting in about:config media.webspeech.syth.enabled to true for voice to work. it will work out of the box in chrome.

**Comment by DiscoTim** [comment]
@Studio-XP what is too much or you think may not be wanted?

it incorporates a number of other pr's and also addresses some of the issues in some of them (and current basic broken things)
Your pr https://github.com/PokemonGoMap/PokemonGo-Map/pull/623 , https://github.com/PokemonGoMap/PokemonGo-Map/pull/723 , https://github.com/PokemonGoMap/PokemonGo-Map/issues/250 ,  https://github.com/PokemonGoMap/PokemonGo-Map/pull/484
and some of https://github.com/PokemonGoMap/PokemonGo-Map/pull/866 (i plan to do more along these lines), https://github.com/PokemonGoMap/PokemonGo-Map/pull/331 , http://feathub.com/PokemonGoMap/PokemonGo-Map/+37

I think distance is a key concept in the notifications - to help prevent notification flooding (especially on mobile), and also with spawnpoint scanning able to cover much larger areas for the average user, I think its important to offer some simple control and distinction over what/how and far/close to be notified for.

Currently there is no way to turn a notification feature on or off, eg.. i can't have sound with/out popup, so distance selectors make sense and take up little more ui space than on/off toggles.

One feature I wanted to implement was text to speech, I find it works incredibly well (especially while driving), it has good native browser support and very simple to implement, but then again a way is needed to control the other notifications. and same will be true if any other notification mechanisms are added.

Different sounds (thanks to @drakeirving) which it will not load unless selected (for anyone concerned on mobile), and nearby notifications, I think are usefull and not much of a stretch.

I had considered moving notifications out of map.js, the bulk of map.js for everyone is the nav setup and storage, aside from that, i've kept the core of this pr in one section https://github.com/DiscoTim/PokemonGo-Map/blob/notifications/static/js/map.js#L1632-L1840 ..so not sure what to do here

**Comment by Acidvenom73** [comment]
@DiscoTim Not sure if it's related to the PR, but when using it the webUI won't properly load.. see [here:](https://i.gyazo.com/360613c113200bd477930f243636cce8.png) 
Then if I open the webconsole I get
`GET http://localhost:5000/static/dist/js/push.custom.min.js 404 (NOT FOUND)`

**Comment by Becold** [comment]
@Acidvenom73 npm run grunt

**Comment by Acidvenom73** [comment]
@Becold Dumb mistake.. Thank you!

**Comment by itztq** [comment]
How can i download this to test it?

**Comment by DiscoTim** [comment]
@itztq a simple way to download to test is grab it from my branch https://github.com/DiscoTim/PokemonGo-Map/tree/notifications , thats what this PR would merge from.

**Comment by Acidvenom73** [comment]
@DiscoTim Tried today, push notifications didn't seem to work on mobile. Tested on several android phones using chrome. Permissions seems to be in order. If I enable notifications the pokemon jumps up and down on the map as usual but no notifications. The Voice and sound does seem to work though. Am I missunderstanding the goal of this PR completely?

**Comment by DiscoTim** [comment]
@Acidvenom73 are you using SSL (https)? it is a requirement of chrome/android notifications. there is nothing we can do about it programmatically. If you are, they should be visible as system notifications, the type you pull down from the top in android, they won't be visible in the map. this app supports ssl, so you would need to set that up if you have not.

**Comment by Infernoman** [comment]
Hey @DiscoTim anyway you could make it so that when zoomed the jumping pokemon aren't affected? Before this commit, the pokemon would jump until clicked on regardless if the map was zoomed in or out from its current position. After this commit the pokemon jump until clicked on. Or until the zoom changes.

**Comment by Infernoman** [comment]
Was this tested on an iphone at all? 
https enabled.
location tracking enabled.
push notifications enabled.
very rare and ultra rare enabled.
but no notifcations, through chrome, safari, or when added to the homescreen

**Comment by DiscoTim** [comment]
@Infernoman not sure what is going on with the jumping pokemon, didn't change any of the code involved with that, other than move 3 lines that start the bouncing. but i will look at it.

If you go here and push the demo button do you get a notification? https://nickersoft.github.io/push.js/

that is the library it is using to call the right notification function for different browsers.

I didn't test iphone, these libraries are supposed to be cross platform/browser, i will if necessary.

.

**Comment by Infernoman** [comment]
Unfortunately it does not support iphone's on chrome, safari or when added to the homescreen as an application.

**Comment by DiscoTim** [comment]
@Infernoman does that mean the demo site https://nickersoft.github.io/push.js/ did not give you a notification on iphone?

**Comment by DiscoTim** [comment]
@Infernoman i'll contact you on discord, i'd like to see this working on ios as well.

**Comment by DiscoTim** [comment]
@Infernoman zooming no longer affects bouncing Pokemon. Thanks for pointing this out.

The way it works now is, it considers the bounce to be part of the notifications, so the 'Notifications' switch has to be turned on for bouncing. If someone only wants bouncing, they could just turn off the other notifications.

I considered adding the same type of distance selector as the other notifications or on/off toggle for bouncing... but i am not sure.. might be overkill

**Comment by Qualimiox** [comment]
I just tested it at localhost and it worked pretty well. The default distances were a little low, but it's an easy change by editing the .json

However, the only way I could get the soundpack to work was by using Microsoft Edge. Both Chrome 52 and Firefox 48 didn't play any sound when the Pokemon Cries were selected. They both worked fine with the default sound, though. Since this was at localhost I didn't use SSL, but Location worked, so that shouldn't be the issue, right?

**Comment by DiscoTim** [comment]
@Qualimiox SSL shouldn't make a different for sounds, it only effects the push notifications. It takes a few seconds for the sound pack to load after it is selected, did you wait for new pokemon to appear? Also try refreshing the site on chrome/firefox your old settings/files from the main branch may be still taking hold. If you are on discord I can try to help you out there as well.

**Comment by DiscoTim** [comment]
In follow up to @Infernoman comments. iOS does not support local web notifications. It does support sound and voice. This is a limitation of iOS.

"Notifications for websites do not appear in iOS" - https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/Introduction/Introduction.html

https://onesignal.com/blog/when-will-web-push-be-supported-in-ios/

**Comment by DiscoTim** [comment]
@Qualimiox thanks for the feedback. In what way were the default distances fairly low? do you think there should be more "less than" distances? or do you mean the values they are set at by default when the app first loads?

**Comment by Cubkyle** [comment]
I like this. Would it be possible add an option to specify a location for the nearby setting? My start point is not actually near where I am, and I imagine this can be the case for other people too, so nearby isn't useful if it's notifying based on the map center.

I don't know if this is a bug or intended, but the notifications don't seem to be persistent. Using Edge on Windows 10 and Firefox on Android, the notifications are deleting themselves from the notification center and notification drawer, which was not the case before I started using this. No SSL set up, if it matters.

**Comment by DiscoTim** [comment]
@Cubkyle i'm working on another pr that allows you to specify or control the location notifications are based on.

Persistent notifications wasn't a bug, they were set to timeout after 5 seconds, but i see that isn't desirable so i am removing it. I'm also adding a couple other things so it works better in FF/android and Edge/Windows.

**Comment by DiscoTim** [comment]
@Cubkyle this PR adds what i think you are looking for https://github.com/PokemonGoMap/PokemonGo-Map/pull/1086 , let me know if it isn't what you are referring to.

**Comment by Cubkyle** [comment]
As I mentioned on #1086, it and this pull work brilliantly together.

I yanked out lines 260 - 266 in push.custom.js and committed on my local test, and that seems to have restored persistent notifications. For me, it'll do until someone who knows what they're doing comes along to do it the correct way!

**Comment by DiscoTim** [comment]
@Cubkyle  that would do it :) the actual line is 1945 in map.js 'timeout: 5000,' , pulling that out has the same effect.

It will be removed in the next commit.

**Comment by nunopitbull** [comment]
Awsome PR!
Just missing what I wrote you in Discord to fine tune it! :P

**Comment by DiscoTim** [comment]
this pr is is in the process of being overhauled within the next couple days.

**Comment by primaxius** [comment]
Please reopen and update when it's no longer a WIP.

**Comment by CoolCanuck** [comment]
WIP? This worked great for me...

**Comment by nunopitbull** [comment]
@primaxius Why was this closed? Worked 100% fine for me even in togetherness with "gym side bar" with IVs and Move Sets. Was perfect and well organized.

**Pull request closed without merging**
