### PR TITLE
Add scan-here button

### PR DESCRIPTION
**Pull request by tkSimon**
## Description
Adds a "scan here" Floating Action Button at bottom center of the map. When clicked/touched, will set the current map center as new search location.

## Motivation and Context
When outside hunting Pokemon you often want to check a few nearby places before deciding which way to go. This is way more convenient when you can just move the map one or two kilometers/miles and tap "scan here" instead of having to type in the name of some location.

## How Has This Been Tested?
Tested using docker.

## Types of changes
[X] New feature (non-breaking change which adds functionality)

## Checklist:
[X] My code follows the code style of this project. (I think?)

### CODE REVIEW

**Comment by DomGrieco** [comment]
Please make this an option; do not force this into all our maps!

**Comment by tkSimon** [comment]
The description is actually outdated (copied from PR to AHAAA....'s repo), it's not a FAB at the bottom center of the map: http://imgur.com/a/0u7OQ
Still want this to be an option?

**Comment by HinoReo** [comment]
I think it should be an option.

I run a small town pogo community and I have 8 fixed points of where my scrappers start scanning. I don't want these to move, but I want my community members to be able to scan outside of the range of my scrappers and/or refresh certain parts of the map on demand.

**Comment by tkSimon** [comment]
@HinoReo sorry, I don't understand... you comment sounds contradictory to me.

Btw, when starting the server with `-fl` the scan FAB is hidden.

**Comment by FlarumHostingCo** [comment]
Would like to see a header option like you use to have.  Hard to adjust the search button to space at same place on different size mobile devices

**Comment by tkSimon** [comment]
Now that i implemented the FAB, i actually like it better than in the header. It's way less obtrusive like that. The FAB is always horizontally centered and near the bottom of the page, no matter the display size or orientation.

iPhone 5: http://imgur.com/a/sqKL6
iPhone 6: http://imgur.com/a/EOQCl
Galaxy S5: http://imgur.com/a/E1Gtq
Nexus 5X: http://imgur.com/a/btYjI
Nexus 6P: http://imgur.com/a/65Xbq

**Comment by realbunny** [comment]
It should still be an option, i host my map for a small town and share the it. So i don't want people changing the location

**Comment by laernumoretz** [comment]
Same, needs to be an option. I have a few morons around here who will enable that thing and break it for everyone including themselves if more then 1 is doing it at the same time

**Comment by JZ6** [comment]
Honestly we cannot cater to people hosting servers, as this project is mainly for people running local versions, so +1 from me

**Comment by DomGrieco** [comment]
@JZ6 It is hosted locally although I'm not the sole user. This would be really annoying and even more annoying if I have to remove this PR every update if it gets committed as is.

**Comment by tkSimon** [comment]
@realbunny as i wrote earlier. If you start the server with `-fl` option, the scan-here button will not be shown. Also, if ppl make the button visible using dev tools, it still wont work because the request is blocked server-side if started with -fl. Please read the documentation.

**Comment by wesleytsai** [comment]
Yeah, like tk said, it doesnt show up with fixed location on.. Lgtm

**Comment by SebCorbin** [comment]
👍

**Comment by andykemp** [comment]
👍

**Comment by tkSimon** [comment]
Further modified to indicate whether search is enabled or disabled by setting opacity to .5 when search is disabled. Pressing FAB when scan is disabled turns search on again and changes location.

Tested with Chrome on Linux & Android 6 device accessing same pgomap instance toggling between states using search check box and FAB.

**Comment by tkSimon** [comment]
Rebased, fixed code style, added mitigation for [changeLocation bug](https://github.com/PokemonGoMap/PokemonGo-Map/commit/513a6fc3c97fcc426efc518975fe547ca527297f#diff-052cfee44ae462a28560613abd7fdd14R881)

**Comment by tkSimon** [comment]
#164 would be a nice alternative to the 3rd commit of this PR

**Comment by Slivo-fr** [comment]
#164 merged, you should remove your third commit

**Comment by tkSimon** [comment]
@Slivo-fr done

**Comment by fakemustache12** [comment]
Maybe use the search glyph instead of location? Makes more sense as pressing button will search in current center location.

**Comment by tkSimon** [comment]
Changed the icon locally, but can't test atm. Think i got soft-banned...

**Comment by tkSimon** [comment]
updated original post to correctly reflect changes

**Comment by tkSimon** [comment]
Vote for this feat at http://feathub.com/PokemonGoMap/PokemonGo-Map/+14 if you like it

**Comment by Worthy7** [comment]
So, because we are moving away from the hexagon scanning, and into spawn-point scanning, what would be ideal is if this was more dyamic.
Your button is nice but IMO it is overkill now. instead, my ideal is that the server will track a user, and scan all pokemon spawn points around them (using the latest TBTerra algo) https://www.reddit.com/r/pokemongodev/comments/4wxteh/i_implemented_tbterras_spawntracker_into/

This way, the user just walks, and the scanning is taken care of.

**Comment by Slivo-fr** [comment]
Well even with new scanning method, having a way to place the center of the scanning were the user is without having to type an address is needed

**Comment by Slivo-fr** [comment]
As the implementation of TBTerra is an option (run with SS) this feature is still needed for the classic mode. Maybe hide the button when -ss is used ?

**Comment by faketits** [comment]
hi, i don't know what has changes in the base source files, but adding the 3 changes in files ain't adding the set-location button on my web... clue some1?

**Comment by Slivo-fr** [comment]
Same issue on my side, button don't show up

**Comment by Slivo-fr** [comment]
Could I suggest a switch or an option somewhere to toggle the search button between using map center or user location ?

**Comment by jaquer** [comment]
@tkSimon: Do you plan on keeping this updated with the current tree? I don't know why it hasn't been merged, since it got so much love of feathub, but I've been using it as-is anyway. Except it won't apply cleanly now.

If you've lost interesting, I'll take a look at what needs to be done, see if I can figure it out.

**Comment by darkelement1987** [comment]
Added the 3 files to my server and rebooted but the button is not showing up, even after hard refresh.

**Comment by tkSimon** [comment]
Hi, sorry, was on vacation for a few days, no access to laptop/internet. Will try to update this later today.

**Comment by tkSimon** [comment]
@jaquer @darkelement1987 rebased, please check now

I would love to see this merged but i won't check if this feature still works every other commit to develop. This PR has been around since before the project changed ownership, and there's no word from contributors if this will be merged eventually or not...

To some extent I understand that there are more pressing issues that need attention at the moment, but this is a rather small addition. "Addition" because it doesn't require changing any of the existing code, so I don't understand why it's not being merged tbh.

It's kind of the opposite of what i'm used to at work, where product owners keep pushing features, almost neglecting technical dept and bug fixes ;)

**Comment by rehand** [comment]
+1 for merging this PR into branch develop.

**Comment by joeubi** [comment]
+1 to get merged... recently broken by updates though.

**Comment by cbogithub** [comment]
I thinks no need creat a button, ==> Add marker to Google Map on Click
http://stackoverflow.com/questions/15792655/add-marker-to-google-map-on-click

**Comment by maddhatter** [comment]
I have been merging this into my copy of this since the get-go. +1 to merge it.

@cbogithub I definitely want a button. I use this to position my 1 non-fixed location scanner to wherever I need it. I do so almost exclusively on mobile, and don't want to have it jumping around every time I touch the map.

**Comment by gaetandumont** [comment]
+1 for merging this PR :)

**Comment by Slivo-fr** [comment]
It seems there is some conflict with the base branch, even if github say otherwise.
I cannot apply the diff on head.

**Comment by primaxius** [comment]
@tkSimon A few small suggestions to get this approved and merged. 
1. Resubmit as github isn't tracking this properly ( it needs a rebase on your end too)
2. As you noted it doesn't show when -fl is used, it shouldn't show when -os or -ss area used as well as it simply won't work.

I have closed this PR so you can resubmit. Looking forward to being able to approve this.

**Comment by tkSimon** [comment]
Sorry guys, stopped playing quite a while back. If any of you want to, feel free to rebase the PR or rewrite from scratch.
Cheers

**Comment by Samael27** [comment]
It's already done on the PR #1307. Thanks for your work ;)

**Pull request closed without merging**
