### PR TITLE
Speed scan v2

### PR DESCRIPTION
**Pull request by Artifice**
# Improvements and enhancements to Speed Scan

## Description
* Fix bug that caused 15 minute spawns to be scanned as 60 minute spawns. This caused lots of "hhhs kind spawnpoint 1234asbcd has no pokemon xx times in a row" messages, reduced Spawns Found % to low percentages, increased captchas since unnecessary scans were being done, and gave a general feeling of malaise when scanning.
* Converted from vincenty to equirectangular approximation distance calcs. 20X increase in distance calc speed. Significant decrease in CPU load and load time.
* Fix bug that stops 5 minutes statistics from printing out.
* Add ability to use -bh with multiple workers/hive. New cmdline arg is -wph #, where # is the number of workers per hive.

## How Has This Been Tested?

Tested by myself and multiple others

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by smc87** [comment]
Please pull out the speed scheduler out into a re-usable form for other schedulers.
It would really help for larger scale maps that could avoid some of the extra overhead of -speed by using -ss with a json whilst using your very nice speed implementation.

**Comment by Holzberg** [comment]
this is exciting.  is it ready for testing?

**Comment by sclo012** [comment]
This is great, also, are you willing to fix -ss to use your code? it is useful for someone that already has 100% spawns and would like to skip the initial scan.

**Comment by shockler** [comment]
i scanned ~60k SP with 1530 and hope that you can fix so that I can use them with your PR

**Comment by sclo012** [comment]
the db schema is different in 1530 and it doesn't classify spawn points. It is doable but not gonna be straight forward to upgrade to this.

**Comment by smint86** [comment]
Suggestion: It would be great for users, if there was a small green dot or something right beside the despawn timer, if it is a spawnpoint with TTH found.

**Comment by kbtbc** [comment]
8+ more hours now tested with v2 ... sorry, but still going nowhere fast.
Log file:  https://drive.google.com/open?id=0B9aHyxCdMlQSMGJCSzFlbklMdWs

**Comment by shockler** [comment]
@Artifice i'm using -bh -w -wph -speed -kph. The 1st run is ok, but when I relaunch, all of them keep saying "Nothing to scan"

**Comment by shockler** [comment]
image

**Comment by shockler** [comment]
Maybe I know why, accounts which get error are at area that doesnt have any spawnpoints.

**Comment by adrianmateii** [comment]
after last update i see: Moving 0m to step 926 for a spawn (always 0m). Hope this is just a display bug and distances are calculated :d (or else speed/next best spawn to scan etc won't work right?

**Comment by Artifice** [comment]
@adrianmateii Yo, Adriaaaaaaaan! Hey, how is the CPU load with the new distance calcs?

Yes, that was a display bug. Fixed in a recent commit.

**Comment by adrianmateii** [comment]
@Artifice no CPU problems since lasts commits. and is indeed faster... still using 14 instances with st25 and works great

**Comment by dikkedeur** [comment]
i have tested this PR today on a clean install.
all went well the first 5 minutes, after that my workers slowly died with the message
that they where receiving no data anymore.
propably ip banned or captha or -ng or -nk some kind of message.
seems like a sort of account ban, since out of 110 accounts roughly 2 or so still got some data.

the first 5 minutes the map was filling extremely fast!, so i was happy to see that but i think it was too much overkill.

i use -speed and -kph 30
rest is default except for recaptha key etc.

**Comment by necre** [comment]
how would i use -bh and -wph together? ive tried -st 15 -bh -wph 35 -w 665 but i get an error lol any advice on proper use?

**Comment by Stuck7hrottle** [comment]
I'm probably wrong, but I think your math is off. 15*35=525. Or 665/35=19. I think you need to change your -st or your -w to match the formula. The other option is to increase your -wph, but 665/15=44.33 which is not possible.

**Comment by mykill18** [comment]
@dikkedeur Same here

**Comment by dikkedeur** [comment]
@mykill18 glad im not the only one then.. i never encountered ipbans or temp bans on accounts on how it goes.
the extra speed is awesome, but not when you encounter bans due the massive speed this PR gives to the scan.

maybe our commandline is not correct and we mis something, that might be the case... i dont know.
what is your commandline or config @mykill18 ??

**Comment by Holzberg** [comment]
I am not sure if I had the same problem ad @dikkedeur or not, but 18 out of 20 workers in the status screen said "Nothing to scan".  They said for for about 20 minutes and then I stopped the server and I have not run it since after reading the posts about banned accounts.  I don't think my accounts are banned though.  I think there was just something wrong with the scheduler that it was not doing anything.

**Comment by shockler** [comment]
@dikkedeur i got the same issue
When I run initial scan, it seems to be lighting speed but easy to get soft IP ban and tons of bad-scan + captcha.
if I run >90 workers for initial scan, i get ban immediately, so I can only run ~60.
The captcha rate is about 4 captcha/worker/hour.

**Comment by mykill18** [comment]
@dikkedeur Just "python runserver.py -cf xxx.ini -sn xxx -st 14 -w15 -speed -kph 35 -xxx,xxx -wh xxx" with encounter:True

**Comment by Holzberg** [comment]
Maybe the encounter is what's getting your accounts banned.  That would be a lot like a bot right?

**Comment by divnotded** [comment]
@dikkedeur -st 14 with only 15 workers is not enough [(steps*(steps-1))*3]/20 is this PR recommendation
which is 27.8 or 28 workers using your settings.

**Comment by dikkedeur** [comment]
@divnotded i used 110 workers/accounts, and that was way too much, ipban within 5 minutes, now with 50 i dont have any problems anymore.

**Comment by Artifice** [comment]
@kbtbc Thanks for the logs. As discussed on Discord, the issues you are having on this PR are the same as on current Dev. I will be be looking at the longer DB calls in V3. :)

@sclo012 As discussed on Discord, putting a flat speed limit on existing code would make it very slow to capture spawns and probably miss more. Speed Scheduler converts the existing queue structure from a deque to a list of objects. Since Speed Scheduler or -ss are different options, I would like to leave -ss as it is, so that people have a choice to run the old code if they choose.

@shockler @sclo012 @marbink Has posted steps to convert TTH from PR #1530 to this PR in the description of PR #1530 

@shockler Thanks for the report of the index error. This was fixed in commit a41efa1 in this PR.

@adrianmateii Yes, the moving 0m comments was a display bug. Fixed in commit 5193715 in this PR. Glad to hear the CPU has improved for you!

@dikkedeur Glad to hear speed scan looks faster in filling the initial scan! I think the slow distance calculations was slowing that down. 

@necre Yes, you can use -bh and -wph together, and other have tested this.

@dikkedeur @mykill18 @shockler As for the IP bans, this is controlled by Niantic. It sounds like the PR is working correctly, and this is the same bans you would get with lots of activity from other Schedulers. I recommend adding an scan delay config (-sd 60?) if the scanning is too fast or starting with a lower -st to stage the initial scan.

Thanks all for the testing and code approvals!

**Comment by shockler** [comment]
@Artifice thx, I will try to increase -sd, i didnt think about it, lol.

**Comment by bbdoc** [comment]
How do I launch this for scanning gyms only (-np -nk) ? What scan mode will it use if no spawnpoints to be found ? Will it automatically switch and avoid going through an initial scan for spawnpoint discovery first ?

**Comment by danwie** [comment]
Not sure if this is relevant to this PR. But I'm wondering how I can set a -kph between two values. Maby I'm wrong, but if I set it to a specific value (like -kph 10) it will probably be very easy to detect?

**Comment by bellowsj** [comment]
@Artifice - Ran this overnight and noticed that the map seems to have a few places where it is showing double spawns on a single spawn point. I visited a couple of the spawn points that had double spawns and verified that it does not have 2 pokemon there. Only a single 'mon is actually there. So somehow it is finding 2 pokemon one a single spawn point where only one actually exists in the game. Thoughts?
double_mon1 
double_mon2

**Comment by FrostTheFox** [comment]
Merging ⚡️

**Comment by filippounitn** [comment]
Perfect. -st 27 600 spawns (rural area) 
3 hours only 30 captchas

**Comment by jorgitoh** [comment]
@filippounitn how many accounts / kph?, with -bh?.
@Artifice should i delete the old database with this PR?

**Comment by Artifice** [comment]
@jorgitoh New DB not required.

@bellowsj Thanks for the report on double pokes. Can you find what kind of spawn point those were? hhhs or ssss?

**Comment by bellowsj** [comment]
@Artifice - One was a ssss. Here is the db row: 
`874df52000d | 40.4710400459701 | -111.451762931732 | 2016-12-14 07:17:15 | ssss | +++-  |            0 |        2652 |            2652`

**Comment by bbdoc** [comment]
Hi @Artifice. Can you help on this 

```
2016-12-14 09:13:57,671 [      db-cleaner][        models][   ERROR] Exception in clean_db_loop: Exceeded maximum connections.
Traceback (most recent call last):
  File "/usr/src/app/pogom/models.py", line 1905, in clean_db_loop
    query.execute()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3274, in execute
    return self.database.rows_affected(self._execute())
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/site-packages/playhouse/shortcuts.py", line 203, in execute_sql
    sql, params, require_commit)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3483, in execute_sql
    cursor = self.get_cursor()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3431, in get_cursor
    return self.get_conn().cursor()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3424, in get_conn
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/usr/local/lib/python2.7/site-packages/playhouse/pool.py", line 127, in _connect
    raise ValueError('Exceeded maximum connections.')
```

Was working fine yesterday. I already tried increasing max-connections with no success. I stopped all my instances, rebooted my server (physical server) and tried only launching one single -os instance, and still getting this error.

**Comment by walaoaaa1234** [comment]
@bbdoc using mysql or sqlite?
Use mysql better.

**Comment by bbdoc** [comment]
@walaoaaa1234 Using MySQL.

btw I did some more tests:
- Created a brand new DB and tried to launch -os using dev+1617 : FAIL - 'Exceeded maximum connections
- Created a brand new DB and tried to launch -os using older dev + PR1530 : SUCCESS

So this is clearly linked to this PR (or PR1501) in some way

**Comment by filippounitn** [comment]
@jorgitoh 90-100 accounts 32kph without -bh

**Comment by bellowsj** [comment]
@bbdoc - Have you tried both: (1) increase the --db-max_connections as an option for pokemongo-map and increasing the actual system variable max_connections in mysql. In your mysql terminal try: `show variables like '%max_conn%';` and see what it gives you. Increase it with `set global max_connections = 1000;` or change it in your my.cnf file.

**Comment by smint86** [comment]
@bbdoc Also, are you running db-cleaner on multiple instances? You should start your workers with --disable-clean and only your map could run the db-cleaner. That's how I do it. Maybe it's connected with your error.

**Comment by Thyllz** [comment]
I had to increase both maximum connections through mysql Client command line as well as DB threads through pogo config.ini when I switched to speedscan and speedscan v2 from -bh.

Seems like speedscan is more demanding on sql then other schedulers

**Comment by joekeating87** [comment]
@filippounitn  I am also getting many unscanned points throughout the hour.
screen shot 2016-12-15 at 2 05 49 pm
screen shot 2016-12-15 at 3 31 23 pm
screen shot 2016-12-15 at 3 29 33 pm
screen shot 2016-12-15 at 3 30 14 pm

**Comment by bbdoc** [comment]
Hi @Artifice With spawpoints change which happening tonight, I cleaned my DB and started over with Initial Phase. Anyway, my impression is that in most cases, spawn points remain the same, only TTH are being adapted (at least this is the case one migration every 2). Would there be a way to add an option to launch the script dropping TTH from database so it would search again for TTH when we know a migration happened ? Would probably be less expensive than a full -cd.

**Comment by sclo012** [comment]
@Artifice I found also the same bug @bellowsj saw (2 pokemon on top of each other, but only one of them is currently there, other has a wrong despawn time and should've despawned already). It's always a spawnpoint with kind = ssss and links = +++-, if it helps isolate the bug.

**Comment by bellowsj** [comment]
@Artifice - I'm also seeing what @joekeating87 is seeing where workers are not going to spawn points that should be active. It is missing quite a few 'mon. Also seeing exactly what @sclo012 was describing with double 'mon on a single spawn point.

**Comment by Artifice** [comment]
@bellowsj Thanks for the check on the double spawns. Let me know if you see any that aren't ssss kind. I'm working on tracking this error down.

@filippounitn With the recent migrations, you should probably do a full rescan anyway. Use the -cd option once to purge the DB.

**Comment by bellowsj** [comment]
@Artifice - I did a full drop database after the migration and I'm still having at least 30% of my spawn points missed. 
missed_scans

**Comment by bbdoc** [comment]
@Artifice I've been running 2 instances of the map with -speed for the last 48 hours, and notice that I still didn't reache 100% TTH. This doesn't look normal to me. One instance (st25) has reached 96% TTH and the other one (st40) has reached 88%.

Wouldn't it be possible to introduce some --findTTH parameter which would allow to launch a specific instance dedicated to TTH ? My idea would be to "assign" one worker to each spawnpoint that has no TTH verified yet, and keep it there, scanning every 90s until it gets a valid TTH. Once done this worker can move to the next spawnpoint with no TTH. I guess this would allow to easily find the last TTH we are looking for and get 100%

Another issue I have on my st40, quite rural area (no more than 500 spawnpoints) is that I see a lot of "Not able to reach any scan under the speed limit". This is not normal as I have more than enough workers on the zone. I guess the assignement of workers to a specific spawn is done too late, so that the workers probably have been doing Nothing for several minutes, and when they finally get assigned to a spawn it's too late to get there. Would it be possible to assign workers to spawns more pro-actively on such zones ? This is an issue I don't have with my more dense area.

**Comment by sclo012** [comment]
@Artifice I am still seeing the 1 hour spawns showing double pokemons. But this time, it is hhhs ????
The time that gets shown is obviously not the real despawn time. I think this bug is specific to 1 hour spawns.

**Comment by p4yot** [comment]
Maybe I'm just plain stupid, and I simply forgot to use some parameters.. if so, I apologize for the trouble.

I've been using Spawnpoint scanning for a few weeks now, and I decided to switch to speedscan this morning. I pulled the latest develop branch, added an altitude PR (1591) and started fresh with a new db.

It seems to work fine. I just used an -st 9 to test it out. Initial scan is 100% done and it's still scanning for TTH (~84%). I have a problem though. When I look at the pokemons on the map, none of them shows time... (please see attached screenshot).  Am i missing something here?  Again, it might just be me being stupid.  Wouldn't be the first time! :D 

Thanks!
capture d ecran 2016-12-22 a 16 23 30

capture d ecran 2016-12-22 a 16 23 41

**Comment by thaiminh8xpro** [comment]
@p4yot you are using old #1530, you may need to update your db and relaunch with npm install

**Comment by bbdoc** [comment]
Hi @Artifice 

I've been using speedscan for a while now, but have quite some questions about it now I start to understand a bit more basic process :  

1/ When does speedscan removes a spawnpoint and stops scanning for it ? I have some spawnpoints that have found no pokemons for so many retries, I don't get they are still getting scanned. E.g. : 

```
2016-12-31 20:30:48,082 [ search-worker-7][        models][ WARNING] hhhs kind spawnpoint 47c199779bb has no pokemon 2141 times in a row
2016-12-31 20:30:48,096 [ search-worker-7][        models][    INFO] Possible causes: Still doing initial scan, or super rare double spawnpoint during hidden period, or Niantic has removed spawnpoint
```

2 / I'm getting a lot of "Broken Pipe" in my logs. Process still seems to be running fine but I don't like seeing so many errors in a log. Any idea what it's linked to ?

```
2016-12-31 20:23:11,345 [    Thread-71335][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "./runserver.py", line 86, in run
    run_old(*args, **kwargs)
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/local/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/local/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/local/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

3/ I have the impression I'm getting more and more missed pokemons after running for a while. I was wondering, if I launch an hex scan in a separate process on the same zone, will it add newly discovered spawnpoints to the right tables so that speedscan catches them on next iteration and starts finding TTH for those ?

4/ I'm getting a lot of "Not able to reach any scan under the speed limit" on a larger map with few spawnpoints (st40 - 500 spawnpoints). I have the impression the map is not planning workers soon enough. Would using -bh be a solution for this ?

Thanks

**Pull request merged**
