### PR TITLE
Reduced and improved the requests to emulate an actual API call (as an app would)

### PR DESCRIPTION
**Pull request by chowderchow**
## Description
***IMPORTANT
You will need to enable the elevation API here:***
https://console.developers.google.com/apis/api/elevation_backend

1. Instead of calling checkChallenge whenever 2 consecutive empty calls have been made, it's now scripted to check with every getMapObjects call. 

2. Modified map_request to mimic an actual request envelope as from an app 

3. Modified step_location to contain actual altitude

PSEUDO-CODE FLOW:
```
req = api.create_request()
req.check_challenge()
req.get_map_objects(...)
...
response = req.call()
return response
```
This will make only one API call, so no extra calls due to captcha checking as in the current implementation.

All the captcha flags are the same as before:
```
-cs --captcha-solving
-ck --captcha-key
-cds --captcha-datasitekey (OPTIONAL)
```

## Motivation and Context
Some people were 'experiencing' a higher observed captcha rate while using the current map. I think it may be due to the extra check_challenge request every 2 consecutive empty scans and improper API calls.

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by paraselene** [comment]
Seems Good

**Comment by crckdns** [comment]
that's an "all-in-one-fix" :D purrrfect

**Comment by smc87** [comment]
if you have pulled this before Chowder has had a chance to add to requirements.txt then:
`sudo -H pip install geocoder`

**Comment by k4n30** [comment]
Can the captcha function be updated to automatically report captchas that fail. I've had it happen to me 3 times in the last hour and unless you watch it closely you are paying for bad captcha returns

https://2captcha.com/setting - under additional API requests

**Comment by willydk** [comment]
@smc87 damn... I got 124 captchas in 4 hours...
@k4n30 what would the log say if I get bad captcha?

**Comment by k4n30** [comment]
2016-11-19 16:44:48,221 [ search-worker-1][        search][    INFO] Account xxxxx failed verifyChallenge, putting away account for now

That's what I get now.  If you're asking me what it should say is the same thing plus something like captcha reported (using the api command I linked)

**Comment by willydk** [comment]
i see those in the logs now, thanks

**Comment by shockler** [comment]
I test this PR with 100 new acc and got no captcha for 6 hours
After that i use -ari 900 and -asi 900 and i keep hitting captcha

**Comment by iluretar** [comment]
Google documentation says elevation api is capped at 2500 requests per day on the free tier, are the workers hitting the api each scan?

**Comment by omgms** [comment]
Do I have any problem if I get this error when I start "unable to retrieve altitude from google api, setting to 0"

**Comment by shockler** [comment]
@omgms Chowder said that he will fix it this weekend

**Comment by Saprophator** [comment]
Still getting captchad alot with this pr. settings -sd 40 -st 10 -ld 30

**Comment by tomballgithub** [comment]
How can you tell if you are getting captcha'ed a lot besides looking at your balance on 2captcha?  My balance is going down $2 per day but I would really like to be able to look at the logs or data to see what is really going on per instance.  I also would like to be able to verify that changes like this one or settings tweaks make a difference or not.

**Comment by willydk** [comment]
look at the logs for 2captcha

**Comment by willydk** [comment]
nohup python runserver.py >> nohup_1.out &

**Comment by tomballgithub** [comment]
Many thanks...

**Comment by simonbuehler** [comment]
the Elevation requests should be cached and refreshed when new search location is more than [insert reasonable default distance here] Meters away from the cached value. Add some jitter to it and this should be good. 
The 2500 requests/day limit would be hit otherwise too fast and make this optimization useless

**Comment by SkOODaT** [comment]
works great but doesnt work lol....google api is 2500 dailylimit with 91 accounts its filled within 30 mins

**Comment by FrostTheFox** [comment]
Closed by request for new PR.

**Pull request closed without merging**
