### PR TITLE
Updated for new libs, added submodule and updated docs

### PR DESCRIPTION
**Pull request by FrostTheFox**
Added new pokecrypt repo as submodule, and setup for encrypt lib detection.
## Description

Added https://github.com/pokecrypt/pokecrypt-pgoapi as a submodule, enabled activate_signature in search.py, updated lib location in utils.py and updated encrypt dll names in utils.py.
## Motivation and Context

Allows for better compatibility with latest pgoapi changes.

Also fixes nonetype and encrypt errors. (due to libs being removed from pgoapi.)

## How Has This Been Tested?

Tested on local Windows 10 machine, have not tested on anything other than windows, 0 visible reason as to why it wouldn't work as before.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

I believe I got most of the git clone references in the docs and updated them for recursive, if I missed any please let me know.

### CODE REVIEW

**Comment by FrostTheFox** [comment]
Merging, please report any doc/other errors to me on Discord. https://l.vulpix.us/pgmdiscord

**Comment by Beri51** [comment]
For those running it on a Raspberry Pi, this will brek your manual fix if you followed [my comment here](https://github.com/PokemonGoMap/PokemonGo-Map/pull/1511#issuecomment-258865043).
You need to download the libencrypt-linux-arm-32.so and manually copy it to ~/PokemonGo-Map/pokecrypt-pgoapi/ (or where you cloned the Map).

**Comment by Bart274** [comment]
@FrostTheFox when using the latest version I get this error:
```
C:\PGMkjell>runserver.py --db-max_connections 200 --db-threads 5 -j -enc -gi
2016-11-10 16:18:55,599 [      MainThread][         utils][   ERROR] Could not find win32 encryption library C:\PGMkjell\pogom\../pokecrypt-pgoapi\encrypt32.dll
2016-11-10 16:18:55,601 [      MainThread][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "C:\PGMkjell\runserver.py", line 293, in <module>
    main()
  File "C:\PGMkjell\runserver.py", line 112, in main
    encryption_lib_path = get_encryption_lib_path(args)
  File "C:\PGMkjell\pogom\utils.py", line 478, in get_encryption_lib_path
    raise Exception(err)
Exception: Could not find win32 encryption library C:\PGMkjell\pogom\../pokecrypt-pgoapi\encrypt32.dll
```

**Comment by MyAdler** [comment]
@Bart274 You need to run "git submodule init" then "git submodule update". Or for a new installation you need to run a recursive pull.

**Comment by Bart274** [comment]
@MyAdler thanks that did the trick :)

**Comment by irus99** [comment]
Does anyone know how to resolve this? I have tried the steps above but no luck


2016-11-11 01:11:14,462 [      MainThread][         utils][   ERROR] Could not find linux2 encryption library /usr/src/1111update/pokemongo-map/pogom/../pokecrypt-pgoapi/libencrypt-centos-x86-64.so
2016-11-11 01:11:14,462 [      MainThread][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "runserver.py", line 293, in <module>
    main()
  File "runserver.py", line 112, in main
    encryption_lib_path = get_encryption_lib_path(args)
  File "/usr/src/1111update/pokemongo-map/pogom/utils.py", line 478, in get_encryption_lib_path
    raise Exception(err)
Exception: Could not find linux2 encryption library /usr/src/1111update/pokemongo-map/pogom/../pokecrypt-pgoapi/libencrypt-centos-x86-64.so

**Comment by Beri51** [comment]
@irus99 you miss the libraries in the folder.
The libraries for Centos are not available (afaik). Maybe you should try to compile yourself [following this](https://github.com/pokecrypt/pokecrypt-pgoapi/blob/master/howto_compile.txt) ?

**Comment by centos6user** [comment]
@irus99 @Beri51 I've created Centos libraries: [See PR](https://github.com/pokelibs/pgoapi-libs/pull/3)

**Pull request merged**
