### PR TITLE
added config variable so user can easily set map's title. 

### PR DESCRIPTION
**Pull request by jplusc**
## Description

Just a config.ini variable "maptitle" so the user can change the title and header of their map,
for example: "City of Jeannete Pokemon Go Map"  or "Joe's Team Map"
## Motivation and Context

was remaking the changes after each new update, I can't be the only one doing this, so added a variable instead.
## How Has This Been Tested?

Built the a new copy of the project from scratch and verified that it worked fine.  But it is just minor changes, so no real issue.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [ x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
     (new config value/switch)
- [x] I have updated the documentation accordingly. 
    (shown in example .INI file and in -h of runserver.py

### CODE REVIEW

**Comment by ChipWolf** [comment]
Kitchen sink.

**Comment by aldarund** [comment]
Morrrrrrre  paraaams. we neeeed morrrrre

**Comment by shadi1989** [comment]
having it in config.ini would be enough imo. shouldn't be used as a parameter cause is useless...

**Comment by FrostTheFox** [comment]
Pretty sure having it just in config.ini (or just as a argument) is against the ConfigArgParse design choice. Hence why it's Config Arg(ument) Parse.

**Comment by jplusc** [comment]
> having it in config.ini would be enough imo. shouldn't be used as a parameter cause is useless...

@shadi1989   I am fine with that... only added it as a parameter  as it seams like everything in config is also a parameter.

**Comment by beccasafan** [comment]
Closing/reopening to trigger Travis again - that's an odd build error.

**Comment by beccasafan** [comment]
Failed with an actual legit build error this time.

**Comment by jplusc** [comment]
thanks @beccasafan for checking that weird build error before which was hiding the actual error.   I did not run flake8 on my local copy, I just did and this minor change passes flake8 as well.

**Comment by tedtim** [comment]
doesn't change title on Full Stats page.

**Comment by jplusc** [comment]
> doesn't change title on Full Stats page.

@tedtim,  added the changes to the full stats page as well.  thanks.

**Comment by Slivo-fr** [comment]
I'm not using config file, I want a parameter :D

**Comment by DiscoTim** [comment]
I think its a good idea for many. 

the default is missing the accent on pokemon.

**Comment by jplusc** [comment]
> the default is missing the accent on pokemon.

@DiscoTim added, thanks.

**Comment by WalterMagnum** [comment]
I would say it's easier to edit the map template than deal with a PR.  Unless this gets merged it doesn't have much utility.

**Comment by Slivo-fr** [comment]
Is there anything to do there that is blocking merge ?

**Comment by Slivo-fr** [comment]
From discord @Seb

>@Slivo 1406 is missing a check for when the maptitle value is empty. And it's another CLI param/config value, so I suppose lots of people will have a word to say about killing kittens.
> 
> Otherwise, it's OK.
> 
> Also, in raw_data, get_args() is called twice. Not sure why that's necessary. (> this isn't because of the PR btw, just a side note)(édité)

**Comment by kevdotcom** [comment]
IMO it's harder to add a Pull Request to your local clone than to edit a simple html file...

Almost everyone knows a little html... Even people who I never thought they would

**Comment by onilton** [comment]
@jplusc Hi, do you still want to work on this? Otherwise can you close your pull request?

**Comment by sebastienvercammen** [comment]
We're cleaning up some old PRs that have been left around from before we had the time to handle everything properly. With the last few weeks going fantastically well, cleaning up the PR and issue queue will let us move forward again :) If this PR is still valid, don't hesitate to re-open and poke us.

**Pull request closed without merging**
