### PR TITLE
Solve Manual Captcha with ChromeDriver on Demand

### PR DESCRIPTION
**Pull request by ic4roswings**
Provides a way to solve captchas without 2captcha payed service 
## Description
After 2 consecutive 0/0/0 Returns checks the account in order to obtain the URL of the captcha if it exist opens a Chrome instance to solve the captcha It waits 30 sec or Until the captcha was solved to retrive the information

EDIT: CHROMEDRIVER IS REQUIRED, IN THE PYTHON SCRIPTS FOLDER

## Motivation and Context

Some people like myself can't make a payment in the 2captcha website
It solves https://github.com/PokemonGoMap/PokemonGo-Map/issues/1470

## How Has This Been Tested?

Running an instance waiting for the captcha to raise the script itself was tested with at least 50 captcha accounts that I Have 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by iluretar** [comment]
i think you should be using captcha_token as variable name instead of linea

**Comment by Arengo** [comment]
We all love Travis. . .. ...

**Comment by totoberg123** [comment]
I guess this is only for Windows?

**Comment by ic4roswings** [comment]
@iluretar yeah maybe once I get it to compile xD

**Comment by iluretar** [comment]
Maybe make it wait 60s instead of 30? pikaptcha do 60s and it doesn't seem to be too long

**Comment by ic4roswings** [comment]
@iluretar I only made it 30 cause if you are not on your desktop when the captcha prompts i'll pause your scanning for as long as the timeout goes, but maybe it can be modified to be an argument

**Comment by iluretar** [comment]
But it only pauses scanning for that worker which shouldn't be a problem, one cool thing would be a flag to first try manual and if that fails go for 2captcha, i'm at my desk most of the day and have pgm running in a side monitor so i can be resolving captchas without issue, but when i go out it would be awesome if it used 2captcha.

**Comment by ic4roswings** [comment]
@iluretar As far as I know all the process are paused waiting for the captcha response with 2captcha or manual

**Comment by iluretar** [comment]
Been running it for about 30min and solved around 10 captchas, all workers kept going while i solved them.

**Comment by ic4roswings** [comment]
are you sure ?? that sounds like multitasking to me

**Comment by iluretar** [comment]
captcha
Maybe i'm interpreting this wrong but it seems like the other workers keep going

**Comment by ic4roswings** [comment]
Yeah, you're right I haven't see that, is kind of wierd I don't understand how is it working that way, 1 Minute it is then

**Comment by iluretar** [comment]
i think that time should be the time that recaptcha url is valid to maximize efficiency, it that time known?

**Comment by gneissone** [comment]
@totoberg123 No, it's working fine for me on OS X. Maybe it's obvious, but to make this work you need to download [chromedriver](https://sites.google.com/a/chromium.org/chromedriver/) and put it somewhere in your PATH. Then make sure you're including the -cs or --captcha-solving flag when you start runserver.py.

**Comment by Bart274** [comment]
How far is this from being merged?

**Comment by springjools** [comment]
The problem with checking just consecutive 0 0 0 is that the order of the accounts are always the same. If you hex-scan an area which has, say water or a mountains, that area will likely have a valid 0 0 0 and since the accounts are always in the same order, the same account will always hit that area.

**Comment by Bart274** [comment]
@springjools that's not true, if you have for example step limit of 5, you have 61 areas. so each account will always scan the same area if your number of accounts is a multiple of 61, ohterwise they switch locations...

**Comment by springjools** [comment]
Ah yeah, that's true of course, how stupid of me. But if you get a bunch of errors and break before round 2, then this is still true.

**Comment by Bart274** [comment]
@ic4roswings I just tried your PR, I use it on a map that uses 2 accounts and both keep hitting 0/0/0 but I never get a captcha. Anything wrong?
http://pastebin.com/raw/5qujnkUz

**Comment by chowderchow** [comment]
@Bart274 Probably means that they're legitimate empty scans, not captcha'd accounts.

**Comment by Bart274** [comment]
No, I forgot to enable captcha solving in my config :p

**Comment by midadami** [comment]
What version of chromedriver should we use? With default one I get chromedriver not found. With last one chromedriver crashes.

**Comment by ic4roswings** [comment]
The latest one 2.25

**Comment by mdnpascual** [comment]
I cannot make this work with chromedriver 2.25 with PR #1367, #1476, and #1530 

I'm using [marbink's pogo captcha solver](https://github.com/marbink/PoGo-Captcha) and the chrome driver is fine. But when I use this one, chrome will open for a second and just closes.

**Comment by springjools** [comment]
I tried this and it works nicely. However, if you have many captchas, the older ones get hidden in the background. Would it be possible to randomise the position of the new window that appears so they don't all stack?

**Comment by mdnpascual** [comment]
Do you know what part of the code I need to edit to reduce timeout time of account if I fail to answer the captcha below the timeout? 2 hours seems to be excessive timeout if you fail to answer them atm

**Comment by simisbeat** [comment]
I'm new here, can someone tell me how to add this manual captcha solving to my po go map? thank you :)

**Comment by GubblGubbl** [comment]
Unfortunately the chromedriver is not available for the arm architectures like on Raspberry Pis.

**Comment by wobblybobz** [comment]
Working great, just wish there was a way that we could force the prompt for captcha request in case we miss the 60 second window from when it auto pops up. So we don't have to wait for the cool down timer to lapse or to force a restart of the server.

maybe a button on the status page that sends an ajax request to the server that starts the chromedriver stuff for that specific account?

**Comment by Bart274** [comment]
@ic4roswings I also like the suggestion @wobblybobz made: would it be possible to add a button on the status page so you can manually launch the captcha sequence again if you happen to miss the previous one so you can uncaptcha your accounts a lot sooner without having to wait for the cool off?

**Comment by PokeSearcher** [comment]
I'd suggest verifing chrome driver on startup rather than only when a captcha is requested. Its currently diffucult to test/diagnose issues (in my case an older unsupported chromedriver.exe).

Given that the test opens a window i suggest not doing it on search-only process, I changed my runserver.py locally to do:

`    if args.captcha_key is None:
        if not args.no_server:
            val_chrome = chrome_verifier()
            if not val_chrome:
                log.error('Using Chromedriver however its not installed.')
                sys.exit()
        log.info('Using Chromedriver captcha solving.')
    else:
        log.info('Using 2captcha captcha solving.')
`

**Comment by iluretar** [comment]
@ic4roswings can you rebase please?

**Pull request closed without merging**
