### PR TITLE
Added webhooks.md

### PR DESCRIPTION
**Pull request by ImAnOwl**
I added a article to the docs about webhooks

### CODE REVIEW

**Comment by adizam** [comment]
Discussing with a few others. My first response is that I believe this needs more information about webhooks in general. This shows how to create your OWN webhook in node.js. It doesn't explain how the project itself spits out data to a webhook (POSTs data).. how to configure it.. or how a project such as yours would suffice for an "inbetween" to kind of "map" data to an alternative shape.

**Comment by chuyskywalker** [comment]
@adizam is right, we can make this much better -- a structure like this would help users a lot:

```
# Webhooks with PokemonGo-Maps
## About webhooks; The What and Why
## Webhooks PokemonGo-Map Can Send
## Example Webhook Receiver Implementations
### Python
### Node
## PokemonGo-Map Webhook Compatible Projects
```

**Comment by ImAnOwl** [comment]
Thank you, Im going to edit this.

**Comment by jnovack** [comment]
I think a bad commit made it's way in here.

+2 for using NodeJS though in your examples.

**Comment by primaxius** [comment]
Declined - needs to be more detailed as specified by https://github.com/PokemonGoMap/PokemonGo-Map/pull/513#issuecomment-239348466

**Pull request closed without merging**
