### PR TITLE
add option to specify config file on command line or via env variable

### PR DESCRIPTION
**Pull request by Climbgunks**
## Description
add -cf --config  option to allow a config file to be specified...or use the environment variable POGOMAP_CONFIG

## Motivation and Context
allow multiple server configurations to be run via config files

## How Has This Been Tested?

Tested with various combinations of POGOMAP_CONFIG env variable settings and -cf command line settings.   Used both absolute and relative pathnames (relative to the current working directory)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X ] My change requires a change to the documentation.
- [X ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by aduljr** [comment]
Awesome, I've been thinking of adding this feature with my setup. Just no time to figure it out.

**Comment by primaxius** [comment]
Like the idea, just not how it's implemented.

**Comment by neutron666** [comment]
Would be nice, would allow to use a config file with just one place having the map files. Right now i have different folders for different areas because i don't want to set everything via cmdline.

**Comment by Climbgunks** [comment]
Made changes to documentation as suggested by  @primaxius

**Comment by FrostTheFox** [comment]
Nicely written docs. If @primaxius gives it the ok then I'll merge.

**Comment by Climbgunks** [comment]
@FrostTheFox   I just submitted a one character change.  I had used the wrong flag (-c) in the documentation instead of -cf.

**Comment by primaxius** [comment]
@Climbgunks you around?

**Comment by primaxius** [comment]
Closed - see https://github.com/PokemonGoMap/PokemonGo-Map/pull/1376
Rebased on my fork and applied changes to get this MERGED ASAP

**Comment by Climbgunks** [comment]
@primaxius around for a bit

**Comment by primaxius** [comment]
lol a little late hehehe

**Comment by Climbgunks** [comment]
no problems...   thx for all the work

**Pull request closed without merging**
