### PR TITLE
Replace Flask with Gevent

### PR DESCRIPTION
**Pull request by iwes**
Replace flask with gevent as the default web server

## Description

Implement [gevent](http://www.gevent.org/) server as default web server
~~Added config option to run flask server for development~~

## Motivation and Context

From Flask's [Documentation](http://flask.pocoo.org/docs/0.11/deploying/#deployment):
>While lightweight and easy to use, Flask’s built-in server is not suitable for production as it doesn’t scale well...

Specifically, when running flask and a connection fails, the thread will throw and leak memory.

After running a fairly busy server for less than a minute:

>Exception in thread Thread-159:
>Traceback (most recent call last):
>  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
>    self.run()
>  File "/usr/lib64/python2.7/threading.py", line 764, in run
>    self.__target(*self.__args, **self.__kwargs)
>  File "/usr/lib64/python2.7/SocketServer.py", line 596, in process_request_thread
>    self.handle_error(request, client_address)
>  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
>    self.finish_request(request, client_address)
>  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
>    self.RequestHandlerClass(request, client_address, self)
>  File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
>    self.finish()
>  File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
>    self.wfile.close()
>  File "/usr/lib64/python2.7/socket.py", line 279, in close
>    self.flush()
>  File "/usr/lib64/python2.7/socket.py", line 303, in flush
>    self._sock.sendall(view[write_offset:write_offset+buffer_size])
>error: [Errno 32] Broken pipe

This will continue until the user or system runs out of memory.

Related to #708, #773, #245 

## How Has This Been Tested?

Tested locally with HTTP/HTTPS to ensure feature-parity with Flask
Tested in ~~production~~ with real clients for 7+ days (no crashes, stable memory usage, running multiple server instances)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by BaIthamel** [comment]
But this map is designed for small use, not production. I'm not sure why we need this :P

**Comment by iwes** [comment]
Well ok, by production I mean me and my devices ;) But the crashing is real, even with only one (misbehaving) client.

**Comment by FrostTheFox** [comment]
How many instances are we talking? Because when you cross a certain line it becomes something we don't support.

**Comment by iwes** [comment]
2. 

The memory leak is the biggest problem I see with the built-in Flask server. I don't care if it throws exceptions on broken pipes, but once it starts leaking memory, it turns into a race condition until resources are exhausted.

**Comment by chuyskywalker** [comment]
While doing my work in #582 I ran into broken pipes _a lot_ and it was super frustrating.

I would actually ask why we'd keep direct flask running at all? Why not just always use gevent as the wrapper?

**Comment by iwes** [comment]
I'm not sure if there's some "development" mode benefit to doing it (when building API calls etc). The flask server only runs now when `--debug-flask` is called. 

If there's no benefit to having flask around, I can remove it entirely.

**Comment by chuyskywalker** [comment]
That's what I was asking -- I have no idea why we'd keep flask as directly invoked at all. I'm somewhat new to the python ecosystem, so I don't know the pros/cons of this situation.

**Comment by chuyskywalker** [comment]
I pulled this branch, and ran some tests comparing it to flask stand alone with:

```
ab -n 9999999 -t 15 -c 64 http://192.168.52.9/loc
```

Flask:
```
Complete requests:      2852
Failed requests:        0
Total transferred:      550777 bytes
HTML transferred:       128340 bytes
Requests per second:    190.10 [#/sec] (mean)
Time per request:       336.665 [ms] (mean)
Time per request:       5.260 [ms] (mean, across all concurrent requests)
Transfer rate:          35.85 [Kbytes/sec] received
```

gevent:
```
Complete requests:      4128
Failed requests:        0
Total transferred:      710016 bytes
HTML transferred:       185760 bytes
Requests per second:    275.17 [#/sec] (mean)
Time per request:       232.581 [ms] (mean)
Time per request:       3.634 [ms] (mean, across all concurrent requests)
Transfer rate:          46.22 [Kbytes/sec] received
```

So, clearly, quite a bit faster. That said, serving TONS of requests really isn't in our "who cares" book. What does matter is that the benchmark made flask dump out broken pipes quite a few times, meanwhile gevent never hiccuped at all.

This is a bit in the weeds though, since even when flask `broken pipes` a thread, it doesn't really break the app.

**Comment by chuyskywalker** [comment]
I also added

```
from gevent import monkey; monkey.patch_all()
```

At the top of runserver.py since apparently [you should do that to really take full advantage](http://www.gevent.org/intro.html#monkey-patching). But I didn't really notice it make much of a difference. Perhaps if I were sending off a lot of webhooks it would.

**Comment by hemsleyk** [comment]
Will this play nice with HAProxy?

**Comment by Spacehug** [comment]
I would love to see broken pipes gone, honestly

**Comment by Infernoman** [comment]
Would love to see this implemented as well

**Comment by iwes** [comment]
@chuyskywalker Added

@hemsleyk It should play fine (or better). I'm running mine behind squid reverse proxy.

**Comment by Toetje585** [comment]
I tried it by myself (merged this to the latest dev build) however my log gets spammed with this:

RuntimeError: reentrant call inside <_io.BufferedReader name=8>
2016-08-20 19:59:35,134 [  DummyThread-96][           app][   ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michel/Bureaublad/PokemonGo-Map/pogom/app.py", line 90, in raw_data
    d['pokemons'] = Pokemon.get_active(swLat, swLng, neLat, neLng)
  File "/home/michel/Bureaublad/PokemonGo-Map/pogom/models.py", line 103, in get_active
    for p in query:
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/shortcuts.py", line 203, in execute_sql
    sql, params, require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3499, in commit
    self.get_conn().commit()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 769, in commit
    self._read_ok_packet()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 748, in _read_ok_packet
    pkt = self._read_packet()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 963, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 990, in _read_bytes
    data = self._rfile.read(num_bytes)

Not sure where it's coming from perhaps someone has an idea?

**Comment by Toetje585** [comment]
I reverted this code, and the errors disappear. If you start with a clean database it just takes a while for the error to show up.  And starts to flood it.

I used: nohup python runserver.py -os -fl -l 'xxxx, xxx' &

All good until now, then i start:

sleep 0.5; nohup python runserver.py -ns -ss test1.json -ng -nk -sd 15 -wh http://127.0.0.1:4000 -l 'xxxxx, xxxx' -a dddd -p 'xxx' &

All seems fine first 15 seconds, until the errors start to flood.

**Comment by iwes** [comment]
@Toetje585 1) what version of python + mysql are you using? 2) Try disabling monkey patch (runserver.py line 21 and 32)?

**Comment by iwes** [comment]
Disregard. I was able to reproduce. It seems the monkey patching is causing it. I'll remove that.

**Comment by Eskof** [comment]
Hello and thanks, seems like web is faster. But mysql seems still really slow, any hint? thanks

**Comment by Kasmodan1** [comment]
When Monkey Patching was Imported was Threading set to true? or false? At that time? I just find it weird that Monkey Patching became garbage.

**Comment by iwes** [comment]
There were multiple threads. Monkey patching messes with sockets.. and seems to cause a problem with peewee's mysql client. Doesn't happen on sqlite, since sqlite doesn't use any sockets.

**Comment by TachyonRSA** [comment]
Working brilliantly!

**Comment by izanagi1995** [comment]
Too many open files? Any idea?

**Comment by Infernoman** [comment]
Balthamel - Today at 5:23 PM
i don't like it, either we should migrate
Balthamel - Today at 5:23 PM
or not

Remove the flask server completely and recommit. Your more likely to get merged.

**Comment by BaIthamel** [comment]
>.> nice one @Infernoman grass me out xD

**Comment by Infernoman** [comment]
LOL my bad but its true. and everyone agreed with you :P

**Comment by iwes** [comment]
¯\_(ツ)_/¯

**Comment by Infernoman** [comment]
just the merge conflicts now then ill try and push someone to get this merged as its pretty important. and resolves a memory leak from flask

**Comment by iwes** [comment]
whoops. how2git. fixing.

**Comment by Infernoman** [comment]
hehe did the same as me :D im not too familiar on how to rebase properly either lol. maybe best to make another PR and close this one out?

**Comment by iwes** [comment]
fixed

**Comment by Infernoman** [comment]
GJ dude lol im not that good yet :p

**Comment by iwes** [comment]
`git reset` is your friend

**Comment by jhaprins** [comment]
A few days ago I patched my servers with this patch and it is really good. I had to restart all server processes behind haproxy every hour because of the memory / socket leak. Now it has been running without problems for several days and it is much faster. Thanks for the patch and please intergrate this as soon as possible.

**Comment by TachyonRSA** [comment]
Don't see why this hasn't been merged yet. Been working perfectly for me for quite a few days. Glad the memory leak is gone, constant restarting of the server got annoying.

**Comment by Eskof** [comment]
Hello, since I swapped to SSL, I have some weird random issue, which crashy the server :(

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 126, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 691, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 271, in __init__
    raise x
SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
<Greenlet at 0x6feb392b3870: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x6feb392cf7d0 fileno=[Errno 9] Bad fi)> failed with SSLError
`

**Comment by v3ss0n** [comment]
beware. Monkey patching will case a lot of problems that is very very hard to debug (c-level). We avoid gevent in production.
Best is to use asyncio or Tornado.

**Pull request merged**
