### PR TITLE
Fix direction for non english languages

### PR DESCRIPTION
**Pull request by Slivo-fr**
Make the gmap link work for non english languages

## Description
Force EN language on link to allow 'current location' to be recognized

## Motivation and Context
Non english speakers cannot use the get direction link

## How Has This Been Tested?
localy tested 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Teelve** [comment]
go to "PokemonGo-Map-develop\static\js\map.js" and look for every "Current+Location", and just replace it with the good language (I'm french, so i replaced it with "Ma+Position")

**Comment by Slivo-fr** [comment]
Indeed, but I'd rather provide a permanent working solution for any user :)

**Comment by Plop** [comment]
Yes please.
Another solution could be that it just indicates the marker on the map, but doesn't launch the direction.

**Comment by Slivo-fr** [comment]
Indeed, I just took the old PR code without thinking about it.

**Comment by Slivo-fr** [comment]
Does not work for the gmap app, only in browser. 
There is two solutions left:
- Translate "your location" in every supported language
- As plop suggested, just link to the place and let the user launch the direction

**Pull request merged**
