### PR TITLE
Only sleep after n consecutive fails, not overall EDIT: also fixed fail statistic being cleared on success

### PR DESCRIPTION
**Pull request by Mr-Groch**
## Description
Changed sleeping 2 hours after max overall thread fail count to just max_fails of concecutive fails.
EDIT:
Also 	fixed status['fail'] statistic being cleared on success

## Motivation and Context
When server is running for long period of time, some failed searches will appear, and with 20000 successed and 5 failed it doesn't mean that account was banned. Changed this check to consecutive failures, not overall.

## How Has This Been Tested?
Locally

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
(I have used new variable, no new var in 'status', because I think that this isn't needed for global needs)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by justsomedudeonthenet** [comment]
That is an issue that definitely needs fixing!

But why not just reset fails to 0 when there is a success?

**Comment by Mr-Groch** [comment]
I think that total fails should stay for statistics. It is good to keep overall success, fails, empyts, etc.

**Comment by aldarund** [comment]
Runs fine for me for a day. Without it was getting 2h timeouts for workers after a day of work or so, while they wasnt banned for sure. With this no timeouts so far ( and no bans but its unrelated) because invalid response are happening pretty rare.

**Comment by beccasafan** [comment]
Aha! Have definitely been hitting this and was confused.

**Comment by jorgebsa** [comment]
👍

**Comment by filippounitn** [comment]
sorry for the noob question. How do I download this new search.py file?
This is a huge issue i want to resolve asap and I think you are my saviour ;)

**Comment by Mr-Groch** [comment]
@filippounitn 

git remote add Mr-Groch https://github.com/Mr-Groch/PokemonGo-Map.git
git fetch Mr-Groch consecutive_fails
git merge Mr-Groch/consecutive_fails

**Comment by justsomedudeonthenet** [comment]
This should definitely be merged.

**Pull request merged**
