### PR TITLE
More flexibility with spawnpoint import file

### PR DESCRIPTION
**Pull request by khag7**
## Description
Allow the spawnpoint import file to be a CSV. Allow it to not include lat & lng. Allow the provided filename to be a relative path.

## Motivation and Context
Data portability is useful. Some users have a much easier time dumping some database columns, editing in excel, and saving as CSV. This change will allow those users to skip the step of converting their data to json. Furthermore, we don't need users to provide their lat & lng with each spawnpoint. The spawnpoint_id already encodes that information. We just need spawnpoint_id and time (seconds past the top of the hour). Two columns. That's it!

## How Has This Been Tested?
JSON imports still work. CSV imports work. Tested with both JSON and CSV files of 55,000 spawnpoints in length. About 5 seconds is added to startup for a file this size to convert spawnpoints (no lat & lng provided) to lat & lng.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by justsomedudeonthenet** [comment]
This appears to ignore lat and lng even if provided in the file?

That is unacceptable.

My spawns.json has no spawnpoint IDs, just lat/lng.  People using any of the spawnpoint compression or optimization features of other PRs and tools will have the same issue - we are scanning a specific point, not necessarily a spawnpoint.

I don't particularly see the need for this.  Converting a csv to json is very easy.  But as long as it is not breaking anything else it would be ok.

**Comment by khag7** [comment]
You are correct. And I wasn't sure how that might play. I guess the smarter call here would be to check if lat & lng provided, if not, get that from spawnpoint ID.

My end goal here is to improve data portability. Immagine someone new decides they want to run a scanner, they download our software. Do they really want to do beehive scans for 2 days to collect a large volume of spawnpoints in their area before they can get into spawnpoint scanning? No! Of course not. They want to go to pokemonspawnpoints.com and say "i want all points within 10 miles of my home address and 5 miles of my work address". Boom! They get a flat file with 60 thousand spawnpoints and what time those points should be checked. No need to waste bandwidth with lat and lng if that data is already in the spawnpoint_id. But more importantly is that excel can manipulate CSV and not JSON. I've helped about a dozen friends locally get this up and running. Some of the most challenging things has been sharing spawnpoint data between us because some people used different mapping programs initially. You know what every database software supports well? **Export to CSV.**


I didn't take spawnpoint compression into consideration. Thanks for the advice, I'll figure it out.

**Comment by justsomedudeonthenet** [comment]
Oh I do understand why people want to work with csv files.

But wouldn't it be simpler (and easier to maintain) if you just had a csv_to_json.py script in /Tools?

Do whatever data manipulation you need as csv, then run the script to spit out a spawns.json file.

**Comment by justsomedudeonthenet** [comment]
Ideally, such a script would accept a file with a mixture of spawnpoint id, lat/lng, and both provided.  Use the lat/lng if it is there (to allow for scanning outside the exact spawnpoint for compression) and calculate it if it is not provided.

Even better, make it able to convert json to csv as well - so you can take your json file and edit it in excel again.

**Comment by primaxius** [comment]
Fails and WIP

**Pull request closed without merging**
