### PR TITLE
readded example.py

### PR DESCRIPTION
**Pull request by FrostTheFox**
## Description

Readded example.py
## Motivation and Context

https://github.com/PokemonGoMap/PokemonGo-Map/issues/182

https://github.com/PokemonGoMap/PokemonGo-Map/issues/182
## How Has This Been Tested?

bang lure pls

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [no] My code follows the code style of this project.
- [no] My change requires a change to the documentation.
- [no] I have updated the documentation accordingly.

for old time sake, thank @JZ6 for the code

### CODE REVIEW

**Comment by clbuttic** [comment]
+1 Tested, working as expected.

**Comment by FrostTheFox** [comment]
yey

**Comment by razorasadsid** [comment]
not working can't find unknown6, tbh this project is scrapped

**Comment by JZ6** [comment]
glad you kept it all this time @FrostTheFox for old times sake

**Pull request merged**
