### PR TITLE
Update schedulers.py (self.step_distance = 0.900 to self.step_distance = 0.500)

### PR DESCRIPTION
**Pull request by h0us3cat**
## Description

if self.args.no_pokemon:
            self.step_distance = 0.900

to

if self.args.no_pokemon:
            self.step_distance = 0.500
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by cydine** [comment]
There are a few other instances in the code where this change is needed too. Another in schedulers.py, in models.py and in scan.py.

**Comment by bbdoc** [comment]
Agree with @cydine... Changing only this value can results in lots of issues. I tried it and the reverted as my beehive was not calculated correctly anymore, had lots of holes between the different hives. All references need to be changed.

**Comment by Obihoernchen** [comment]
That's bad and by far not complete. Why not adding radius to https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/pogom/search.py#L789 ?

**Comment by sebastienvercammen** [comment]
This PR missed other old references to the distances. We have a more complete PR ready on a private fork but can't publicize/merge yet because the changes are tied to other upcoming PRs that change behavior.

**Pull request closed without merging**
