### PR TITLE
Introducing single-user: search mode (aka Scheduler) and step limit via frontend + speed limit

### PR DESCRIPTION
**Pull request by Mr-Groch**
## Description
Ability to change search mode (scheduler) and step limit in runtime via web page. This is mainly inherited from PR #737 and #37 - I have not closed that PR's, because mybe contributors decide to use those independent. Difference is that visibility of search mode select box and step limit input field depends here on -su param.

Also added speed limit to avoid teleports on spawnpoint only search and location change

## Motivation and Context

The same as PR #737 and #37

## How Has This Been Tested?

The same as PR #737 and #37 

## Screenshots (if appropriate):
search_mode

img_20160910_213354

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by aldarund** [comment]
But that would mean that any use who use the map would be able to change it. Not really good

**Comment by Mr-Groch** [comment]
@aldarund It can be disabled. If someone use fixed location - it will not show. Also adding -nsm parameter will disable just this select box

**Comment by aldarund** [comment]
Why its enabled by default then and need switch to be disabled instead of switch to be enabled?

**Comment by 4RK4N** [comment]
u could rework this to integrate into the alrdy password protecred /status page. and with some more PR's like this one it could be a fully featured admin frontend :D

**Comment by Mr-Groch** [comment]
@aldarund For the same reason search (pause) switch is enabled for default. I think that main purporse of this map is individual use, but if contributors wants to disable this by default, I will make it disabled. Waiting for more feedback :)

**Comment by jaquer** [comment]
I'm really loving your work @Mr-Groch, but @aldarund has a good point. I would switch the logic around and enable the feature only if `search-mode-control` argument is true. I know I'm not a contributor, but this is a core functionality change.

**Comment by SlasherKG** [comment]
This and the step control in the web gui will be awesome! 
It's a pain to have to RDP to my PC every time I need to change steps and type of scan.

I hope these get merged!

**Comment by Mr-Groch** [comment]
OK, I have disabled it by default. Added -su arg (--single-user-control) to enable search mode select box and step limit input field. I wish to use that arg also for current other search controlls like search pause, search location following user - what do you think?

**Comment by Spiritvn** [comment]
I think you should move this to the Search Mode and Search Step Limit to Status Page which requires password, it should be for backend than frontend. 

I would like to have the speed limit merge, combine its with on demand mode here: https://github.com/PokemonGoMap/PokemonGo-Map/pull/1271 i can have some seperated workers to scan follow my friends location and lower down the BAN chances

**Comment by Mr-Groch** [comment]
@Spiritvn It is now not enabled by the default. You must specify -su paramter to enable this. I want also cover search pause switch and search follows user location switch with -su parameter, but need more feedback about that.

**Comment by Spiritvn** [comment]
I know it's disabled by default, but i agreed with @4RK4N , if you enable it, it's still on the place where other users could change it and affect to the others. The map page should be related to "FrontEnd" than that's backend function, status page is more for backend so it's better structure, it's my personal opinion though.

Really love to have speed limit goes with scan follow me :)

**Comment by Mr-Groch** [comment]
Param full name is --singe-user-control (su like superuser ;) ) and my idea is that only users who want to have this kind of control will enable it. I'm sure there is many people that use this individually. And that why I want also to pull search pause control and search follow user into this new mode. This PR is not to add admin controls behind password protected control panel - just to make lot of users life easier :) 

Admin backend is also good idea, but I would like to see it as seperate PR.

**Comment by Mr-Groch** [comment]
Like the commit message says, I have removed -nsc arg, make search control part of single-user mode (-su). One parameter less ;) After some thinking - I will leave location changing as is - fixed location enabled/disabled is better place to handle that.

**Comment by primaxius** [comment]
Not everything needs to be in the frontend.

**Comment by Mr-Groch** [comment]
@primaxius This is optional feature - only those ho wants this will enable it, so why closed?

**Comment by CalcMan** [comment]
Reopen please, these features are very useful for single user maps, and they are designed to be on only when requested, why not let folks use what they want?

**Comment by SenSachen** [comment]
I too would enable this optional feature if it were implemented.

**Pull request closed without merging**
