### PR TITLE
New fort (gym, pokestop) icons

### PR DESCRIPTION
**Pull request by cristofercruz**
Designed some new gym and pokestop icons based on in game UI and top down perspective. Also added scaling of fort icons using the same icon size setting already in place same as pokemon markers.

## Motivation and Context
Better quality images
Easier to tell where the fort center is
Icon perspective matches map perspective

## How Has This Been Tested?
Tested locally seems to work ok

## Screenshots (if appropriate):
before
after

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by palmercm** [comment]
I like this change. The old icons take up a lot of real estate and don't make it clear where exactly things are located.

**Comment by Viper2k4** [comment]
I like the new pokestop-icons, even more readable. But i'm not very in love with the gym icons, hard to find the gym's inside the pokestops with a quick look.

Old gyms with new pokestop-icons would look sweet :)

**Comment by cristofercruz** [comment]
Made some light adjustments: increased the yellow intensity on the instinct gyms. Increased outline and shadow visibility on gyms.

**Comment by HypeZ85** [comment]
New icons have less contrast than the older. 
New gyms are less eye-catching (specially the yellow one). 
Lure is also less eye-catching. 

I never contribuited to this project so my opinion have little importance here, but i personally prefer the old icons. For older gym, its true that they are big, but you can always clearly see them in a bat of the eye and you can always disable gyms display if you have no interest in them

**Comment by cristofercruz** [comment]
adjusted images again to make gyms and lured stops more visible

**Comment by kevdotcom** [comment]
Your gym markers are way off center 
image

**Comment by kevdotcom** [comment]
Same with Pokestop Markers
image

**Comment by cristofercruz** [comment]
@kevdotcom you might need to run grunt build

**Comment by kevdotcom** [comment]
That just made the icons smaller :/

**Comment by kevdotcom** [comment]
Thank you :) I tend to forget stuff

**Comment by primaxius** [comment]
I'm just gonna decline this. There is so much love for the current icons. If you want custom ones just replace the ones in **PokemonGo-Map/static/forts/**

**Pull request closed without merging**
