### PR TITLE
added flake8 linting file and applied linting rules

### PR DESCRIPTION
**Pull request by Chlodochar**
## Description

This adds a flake8 configuration file for linting the project. I also solved the issues that flake8 mentioned on the current code.

I have ignored "Line-too-long" issues, because there were a bunch of those and would result in multiple changed lines (harder to see whether it is actually still correct in the diff).

## Motivation and Context

This is partly to move from Landscape to anything else. It annoys me that it is so flaky. At least we're now able to use the command-line to run flake8, but it also opens the doors for other services like SizeCI.
## How Has This Been Tested?

Ran the crawler.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by chuyskywalker** [comment]
> C'mon Landscape, gimme some sweet sweet score increase.
> EDIT: Ugh, Landscape is stuck again.

Sums up this pr nicely, lol

**Comment by chuyskywalker** [comment]
So the idea, roughly, would be to include flake8 and run it as part of, say, travis-ci (et. all) instead?

**Comment by Chlodochar** [comment]
@chuyskywalker stage 2 isn't clear yet. However, whatever we will do, we will want to run linting locally as well. Flake8 seems to be the standard for Python, so this is a first step towards deprecating Landscape.

Landscape currently has its own settings for flake8, so it's not trivial to match those settings using commandline.

I would like to try SideCI next. It seems a bit spammy if there already were issues in the code before a PR, but it comments the problems inline in the PR, which seems helpful. Once this PR is merged, there shouldn't be any flake8 issues anymore, so SideCI *could* be used.

**Comment by invisiblek** [comment]
bump. shipit?

**Comment by chuyskywalker** [comment]
Done'zo

**Pull request merged**
