### PR TITLE
return current loc even when setting new loc

### PR DESCRIPTION
**Pull request by ilendemli**
## Description
Returns the currently saved location after setting new location instead of a meaningless "ok" text.

## Motivation and Context
Mobile clients can use the same datamodel of loc/ for next_loc/ to map the result.

## How Has This Been Tested?
updated next_loc(self) in app.py to call and return the result of loc(self)
made sure it does not break the feature and ergo the webinterface

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by chuyskywalker** [comment]
LGTM

**Comment by ilendemli** [comment]
@chuparCh0pper Would appreciate it, if this could be merged soon.

**Comment by chuparCh0pper** [comment]
I think @ilendemli ment you @chuyskywalker

**Comment by ilendemli** [comment]
ah yes @chuparCh0pper, sorry for that!

**Pull request merged**
