### PR TITLE
Fix installation documentation on OSX El Capitan

### PR DESCRIPTION
**Pull request by Th3Mouk**
Fix of the install documentation for OSX El Capitan.

## Motivation and Context
The six package is already installed and can't be overwritten due to the system protection.
https://github.com/pypa/pip/issues/3165

## How Has This Been Tested?
On my OSX El Capitan

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by chuyskywalker** [comment]
Can you try the changes in #327 to see if that works better?

**Comment by woest85** [comment]
@chuyskywalker I don't think the stuff in #327 is going to work for OSX El Capitan.

**Comment by Th3Mouk** [comment]
This doesn't work effectively

**Comment by Th3Mouk** [comment]
@chuyskywalker any news on this bug ?

**Comment by rbryson74** [comment]
This is fixed now in MacOS sierra and/or using the ```virtualenv``` package in pip

**Pull request closed without merging**
