### PR TITLE
Updated doc with command line arguments

### PR DESCRIPTION
**Pull request by chypriote**
## Description
This is the help section from the original repo, that is not yet in the new doc. 

## Motivation and Context
The --help command doesn't display a lot of informations, this is more thorough.

## How Has This Been Tested?
Docs built locally

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by chuyskywalker** [comment]
I actually took this one our on purpose. My reasoning is that `-h` exists and will always be up-to-date. Keeping these in sync is, well, a time sink.

**Comment by chypriote** [comment]
This is the message shown by -h:

> usage: runserver.py [-h] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
>                     [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY]
>                     [-ld LOGIN_DELAY] [-dc] [-H HOST] [-P PORT] [-L LOCALE]
>                     [-c] [-d] [-m] [-ns] [-os] [-nsc] [-fl] -k GMAPS_KEY [-C]
>                     [-D DB] [-cd] [-np] [-ng] [-nk] [--db-type DB_TYPE]
>                     [--db-name DB_NAME] [--db-user DB_USER]
>                     [--db-pass DB_PASS] [--db-host DB_HOST]
>                     [--db-max_connections DB_MAX_CONNECTIONS]
>                     [-wh [WEBHOOKS [WEBHOOKS ...]]]

In my experience, it's not obvious what [-c] [-d] [-m] [-ns] [-os] [-nsc] [-fl] etc doest from reading it

**Comment by anvilo** [comment]
There are short descriptions for each under the wiki tab.
Link here: https://github.com/PokemonGoMap/PokemonGo-Map/wiki/Command-Line-Arguments

**Comment by chypriote** [comment]
Oh my bad, didn't see it. Since the wiki homepage redirects to the docs, thought the wiki was empty

**Comment by chuyskywalker** [comment]
No, THIS is what the help output looks like:

```
# python runserver.py -h
usage: runserver.py [-h] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY]
                    [-ld LOGIN_DELAY] [-lr LOGIN_RETRIES] [-sr SCAN_RETRIES]
                    [-dc] [-H HOST] [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns]
                    [-os] [-nsc] [-fl] -k GMAPS_KEY [-C] [-D DB] [-cd] [-np]
                    [-ng] [-nk] [-pd PURGE_DATA] [--db-type DB_TYPE]
                    [--db-name DB_NAME] [--db-user DB_USER]
                    [--db-pass DB_PASS] [--db-host DB_HOST]
                    [--db-port DB_PORT]
                    [--db-max_connections DB_MAX_CONNECTIONS]
                    [-wh [WEBHOOKS [WEBHOOKS ...]]]

Args that start with '--' (eg. -a) can also be set in a config file
(/usr/src/app/pogom/../config/config.ini or ). The recognized syntax for
setting (key, value) pairs is based on the INI and YAML formats (e.g.
key=value or foo=TRUE). For full documentation of the differences from the
standards please refer to the ConfigArgParse documentation. If an arg is
specified in more than one place, then commandline values override config file
values which override defaults.

optional arguments:
  -h, --help            show this help message and exit
  -a AUTH_SERVICE, --auth-service AUTH_SERVICE
                        Auth Services, either one for all accounts or one per
                        account. ptc or google. Defaults all to ptc.
  -u USERNAME, --username USERNAME
                        Usernames, one per account.
  -p PASSWORD, --password PASSWORD
                        Passwords, either single one for all accounts or one
                        per account.
  -l LOCATION, --location LOCATION
                        Location, can be an address or coordinates
  -st STEP_LIMIT, --step-limit STEP_LIMIT
                        Steps
  -sd SCAN_DELAY, --scan-delay SCAN_DELAY
                        Time delay between requests in scan threads
  -ld LOGIN_DELAY, --login-delay LOGIN_DELAY
                        Time delay between each login attempt
  -lr LOGIN_RETRIES, --login-retries LOGIN_RETRIES
                        Number of logins attempts before refreshing a thread
  -sr SCAN_RETRIES, --scan-retries SCAN_RETRIES
                        Number of retries for a given scan cell
  -dc, --display-in-console
                        Display Found Pokemon in Console
  -H HOST, --host HOST  Set web server listening host
  -P PORT, --port PORT  Set web server listening port
  -L LOCALE, --locale LOCALE
                        Locale for Pokemon names (default: en, check
                        static/dist/locales for more)
  -c, --china           Coordinates transformer for China
  -d, --debug           Debug Mode
  -m, --mock            Mock mode. Starts the web server but not the
                        background thread.
  -ns, --no-server      No-Server Mode. Starts the searcher but not the
                        Webserver.
  -os, --only-server    Server-Only Mode. Starts only the Webserver without
                        the searcher.
  -nsc, --no-search-control
                        Disables search control
  -fl, --fixed-location
                        Hides the search bar for use in shared maps.
  -k GMAPS_KEY, --gmaps-key GMAPS_KEY
                        Google Maps Javascript API Key
  -C, --cors            Enable CORS on web server
  -D DB, --db DB        Database filename
  -cd, --clear-db       Deletes the existing database before starting the
                        Webserver.
  -np, --no-pokemon     Disables Pokemon from the map (including parsing them
                        into local db)
  -ng, --no-gyms        Disables Gyms from the map (including parsing them
                        into local db)
  -nk, --no-pokestops   Disables PokeStops from the map (including parsing
                        them into local db)
  -pd PURGE_DATA, --purge-data PURGE_DATA
                        Clear pokemon from database this many hours after they
                        disappear (0 to disable)
  --db-type DB_TYPE     Type of database to be used (default: sqlite)
  --db-name DB_NAME     Name of the database to be used
  --db-user DB_USER     Username for the database
  --db-pass DB_PASS     Password for the database
  --db-host DB_HOST     IP or hostname for the database
  --db-port DB_PORT     Port for the database
  --db-max_connections DB_MAX_CONNECTIONS
                        Max connections (per thread) for the database
  -wh [WEBHOOKS [WEBHOOKS ...]], --webhook [WEBHOOKS [WEBHOOKS ...]]
                        Define URL(s) to POST webhook information to
```

**Comment by chypriote** [comment]
Okay, not sure what happened, I remember getting only the first part of the output, but testing it again I get the correct one.
Guess this can be closed then.

**Comment by chuyskywalker** [comment]
Thanks, I do appreciate contributions to the wiki though. So if you find anything else, feel free to ask.

**Pull request closed without merging**
