### PR TITLE
Add scan-here button

### PR DESCRIPTION
**Pull request by Samael27**
## Description
Adds a "scan here" Floating Action Button at bottom center of the map. When clicked/touched, will set the current map center as new search location.

## Motivation and Context
When outside hunting Pokemon you often want to check a few nearby places before deciding which way to go. This is way more convenient when you can just move the map one or two kilometers/miles and tap "scan here" instead of having to type in the name of some location.

## How Has This Been Tested?
Tested using docker.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

THis is the updated #16 PR including the last changes.

### CODE REVIEW

**Comment by djgreg13** [comment]
duplicate of #16 ?

**Comment by Samael27** [comment]
Yes but up to date (the other one couldn't be merge anymore).

**Comment by Samael27** [comment]
Why the checks had failed ? For me everything is fine, did I miss something ?

**Comment by Badiboy** [comment]
See build details (link "Details").

/home/travis/build/PokemonGoMap/PokemonGo-Map/static/js/map.js
  954:1  error  Trailing spaces not allowed  no-trailing-spaces

**Comment by Samael27** [comment]
Yes found it thanks. New check in progress :)

**Comment by Slivo-fr** [comment]
You commited the process.pid :P

**Comment by Samael27** [comment]
File deleted ;)

**Comment by djgreg13** [comment]
strange, i merged #16 yesterday in my working copy,
differences with or i can keep #16 ?

**Comment by Samael27** [comment]
With this repo up to date I can't, that's why I recreate it. No there is no differences, if the #16 works fine for you keep it.

**Comment by Slivo-fr** [comment]
I'm also unable to apply diff of #16 on up-to-date dev branch

**Comment by Mr-Groch** [comment]
I have merged #16 succesfully some time ago and using it for a few weeks - no problems with pulling latest commits

**Comment by jaquer** [comment]
Yeah, #16 still applies cleanly (look at the bottom of the PR for confirmation from Github itself: "This branch has no conflicts with the base branch"). Maybe you've applied other, conflicting changes on your tree?

I'm glad this new PR is bringing attention to it though, and I will plug #1121, where I suggest people :+1:  to show their support.

**Comment by Samael27** [comment]
New pull request comming (impossible to keep this one up to date).

**Pull request closed without merging**
