### PR TITLE
Improved status counters

### PR DESCRIPTION
**Pull request by mew905**
## Description
Adds a total captcha counter to the workers, plus a whole line dedicated to totals of all workers and hourly stats (and even captcha costs per hour and per month)

## Motivation and Context
Researching captcha methodology
Cost control

## How Has This Been Tested?
my map

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by monkeymalle** [comment]
Hi @mew905 
Nice PR. I was trying it out, but you missed a small change in your commit to show the message. I needed to change:
`# How pretty.
 status = '{:10} | {:5} | {:' + str(userlen) + '} | {:' + str(proxylen) + '} | {:7} | {:6} | {:5} | {:7} | {:10}'`
to:
`            # How pretty.
            status = '{:10} | {:5} | {:' + str(userlen) + '} | {:' + str(proxylen) + '} | {:7} | {:6} | {:5} | {:7} | {:7} | {:10}'`

**Comment by mew905** [comment]
@monkeymalle good call, forgot about that!

**Comment by mew905** [comment]
Also I cant seem to get -ps working with a real worker count. I suppose I could just use args.workers. Right now it shows the number of lines on your screen + 1

**Comment by m3g4mInD** [comment]
Well i have a problem with this pr, after git fetch origin pull/1587/head:PR#-statuscounters
git checkout PR#-statuscounters
npm install
npm install build

in console touch F is ok  -> http://prntscr.com/dcdqtb
but touch ENTER not ok ->  http://prntscr.com/dcdrb1

PR 1530 work fine.

**Comment by mew905** [comment]
there's gotta be more to it, I literally did the same earlier today and it works perfectly on mine. as far as I remember there's 2 places in the code where it does a sort: get_spawnpoints_in_hex in models.py, and in the worker status thread in search.py

**Comment by m3g4mInD** [comment]
Well is weird,but i gonna make a new install maybe i have some have some conflits i dont know :)

**Comment by midadami** [comment]
I get the same error as @m3g4mInD. The writing on the database doesn't work so you still get webhooks but no pokemon show on map since they load from db.

**Comment by SkOODaT** [comment]
works great for me only issue i see is if i am on page 1 or page 2 and thiers more pages i need to go to the last page for it to compile all the info correctly, if i am on page 1 it will only summerize page 1 not all the workers

**Comment by gabaod** [comment]
I think it also has to do with the window size.. as if you make the window very short in height, it will only show totals of what it can see above it. So if you dont see all the workers it only displays totals of the workers you can visually see in the window.

**Comment by mew905** [comment]
I tried placing the counters outside the if statement but it seems to break
the ps. If someone else has any ideas or solutions im very anxious to hear
it

**Comment by onilton** [comment]
@mew905 Hi, since https://github.com/PokemonGoMap/PokemonGo-Map/pull/1604  got merged, can you confirm that the changes proposed by this PR are in develop now?

If you can confirm, can you close it? :smile:

**Comment by mew905** [comment]
yup, I checked out the code of 1604 and it looks good :)

**Pull request closed without merging**
