### PR TITLE
Add gym-details sidebar

### PR DESCRIPTION
**Pull request by maddhatter**
## Description
Add a "View Details" link to the gym popup that opens a sidebar (same as stats sidebar) to display detailed information about the Pokemon in the gym.

## Motivation and Context
The information being displayed in the sidebar has been captured since #666, but was not displayed on the front-end.

## How Has This Been Tested?
SQLite backend + Firefox/Chrome on Windows 10

## Screenshots (if appropriate):

Clicking the Pokemon in the sidebar shows IVs and moves:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by equatebrand** [comment]
static/js/map.js line 1259 seems like it should be: 
<b class="team-${result.team_id}-text">Level ${gymLevel}</b>

**Comment by maddhatter** [comment]
Make sure you `npm install` or `grunt build` after you update that line (about it outputing 7)

I mocked everything up with hardcoded values, looks like I missed that variable. Thanks!

**Comment by equatebrand** [comment]
Yeah, I realized that after I said it.  Working great now, though. Thanks!

**Comment by jorgebsa** [comment]
Very nice addition! Nitpicking, but maybe we could find a transparent background team logo to use on the sidebar?

**Comment by G1K** [comment]
Hello! ) Perhaps you have plans to complement the detailed statistics on GYM? It would be cool to see the top trainers and top pokemonovv selected map area.

**Comment by djv2** [comment]
would be cool to have a stats per user. for example (based on your screenshot), see all gyms/pokemon that philie93 has held

**Comment by n30nl1ght** [comment]
Very nice work.

But it is in conflict with this one
[Enable pulling each pokemons IVs and Moves by starting ](https://github.com/PokemonGoMap/PokemonGo-Map/pull/1272)

So i can't merge :-(

**Comment by jnovack** [comment]
1) On mobile there's not much "side" room.
2) Clicking on the gym should AUTO open the side bar, the popup was gimmicky from Day 1.
3) I don't care for having to click AGAIN on EACH pokemon to see the moves.  Print everything always and shrink some padding.

**Comment by nhumber** [comment]
Love this, any chance for a switch to enable one or the other? i think having both the popup and sidebar is  too much, a toggle for one or the other would be ideal, toggle it when on mobile to only show the sidebar, this would help as its difficult closing the "big" gym popups.

**Comment by Shentang** [comment]
@n30nl1ght I've just removed moves.json and replaced it with this PR moves.json and everything is working. Got both PRs up and running

@maddhatter I'd leave the text black, at least in the yellow team, it's barely readable.

chrome_2016-09-18_16-25-24

**Comment by darkelement1987** [comment]
Can someone with Moves&IV + Gyms sidebar post a working fork? I can't get it to work.

**Comment by SoonDead** [comment]
I have taken a very different route with my pull request: #1340

I personally prefer my layout (why I made the request in the first place) as it feels more lightweight without the sidebars. I don't like to use sidebars on small screens.

**Comment by hd1080** [comment]
This PR is working almost fine for me. I have only one problem that it doesn't show the background color from the move type. I attached a screenshot. As you can see (or maybe not) the water type is in white and barely readable. 
move_type_background

Another thing is the bar for the gym level. I think there might be a bug in the calculating of it. The read one is half full which makes sense but the yellow one is only filled by a quarter and I think it should be filled by three quarters.
half_full
quarter_full

**Comment by irus99** [comment]
@SoonDead I really like the way you did yours. Did you happen to merge it with pr #1272 ?

**Comment by Shentang** [comment]
@SoonDead the difference is, that you see all pokemons and associated trainers with it, while on yours you see only the one you choose. So in this one, with one click you can glance through everything, while on yours you have to click 10 times on 10lvl gyms if you want to check if someone is sitting on that specific gym.

If you would add a button that would show everything as it does here, I'd go with your layout too.

**Comment by gatomiaurex** [comment]
I am new to merging stuff so I just copy / paste the files changed, I know there is a way to merge the changes without doing that but I just don't know how to do it or how to google it, can anyone tell me how to do it? IIRC it was something like git merge something.git

**Comment by hd1080** [comment]
I think I know what is causing the problem that is doesn't show the background color of the move type. I use locale:de and therefore it doesn't show the English name of the move type it is translated into German. The background color is shown for the move type normal because it's the same in German. Do you know how to fix this @maddhatter ?

**Comment by SoonDead** [comment]
@irus99 No, and the moves.json format is different and causes a conflict. I'll try to merge it in 10 hours.

@Shentang You mean that I should add the view details link that opens the sidebar from this PR?

@gatomiaurex The commands are easy and a simple how to use git tutorial helps, but merging in the command line is sometimes hard. I would recommend a GUI like tortoisegit or git extensions that holds your hand through the process.

**Comment by Shentang** [comment]
@SoonDead No, it's up to you how to show it - I don't like the sidebar either, but it does show me all info at once. You could show/hide names above/under CP for example (saw something like this) - if you're concerned about lenght, you can always add three dots and cut at for example 8-9 characters to make it not look shitty.

All in all, I don't really have an idea how to do it, but seeing whose pokemon is sitting in a gym is an important information for me, and this PR does it, even if it does it badly as for now.

**Comment by SoonDead** [comment]
@maddhatter I really like the classes for the type labels that color them. They would be useful for other parts of this app, like the pokemon details popup could use these classes for coloring instead of requiring a color in the server response.

This would require these classes to not be nested inside the belly of the gym details scss.

Can I steal your classes for a pull request where I want to remove type colors from the raw_data response?

**Comment by hd1080** [comment]
@SoonDead his coloring does't work with other translations besides english (the locale parameter). I think this should be fixed first.

**Comment by SoonDead** [comment]
@hd1080 Good to know as I only use it in english. Should be fixed by refactoring the translations.

**Comment by Imoq** [comment]
Perhaps outside of the scope of this PR (or perhaps not!) but it would be cool to have a page with users stats, if we are already collecting them; for example: userx has taken X number of gyms (Y currently), and his Pokémon army is: XXX, XXX and XXX with those stats. That's the general idea, anyway.

**Comment by hd1080** [comment]
It would be cool to see how many free slots a gym has. I already implemented it in my fork and it looks like this.
free slots

- the pokemon stats order should be change. ATK should be first and then followed by DEF. PR #1272 shows also ATK as first and it's on every website (for calculating IVs) so.

- the team pictures should be exchanged by ones with transparent background. I found good ones on this website https://jackaloupe.com/2016/07/06/all-pokemon-go-team-logos/  I guess they are free to use. I am already using them here https://github.com/hd1080/PokemonGo-Map/tree/develop/static/forts so maybe you could just copy past them into your PR.

**Comment by primaxius** [comment]
I agree with hd1080 :)

**Comment by darkelement1987** [comment]
Thanks @hd1080 you are awesome! Are lured pokestops built in on your fork :)?

Only thing i don't like is, i've set my instance to search at "-st 24" but it keeps searching for gyms further and further away, like half the netherlands while it should only scan within a 3 km radius or something.

**Comment by SoonDead** [comment]
@darkelement1987 those gyms are most likely old data. Check the last scanned date on gym labels

**Comment by darkelement1987** [comment]
nope

**Comment by jnovack** [comment]
RE: Free Slots on a Gym.

I imaged more the following than a silly text number.

image

**Comment by darkelement1987** [comment]
I think my friend's worker (which works on my db) is the bad one, it scans like this (with the dots way outside radius), what could this be?

claire

**Comment by jnovack** [comment]
Is this related to the PR or something that should be taken elsewhere?

**Comment by darkelement1987** [comment]
I just changed the yellow text @ Team Instinct (see screen), you can grab my files here if you like:
http://www.filedropper.com/replace_1

instinct

**Comment by darkelement1987** [comment]
Hmm, it's not my friends instance, it's my own as it's the only one scanning for gyms. I'm using fork by @hd1080

**Comment by pedrothome** [comment]
There is a way to close the sidebar?

**Comment by darkelement1987** [comment]
Just click in the map again

**Comment by Dagothur** [comment]
the reason your gym scans are jumping so far is because if pokemon scanning is disabled the step radius is automagically modified to be much larger. the reason is because seeing pokemon is only 70m but seeing pokestops and gyms is closer to something like 900m ...

**Comment by primaxius** [comment]
@maddhatter  Changes still required (UPDATED)
- Rebase
- CSS fix for sidebars 
- Yellow text
- Free slots 
- Reorder IV data to match commonly used format  (ATK/DEF/STA)
- transparents logo 

References : 
https://github.com/PokemonGoMap/PokemonGo-Map/pull/1343
https://github.com/PokemonGoMap/PokemonGo-Map/pull/1316#issuecomment-248558030

**Comment by Bizadon** [comment]
@maddhatter Doesnt work on me, may be I am doing something wrong? I git clone branch
https://github.com/maddhatter/PokemonGo-Map/tree/gym-sidebar
from you and try to run, but no I dont see "view details" link.

**Comment by darkelement1987** [comment]
@hd1080 I'm using your repo, but why did you disable Pokémon Rarity @ the pokemon labels on the  map? I tried removing the comment-out tags (<!--) @ static/js/map.js but that doesn't seem to help.

How can i get it back :)?

**Comment by hd1080** [comment]
@darkelement1987 I removed it because it is not an important information for me and it just uses too much space on my small smartphone screen. But if you want it back just remove the   . After that you have to run grunt build and refresh your browser window.

**Comment by jtp10181** [comment]
This is working great for me. Current merge conflict is just because another function got added to the map.js on dev, so it was easy to resolve. I do agree the yellow text needs adjusting.

**Comment by mew905** [comment]
trying this out on my phone with the code current as of 4 hours ago, I really do like it, but I have a horizontal scroll bar (and there's a gap between the left edge of the sidebar and the actual data), and it uses up 80% of my screen. If we could shrink that just a bit to play nicely with phone's that'd be awesome. the screen usage isn't a *huge* deal, but that horizontal scroll makes it a pain in the butt. On the desktop browser (chrome, specifically) it works awesome.

**Comment by darkelement1987** [comment]
Oh sidebar doesn't work with the maps full screen mode. Or is it meant that wat?

**Comment by mew905** [comment]
No, tested on my lg g5 phone, theres a small white gap on the left side of the sidebar when its up, and the information is wider than the sidebar, meaning i have a horizontal scroll bar and have to scroll left or right to see atk iv or move damage, but not both.

**Comment by darkelement1987** [comment]
Wasn't meant to you lol its Just another problem

**Comment by arnaudverniers** [comment]
Hi,

First, thanks for the featuer, really good one.

Then, i changed the 13 files, for each i just click on "view" > "raw" and copy paste but now, i can't even launch the server ...

Thanks for the help.

error

**Comment by 3Trace** [comment]
Any instructions out there about how to set up and test any of these beta enhancements? Non-developer here, but I'd love to test it out.

**Comment by wobblybobz** [comment]
Has this stalled? I have taken this Pull Request and rebased it and made the other requested changes.
https://github.com/wobblybobz/PokemonGo-Map/tree/gym-sidebar
Should i create a pull request for this? So this one can be closed and it can finally get merged?

**Comment by mew905** [comment]
yes, please make a PR. I'd like to add this with the corrections added in :)

**Comment by k4n30** [comment]
Those still wanting this should upvote #1422

**Comment by primaxius** [comment]
See 1422

**Pull request closed without merging**
