### PR TITLE
Added basic authentication to scan location change

### PR DESCRIPTION
**Pull request by kev007**
## Description
Added -t command line and tokens config.ini options to set an authentication requirement for scan location changes 

## Motivation and Context
I like to share viewing access of my public instance of PokemonGo-Map with trainers I often meet at PokéStops and Gyms. The problem arose that everyone was trigger happy, causing the search location to jump wildly across the city, preventing a complete scan of each area. By restricting users without a token/password to view-only access, it should limit this issue.

## How Has This Been Tested?
1. With command line argument
2. With config.ini
3. Not configured

## Screenshots (if appropriate):

- Entry field is visible only if server is configured for it
image

- Example config
image

- 401 on authentication failure
image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
(Travis CI informed me of my errors - fixed)
- [x] My change requires a change to the documentation.
(ddition to command line documentation)
- [ ] I have updated the documentation accordingly.
(If this PR gets accepted, I will certainly update the wiki!)

## Notes
This is really basic plaintext authentication! Unhashed password is stored as cookie!

TODO: stop using plaintext ;)

### CODE REVIEW

**Comment by chuyskywalker** [comment]
Actually: #642

**Comment by kev007** [comment]
Oh well, at least this can be a stopgap solution until #642 hits stable.

**Comment by chuyskywalker** [comment]
Do appreciate it, just bad timing :)

**Comment by primaxius** [comment]
Delined.

**Pull request closed without merging**
