### PR TITLE
Throw exception if attempting -speed with no_gym and no_pokestop

### PR DESCRIPTION
**Pull request by smc87**
- Early in the code. Could move back to schedulers or elsewhere that anyone thinks more appropriate.

## Types of changes
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by forcewill** [comment]
To use speedscan we must scan also gyms or pokestops?

**Comment by smc87** [comment]
Yes, its in the docs, otherwise you get 0/0/0 scans.

**Comment by WalterMagnum** [comment]
Not that this is the place,  but if no gyms / pokestops are found it thinks you are over the speed limit.

**Comment by MysticalOS** [comment]
That explains a few things. where I live there are no pokestops or gyms.

**Comment by averylarry** [comment]
I'm not sure this is actually a requirement.  I'd prefer to leave it as a warning instead of a fatal error and exit.

**Comment by kevdotcom** [comment]
Not everybody does it with arguments... Many people probably turned it off in the config.

You should change the Exception accordingly.

**Comment by smc87** [comment]
Updated the message to be more generic.

**Comment by averylarry** [comment]
@smc87 But there's no reason other than excessive warnings to have gyms or pokestops with -speed.  I think that I *should* be able to run -speed without gyms and pokestops if I want to (which I do, because I don't ever care about gyms or pokestops and I don't want them in my database).  That's why I advocate for a warning instead of a full exception/exit the program.  I'd even suggest a warning with some type of "press any key to acknowledge that -speed works better with gyms or pokestops" prompt.

I think a warning is good.  I think the rest of it should be fixed by modifying the -speed logging/warning messages.

**Comment by sebastienvercammen** [comment]
@averylarry I was told on Discord by participating members in @Artifice's original speed PR that it requires either gyms or pokéstops because it bases its definition of a "good scan" on the result of those gym/pokéstop scans.

From Artifice's PR:

```
Speed Scheduler uses visible Gyms and Pokestops to determine if a scan is valid. Try adding gyms and stops back into your scan.
```

If you want to review speed scanning and how gyms/pokéstops relate to them (to see if everything works properly without them), you're welcome to. If it does work perfectly, include @Artifice and me in your mentions, because it means I've gotten wrong information from the author and something needs to be changed.

**Comment by TheNewDarkOne** [comment]
Ah that explains why it was pretty useless when I ran it. It was literally dropping VALID spawn points because it couldn't figure out what was going on. I am rural and there are LITERALLY no pokestops or gyms near me. If it's using them to determine if a scan is valid then it will certainly have no idea what's going on where I live. I honestly just need it to scan everything every 15 minutes until it finds all spawn points, period. it should just do a good ole beehive to get spawn points, THEN start rescanning spawn points to get TTH. all in all i feel -speed was probably the worst of the 3 PTRs they could have merged for valid TTH. spawn points.

**Comment by averylarry** [comment]
models.py lines 1457 - 1467 should be changed to include nearby_pokemon.  It should not speculate regarding -ng and -nk since it can actually lookup the arguments.  Lines 1469 - 1471 should be merged into 1457 - 1467 to provide a single clear warning message regarding 0/0/0 scans.

**Comment by averylarry** [comment]
PR #1662 alleviates the misleading/confusing logging and reduces (eliminates?) speed scanning's reliance on gyms/pokestops.

**Comment by smc87** [comment]
Closed in favour of: https://github.com/PokemonGoMap/PokemonGo-Map/pull/1662
Which  actually fixes the problem, rather than preventing running with the desired options.

**Pull request closed without merging**
