### PR TITLE
Fix map V.2

### PR DESCRIPTION
**Pull request by nullpixel1**
## Description

In this update:

- Updated requirements to use the pogodev API, which should be updated shorty
- Fixed a null pointer error whilst using the new API

## Motivation and Context

Your discord was enough motivation  (mapppp)

## How Has This Been Tested?

impatient people got it working 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by nullpixel1** [comment]
yey

**Comment by smartcuc** [comment]
snief.. Not working on my end:

[utilities][   ERROR] Could not find linux2 hashing library /usr/local/lib/python2.7/dist-packages/pgoapi/lib/libniantichash-linux-arm-32.so

The file is in that location....

**Comment by Stuck7hrottle** [comment]
I got the same error except my path is slightly different. /opt instead of /usr.

**Comment by smartcuc** [comment]
Well, it's missing as part of the api. Once it has been released pgoapi needs to be re-installed.

**Comment by smartcuc** [comment]
There are two libs missing to get it working on PI's:
libencrypt-linux-arm-32.so
libniantichash-linux-arm-32.so

**Comment by m3g4mInD** [comment]
I have tried but still dont show any pokemon or gym or pokestop only empty scans 5 acc in 500mtrs radius
.

**Comment by nullpixel1** [comment]
Linux 32 and 64 is not yet supported

**Comment by Bart274** [comment]
@nullpixel1 so if I understand correctly, using the latest version still doesn't work until a new update is released of the pgoapi? (Just to make sure it's normal the map isn't working yet)

**Comment by kamaze** [comment]
please check /usr/local/lib/python2.7/dist-packages/pgoapi/lib/howto_compile.txt
you can compile these library by yourself.

**Comment by Beri51** [comment]
For  libniantichash-linux-arm-32.so I did this:
```
wget https://gist.github.com/popcornmix/f94e6ab0566a60b7fd1e8acccc0647f8/archive/5e3e07c
e7d3bc66ce1f4401571e0195e0d0d5128.zip

unzip 5e3e07ce7d3bc66ce1f4401571e0195e0d0d5128.zip

cd f94e6ab0566a60b7fd1e8acccc0647f8-5e3e07ce7d3bc66ce1f4401571e0195e0d0d5128/

gcc -Wall -std=c99 -fPIC -shared -o libniantichash-linux-arm-32.so niahash.c

cp libniantichash-linux-arm-32.so /usr/local/lib/python2.7/dist-packages/pgoapi/lib/
```
[Source](https://github.com/pogodevorg/pgoapi/issues/145)

I have no solution for the libencrypt-linux-arm-32.so unfortunately.

**Comment by forcewill** [comment]
@Beri51 , @smartcuc  i have a RPI i will test it and let u guys know

**Comment by z0mbiel0ve** [comment]
After following those same instructions above for libniantichash (and downloading libencrypt from here https://github.com/TBTerra/spawnScan/tree/master/lib)

I am stuck with this: 
2016-11-06 19:20:54,120 [ search-worker-0][        search][ WARNING] Exception while downloading map: NULL pointer access

Which is then followed by an error abandoning the location.

**Comment by Beri51** [comment]
Ok, thanks to https://github.com/pogodevorg/pgoapi/pull/148 I could get it to work on Rapsberry Pi.
Just dl the files and copy them to /usr/local/lib/python2.7/dist-packages/pgoapi/lib/

**Comment by kamaze** [comment]
@z0mbiel0ve i have just solved similar issue. I found it was caused by downloaded libencrypt is old version.
you can follow this instructions to build the new one:
https://github.com/pogodevorg/pgoapi/issues/147#issuecomment-258861745

**Comment by smartcuc** [comment]
With the new lib's I'm getting "Parsing found 0 pokemons, 0 pokestops, and 0 gyms."
Hm, do I need new accounts?

**Comment by djgreg13** [comment]
great, working with old accounts

**Comment by smartcuc** [comment]
Have taken the last version, copied the lib's into the directory.... and still 0/0/0... What do I wrong?

**Comment by nullpixel1** [comment]
Please can you stop abusing this thread?

**Comment by necre** [comment]
we love NULL

**Comment by z0mbiel0ve** [comment]
@kamaze Thanks! That did the trick for me as well.

**Pull request merged**
