### PR TITLE
PR Merge for Testing

### PR DESCRIPTION
**Pull request by Janglinator**
❗️  I do NOT want this merged.  ❗️

I created this only because soooo many people don't know how to grab individual branches, only PR's.  Also, there was no place to contribute discussion to this branch, so this seemed like the best place where people could pull and discuss.

## Description
This is a PR to *TEST* multiple existing PR's together, along with the latest of development.

Current PR's:  #1367, #1476, #1477, #1530, #1556, #1566

## Motivation and Context
We're all experiencing catpcha's up the wazoo.  The current development branch only makes this worse.  We have a few great PR's that attempt to fix this issue (as much as possible), but due to the complexity of them, they're still waiting for review.  This will let us see what the end product will look like when a select few integral PR's get merged.

## How Has This Been Tested?
I haven't had much time to test it thoroughly  😆   I'm counting on others to be able to test it for me.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Dcstegg228** [comment]
I will begin testing shortly.

**Comment by Janglinator** [comment]
It looks like #1566 broke the captcha_request definition:  https://github.com/PokemonGoMap/PokemonGo-Map/pull/1566/files

**Comment by Dcstegg228** [comment]
So should I try this out or not? Im waiting on the funds to clear into my 2captcha account then im ready to fire this up.

**Comment by Janglinator** [comment]
@Dcstegg228 You can test  :)  I just reverted PR 1566, which was causing the issues

**Comment by Alderon86** [comment]
So i can merge this without errors into a clean develop build?

**Comment by filippounitn** [comment]
python runserver.py -a ptc  -u USERS -p PASSWORD-w 60 -st 11 -l "LOCATION"  -k KEY -sd 30 -gi -ld 1 -wh http://127.0.0.1:4000 -nk -cs -ck 2CAPTCHAKEY -pd 48 --db-threads 50 --wh-threads 50 -ps -sl 32 -asi 0 -ari 10

using this command, used to work not now idk tried some different things like bh -w 11 -st 5
It keeps saying waiting for item from queue, can't get the beehive to scan
any clue? PR problem or mine?
(caps lock words are "hidden" for obv reasons)

**Comment by Janglinator** [comment]
@Alderon86 Yes, but that's what this is; multiple PR's merged into a clean develop build.

@filippounitn Dang sounds like a PR issue  :/  I'll take a look.

**Comment by filippounitn** [comment]
I deleted my comment. It works. Only problem was that before starting it had to calculate a lot of things around 5+ mins calculating I though it was broken. It's because I was using -st 11 (no -bh).
Now i'm using -w 90 -st 2 -bh, working perfectly and wait time before starting is low (10 seconds or so).
Thank you

**Comment by ic4roswings** [comment]
[1551.zip](https://github.com/PokemonGoMap/PokemonGo-Map/files/607343/1551.zip)

I added 1551 I dont know why i cant uploaded to my fork but here are the files with the changes

**Comment by jane0815** [comment]
After 30 min i get this error:

`2016-11-22 20:27:26,113 [      db-cleaner][        models][   ERROR] Exception in clean_db_loop: (1213, u'Deadlock found when trying to get lock; try restarting transaction')
Traceback (most recent call last):
  File "/Users/yuri/PoGo/PokemonGo-Map/pogom/models.py", line 1179, in clean_db_loop
    query.execute()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3274, in execute
    return self.database.rows_affected(self._execute())
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/site-packages/playhouse/shortcuts.py", line 203, in execute_sql
    sql, params, require_commit)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
  File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 161, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 317, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1021, in _read_query_result
    result.read()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 983, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1213, u'Deadlock found when trying to get lock; try restarting transaction')
`


And from that moment more and more account fail to login:

Failed to login to Pokemon Go with account XYZ. Trying again in 10 seconds

The accounts that can not login get more and more. When i stop the map and start it again all accounts work fine again.

**Comment by Janglinator** [comment]
The hard part with a merge like this is it's tough to debug, because I'm not sure which changes were made by which pr  ☹️

**Comment by slideup-benni** [comment]
@Janglinator maybe "blame" will help you :)

**Comment by Janglinator** [comment]
Haha I suppose.  I don't have a lot of time to be able to test/debug though  :/  I only merged these all together because so many people have asked about it

**Comment by gabaod** [comment]
1213 is typically an issue with how the main code does sql queries and i believe whats happening is some are going before others causing an issue in streamlining them.   could be wrong.     you can see if these changes fixes it.  max_connections = 500
open-files-limit = 500
table_open_cache = 512
table_definition_cache = 1024
wait_timeout = 60
interactive_timeout = 120

ive noticed the 1213 only happens when you scale up too large, and to bypass it would be run multiple hives next to each other in smaller size.

**Comment by jane0815** [comment]
@gabaod when i add those changes to config.ini the map would not start up. 

I am currently running 37 workers, scan delay 20, login delay 10, step limit 3

The map is runnig on Mac OSX. Mysql is on a Pi running Raspberry in the same local network.

**Comment by gabaod** [comment]
those are my.cnf settings for mysql.. not for POGO

**Comment by jane0815** [comment]
My mysql does not even want to start when i add those settings to my.cnf :(

**Comment by Arengo** [comment]
So how is it going so far regarding reCaptchas?

**Comment by FrostTheFox** [comment]
I plan to close this when I get home. I get you're trying to help, but this isn't what PRs are for. PRs are for pull requests, requests for your code improvements or additions to be added. This is just bringing a bunch of PRs together because people don't know how to merge in multiple PRs themselves. If they don't know how or are having issues doing so, then they shouldn't be trying. Everything in PR is considered experimental until merged and is not recommended for use by anyone besides those who understand what each line of code is for and how to use git properly.

**Comment by FrostTheFox** [comment]
If you want to actually help, test code. Approve the changes via github. If I test and it works, and I see a couple approvals on the PR I'll usually merge it.

**Comment by thatsweater** [comment]
CLOSE ME DADDY

**Comment by sebastienvercammen** [comment]
I agree with @FrostTheFox. Help devs by submitting feedback to actual PRs. Don't abuse PRs just because some people don't fully understand them.

**Comment by BaIthamel** [comment]
Closing since fox is not at pc.

**Comment by xrobau** [comment]
> If you want to actually help, test code. Approve the changes via github. If I test and it works, and I see a couple approvals on the PR I'll usually merge it.

A pile of the pending PRs have lots of people saying 'This works fine, have tested it, it's great'.  If you're expecting people to click the approve button, you may not be aware, but that's *not available to most people*.

**Comment by Janglinator** [comment]
I absolutely concur.  We can't approve changes because only a select few people have the ability.  And they don't do their job, I've said this multiple times.  I've tested and thumbs-upped many PR's, and nothing happens.

"If you want to actually help" What are you implying?  I have 2 PR's, both waiting for review, both in the same situation as all the other PR's.

"...they shouldn't be trying" Is that really how we treat our non-dev fans?  "Oh don't know how to perform a complex git merge with about 100 conflicts?  Well piss off!"  The simple fact is this repository is useless without he PR's.  We're trying to fix ACTUAL issues, and not just adding periods to the end of every comment.  I was sharing this branch, but a lot of people were confused how to pull it, but they know how to pull individual PR's.  So I stuck my neck out, lent them my time, and pushed it to a PR.

**Comment by FrostTheFox** [comment]
You really can approve changes, though. Click the files changed button at the top of the PR, and approve changes on the left. I just did this on an account with no special repo access. Please don't say things that you're not sure about.

@Janglinator It wasn't directed at you specifically. It was a general statement.

Yes. Because it's experimental code. Period. It's not meant for use other than people who are capable to pull the code themselves. I'm sorry that you think it's useless without it. Believe it or not, I have a life outside sitting in Discord and reading Github PRs all day.  And thanks for the period thing. It's clear i'll never live that down, but I don't care that you're trying to insult me with it. The PR is still available to pull. It's staying closed, because it's not a valid PR.

I have some thanksgiving break here, so I can test a bunch of code and try to merge stuff in. 

What? I don't even get what you're trying to elude with the **TO BE ADDED** part.

**Comment by FrostTheFox** [comment]
If you wanna continue the discussion, talk to me on Discord. I'm not going to continue here.

**Comment by xrobau** [comment]
> You really can approve changes, though. Click the files changed button at the top of the PR, and approve changes on the right.

Well. Bugger me. I do apologise, I did not know that was there.

**Pull request closed without merging**
