### PR TITLE
gevent hotfixes

### PR DESCRIPTION
**Pull request by gabrielsoldani**
## Description
Fixes logging and handles KeyboardInterrupt

## Motivation and Context
* **Thunderfox said he would break my leg if gevent broke things.**
* gevent error logs were being written to stderr instead of using our logger.
* gevent info logs were being written to stderr instead of using our logger when `--verbose` or `--very-verbose` are on.
* KeyboardInterrupt was crashing the main thread instead of gracefully exiting.

## How Has This Been Tested?
I ran it on my computer.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by FrostTheFox** [comment]
i did say that and now i'm gonna fuckin bite into your legs as hard as possible

**Comment by FrostTheFox** [comment]
cmon travis lets go boii

**Comment by bluelatios** [comment]
Traceback (most recent call last):
  File "runserver.py", line 20, in <module>
    from gevent import pywsgi
ImportError: No module named gevent

-__-

what should i do?

**Comment by Qualimiox** [comment]
@bluelatios You'll have to install gevent.
Just run pip install -r requirements.txt again, that should work.

**Comment by mbg032373** [comment]
I had to manually install gevent on OSX to make this work.  It would read it from requirements, but not install it for some reason?  Had to also to use sudo to get it to take as well.

`sudo -H pip install gevent`

**Comment by SeeingBlue** [comment]
`C:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map>pip install gevent
Requirement already satisfied (use --upgrade to upgrade): gevent in c:\python27\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.9 in c:\python27\lib\site-packages (from gevent)

C:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map>C:\Python27\Python.exe c:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map\runserver.py -os -H 0.0.0.0 -P 5000 -nsc -fl -k A*************o -l "36.214, -83.2949"
Traceback (most recent call last):
  File "c:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map\runserver.py", line 20, in <module>
    from gevent import pywsgi
  File "C:\Python27\lib\site-packages\gevent\__init__.py", line 49, in <module>
    from gevent.hub import get_hub, iwait, wait, PYPY
  File "C:\Python27\lib\site-packages\gevent\hub.py", line 11, in <module>
    from greenlet import greenlet, getcurrent, GreenletExit
ImportError: DLL load failed: The specified procedure could not be found.`

**Comment by bluelatios** [comment]
@Qualimiox works like a charm thanks :D

**Comment by SeeingBlue** [comment]
Still aint working for me. Same error as above.

**Comment by gabrielsoldani** [comment]
@SeeingBlue What `python --version` are you running? A quick Google search says a python update (the current version is 2.7.12) might fix your issue.

**Pull request merged**
