### PR TITLE
Status screen improvments - paging, new queues

### PR DESCRIPTION
**Pull request by justsomedudeonthenet**
## Description
Incorporate paging into the status screen.  It will figure out how many lines fit in your terminal and page the worker list appropriately.

Add the new database and webhook queues to the status screen.

## Motivation and Context
Balthamel asked for paging.  Some people run way too many workers to fit on a screen.
http://feathub.com/PokemonGoMap/PokemonGo-Map/+69 asked for the new queues to be shown.

## How Has This Been Tested?
On my linux server.  Should work on windows as well.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by justsomedudeonthenet** [comment]
This incorporates https://github.com/PokemonGoMap/PokemonGo-Map/pull/839, which I closed because it would have caused merge conflicts.

**Comment by Becold** [comment]
> Minor text fixes
image

**Comment by xPersei** [comment]
paging

I know it doesn't look as bad as for other people with more workers, but it was getting trickier to monitor all of them. 

Thank you very much for your work.

**Comment by justsomedudeonthenet** [comment]
@xPersei crap...you just gave me an idea for a potential bug in this.  I didn't think of people running terminals at unusably small sizes...

**Comment by xPersei** [comment]
[stacking](http://i.imgur.com/61S57qO.png)

@justsomedudeonthenet My case may fall away from the norm, it was the result of using "Show windows stacked" on Win10 as a non-tech-savvy way for monitoring.

**Comment by justsomedudeonthenet** [comment]
@xPersei Yeah...but there would have been a bug where if your terminal was exactly 6 lines high, it would have tried to divide by zero.  That is fixed now (though it still won't be as useful at such small sizes).

**Comment by BaIthamel** [comment]
Ahahaha divide by 0? xD

**Pull request merged**
