### PR TITLE
_nav.scss: pokestop scrollbar fix

### PR DESCRIPTION
**Pull request by CoolCanuck**
## Description

fixed a scrollbar appearing after toggling pokestops on. 

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by CoolCanuck** [comment]
@chuyskywalker not accepted yet =_=?

**Comment by chuyskywalker** [comment]
I checked this out and don't notice any difference.

**Comment by CoolCanuck** [comment]
Ugh. I'll make a video tomorrow.

**Comment by Chlodochar** [comment]
I do not notice any horizontal scrolling behavior in the sidebar. Was this already fixed?

**Comment by CoolCanuck** [comment]
Here's proof. 
http://i.imgur.com/dlsKKoR.png

http://pgobarrie.ca/Scrollbar.mp4

**Comment by chuyskywalker** [comment]
Aaaahhhh, I see. You did, however, fix a symptom and not the problem. Watch the animation and pay attention to what's happening to the "Hide Pokemon" area. 

I've applied the proper fix for this here in #1028, please give that a quick try and let me know.

**Pull request closed without merging**
