### PR TITLE
Correct "Pokemon(s)" to "Pokémon" in log message and status page

### PR DESCRIPTION
**Pull request by Darkknightz**
## Description

Minor text fixes
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by justsomedudeonthenet** [comment]
Much as everyone love a good meme, I've edited the title to reflect what it actually does - makes it easier on devs deciding what to merge.

**Comment by Darkknightz** [comment]
Thanks dude!

**Comment by Zentriert** [comment]
Noooo! I've been dreading the day you fix this "typo" .... after seeing all the other "minor text fixes" recently I figured eventually someone would try to fix Pokemons ...  

I was sad enough when it stopped saying "Upserted 2 Pokemons ... " because it sounds hilarious, but taking away Pokemons too... you've gone too far! 

It was too funny the way it was and I figured it was done on purpose?

**Comment by justsomedudeonthenet** [comment]
I kinda wanted to really enrage some people and change the plural to Pokemen.  Because I keep meeting random people who don't play calling them that.

**Comment by Zentriert** [comment]
I definitely hear "Pokeman" and "Pokerman's" more often, which I find
hilarious.

**Comment by primaxius** [comment]
Breaks on terminal - Declined
http://prntscr.com/ckwp6a

**Pull request closed without merging**
