### PR TITLE
Rebase -ss compression branch (#765)

### PR DESCRIPTION
**Pull request by jchristi**
Fix merge conflicts in #765 so that it merges cleanly.

## Description
See #765

## Motivation and Context
#765 is a great new feature, but it has had merge conflicts for several days. LGTM! See #765 for original motivation and context.

## How Has This Been Tested?
I tested overnight and see that compression works, however I do see many empty results. I did not write original PR so I am not as familiar with this code. Needs additional testing.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by EdenGottlieb** [comment]
I need this.

**Comment by jchristi** [comment]
@FrostTheFox I'm not going to bother keeping this branch updated unless I receive some confirmation that there is a willingness to merge this feature.

**Comment by averylarry** [comment]
I don't know how much hope there is for this since #990 was merged.

**Comment by jchristi** [comment]
I think the algorithm in #990 is more efficient, however, I don't like that there is no option to calculate at runtime the way this PR does. I might look into implementing that if there is interest from project maintainers.

**Comment by primaxius** [comment]
Just use the tool.

**Pull request closed without merging**
