### PR TITLE
Prevent "Speed violation?" message when using --no-pokemon

### PR DESCRIPTION
**Pull request by snooter**
## Description
Using the --no-pokemon flag will always result in no nearby_pokemons or wild_pokemon.

## Motivation and Context
Prevents log spam.

## How Has This Been Tested?
Run in a remote area without --no-pokemon to see the message, run in a busy area with --no-pokemon to suppress the message.

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sebastienvercammen** [comment]
You didn't check the code properly, `nearby_pokemons` is still used as usual because the Niantic servers will return this data (they are unaware of any "no Pokémon" flag), even with Pokémon scanning disabled.

It's `wild_pokemon` that is used for Pokémon parsing later on which will be empty.

This PR does not fix anything.

**Comment by Obihoernchen** [comment]
@sebastienvercammen I disagree.
This PR is totally fine because the speed violation message is wrong for no pokemon mode. **There is no speed limit for gym/pokestop scanning**. `nearby_pokemons` and `wild_pokemon` can be empty, it doesn't matter. Gyms/stops are scanned regardless.

**Comment by snooter** [comment]
I'm still wrapping my head around all of the inner workings here, but I agree with @Obihoernchen .  I'm probably exceeding the speed limit, which is resulting in zero nearby_pokemons and wild_pokemon, but that doesn't matter because the -np flag explicitly says I don't care about that, and I'm still getting the gym information I requested. 

All I know is that with this PR, when using -np for gym scanning, my logs are spam-free, and nothing is changed when not using the -np flag.

**Comment by snooter** [comment]
To simplify: this PR only suppresses a "no pokemon found" message when using --no-pokemon, which seems pretty innocuous.

**Pull request closed without merging**
