### PR TITLE
Fix pip requirement installation

### PR DESCRIPTION
**Pull request by Th3Mouk**
## Description
pip requirements can't be install for projects in development.
Tickets resolutions: #283 #277 #276 

## Motivation and Context
The installation can't be complete on pip requirements

## How Has This Been Tested?
 - OSX El Capitan
 - Python 2.7.10
 - pip 8.1.2 from /Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg (python 2.7)

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Chlodochar** [comment]
I'm not sure all of those tickets are the same problem, but `-e` is how requirements.txt looked on AHAAAA's repo too. Apart from the rebase, this looks good :+1:.

**Comment by chuyskywalker** [comment]
This shouldn't fix anything, it just changes the install mode. The `-e` turns on "editable mode" https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support -- which we don't need. 

Also, you have a commit-sha change in there because...?

**Comment by chuyskywalker** [comment]
In fact, just a little bit lower in the doc, git examples are present: https://pip.pypa.io/en/stable/reference/pip_install/#git

**Comment by chuyskywalker** [comment]
After looking over the linked errors, none of them are because of our current format. 

:-1: on this request.

**Comment by Chlodochar** [comment]
@chuyskywalker is right. Closing this PR.

**Pull request closed without merging**
