### PR TITLE
Status Page (#908 Resubmission)

### PR DESCRIPTION
**Pull request by maddhatter**
## Description
Resubmitting #908 with merge conflict resolutions, and two minor fixes:
1. Fix typo
2. Workers clear all their old statuses when they start

## Motivation and Context
#908 has not been being updated

## How Has This Been Tested?

See #908

## Screenshots (if appropriate):
Example Login Page
Example Status Page

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by maddhatter** [comment]
Documentation page is coming shortly...

**Comment by Darkknightz** [comment]
Thanks for this! One typo though in the overview it says "Skiped"  (See screenshots in example) I guess this should be "Skipped".

**Comment by FlarumHostingCo** [comment]
Would love a way to see hung processes as well in status.  Been seeing an issue lately where a runserver.py will remain hung, not quiting and spiking server load as a result forcing to find which one via top and then using kill -9 on the PID.

**Comment by FlarumHostingCo** [comment]
Can this be made to run too if using --no-server too?   Would love to see status of bots via web interface without having to run a unused webserver to keep resources used to a minimum.

**Comment by maddhatter** [comment]
Yeah, you just set the `-sn` on each worker, and they'll report their statuses into the database. You have to have at least one process running the web server obviously as well, if you want to see the statuses.

**Comment by obsess** [comment]
Killing a task with ^c will leave the -sn instance and workers listed even if the process is killed.

**Comment by SlasherKG** [comment]
Yeah, I was testing this and created different status names, now I have bogus tables on the status page.
anyway to clear old/unused?

**Comment by obsess** [comment]
Maybe clear with clean db based on last connected? > 10min?

**Comment by chuyskywalker** [comment]
Yeah it cleans up stuff older than 30 minutes I believe.

**Comment by SlasherKG** [comment]
You're right. This morning it only has the latest instance.
Thank you!

**Comment by ultrafunkamsterdam** [comment]
How do i add the status page behind NGINX?

Part of my serverblock below. Normal (/go/) works perfectly. but /go/status/ does not.

a GET or CURL in my shell returns a login page, so the status page is actually running. 

The 'page not found' error is not coming from NGINX. 

Also trying only single location  /status/  does not work.

nginx:

location /go/ {
		proxy_pass http://127.0.0.1:5000/;
		proxy_redirect off;
}

location /go/status/ {
		proxy_pass http://127.0.0.1:5000/status/;
		proxy_redirect off;
}

**Comment by maddhatter** [comment]
I'm running behind an nginx reverse proxy without issues. Make sure that you set `status-page-password` in your config.ini or `-spp` on the command line for the web server process. If you don't set that, it 404's

**Comment by djv2** [comment]
@maddhatter for testing, i'm running 1 worker with multiple accounts. i set -spp -sn on this 1 worker and the page is blank. is this normal? or does -spp have to be set on main server and -sn on all the other workers?

**Comment by maddhatter** [comment]
https://pgm.readthedocs.io/en/develop/extras/status-page.html

**Comment by djv2** [comment]
@maddhatter if that was towards me it didn't answer my question ;) ;(

**Comment by ultrafunkamsterdam** [comment]
For me it's somehow working now, except for 1 little thingy.

/go/5001/status is working  
/go/5001/status/  (slash @ end ) is not working. It gives me the flask 'not found' page, not the nginx one.

config is  simple, no changes needed, but it would be nice if the ending slash like /go/5001/status/
would work.

location /go/5001/ {
		proxy_pass http://127.0.0.1:5001/;
		proxy_redirect off;
	}

**Comment by obsess** [comment]
@ultrafunkamsterdam try this
```
location /go/5001/ {
        rewrite ^/go/5001(.*) /$1 break;
        proxy_pass  http://127.0.0.1:5001/;
}
```

**Comment by ultrafunkamsterdam** [comment]
@obsess Thank you  for your quick answer. Unfortunately it does not work. I also tried incognito session, because sometimes chrome adds the slash when you've visited the page before.

Now,when i go to /go/5001 it automatically adds a ending / , so it becomes /go/5001/ and gives me this error:
ERR_TOO_MANY_REDIRECTS

And when i go to /go/5001/status  it will end up going in /go/5001/ giving the same error.

Suprisingly, when i go to /go/5001/status/ (so WITH the slash)  it's displaying the main application (the maps) while keeping the /go/5001/status/   URL :)

I will  comment out your suggestion, so if there's an alternative i can switch back quick.

For now i will go back to my previous config, and watch carefully not to add the ending slash :) /go/5001/status

**Comment by obsess** [comment]
I had a typo add / after 5001 in rewrite.

**Comment by ultrafunkamsterdam** [comment]
Thanks again!

I assume you meant: 

location /go/5001/ {
		rewrite ^/go/5001/(.*) /$1 break;
    	   	proxy_pass  http://127.0.0.1:5001/;
}

When i go to  /go/5001 it  automatically adds /  
When i go to /go/5001/status  it takes me to /go/5001/ 
when i go to /go/5001/status/  it gives me a Not Found error from flask.

**Comment by obsess** [comment]
I have it working just fine on a subdir. Feel free to msg me on discord and i'll see what I can do to help sort out your issue. obsess#3368

**Comment by ultrafunkamsterdam** [comment]
I made a stupid mistake too. I trusted incognito screen to not remember stuff, but it does. 

I tried your solution using Safari on iPhone which i never used, and it behaves exact the same way as my config. So everything works, except /go/5001/status/   just /go/5001/status works fine.

I will sign up for discord. It's about time now. Seen alot of links towards it, so there must be some interesting discussions on api development i guess. Many thanks for the effort!!! 

location /go/5001/ {
	rewrite ^/go/5001/(.*) /$1 break;
	proxy_pass http://127.0.0.1:5001/;
}

same behaviour as:

location /go/5001/ {
		proxy_pass http://127.0.0.1:5001/ ;
		proxy_redirect off;
}

**Comment by djv2** [comment]
@maddhatter feature request - show worker # too, as it is in search-worker-## in console

**Pull request merged**
