### PR TITLE
Added live push bullet and slack notification when pokemon shows up nearby

### PR DESCRIPTION
**Pull request by beetz12**
## Description
This is an enhancement to POGO map that will automatically notify users of rare pokemons nearby using push notifications via push bullet and slack. Twilio and telegram are also supported but they need to be tested. Major credit goes to @megahambone for his original work. To get started, first you need to obtain a push bullet or slack API key (both are free). Then add your key to alarms.json along with the pokemon you want to get notifications for. 

## Motivation and Context
POGO map is awesome tool at showing all pokemon around you. However, you are a busy trainer and you can't keep your eyes glued to your phone all day waiting for new pokemon to show up. While the app currently already has a built in notification system, it has two major drawbacks: 
1. The pop up notification do not work when your phone is locked. 
2. The pokemon list is not saved, so you have to put them in every time.  

This PR solves both problems by letting you name all the pokemon you want to catch in alarms.json. You will receive instantly push notifications on your phone instantly when the pokemon in your list comes within range.

## How Has This Been Tested?
I tested by using my own slack and bullet credentials in the config file, running the scanner, and verifying that I receive notifications for the desired pokemon. I have an iphone 5S and My environment is Max OS X El Capitan and chrome. 

## Screenshots (if appropriate):
img_2241

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

The instructions for using notifications is located in pogom/alarm/instructions.md

### CODE REVIEW

**Comment by hhu94** [comment]
From a quick look at the code this is essentially integrating https://github.com/kvangent/PokeAlarm/ into our project. I don't like it. We implemented webhooks to allow addons like PokeAlarm and I think it should stay that way.

Separation of concerns and all that.

**Comment by invisiblek** [comment]
i agree

**Comment by andrewda** [comment]
I agree with everything above. We should try to leave stuff like this to the webhooks.

**Comment by DeeFox** [comment]
Maybe add a curated list of webhook addon projects to the readme just like the mentions of the iOS and Android-Client so users can discover those?

**Comment by hhu94** [comment]
@DeeFox For now I know of pokelyzer and pokeralarm, feel free to submit a PR to edit it into the README.

Closing this PR.

**Comment by beetz12** [comment]
Thanks for all the feedback. Based on the comments, looks like I should have done more research before submitting this PR. I fully understand your reason for not accepting this merge. While It would be all too easy to merge it, it comes at the cost of making the code more complex in the long run.

I'd still like to help but being totally new to webhooks,  are there any good resources you guys recommend for learning webhooks in regards to notifications? Also what are some existing webhooks that tie into POGOMap that I can look at?

**Pull request closed without merging**
