### PR TITLE
Update docs to run pip install as user

### PR DESCRIPTION
**Pull request by invisiblek**

### CODE REVIEW

**Comment by chuyskywalker** [comment]
Why?

**Comment by invisiblek** [comment]
shouldn't be a need to run this as root, but it looks like some of the scripts for external stuff (travis for instance) are expecting it?

**Comment by chuyskywalker** [comment]
No, it looks like that travis instance just died. I don't know how to force a recheck without pushing something else to the branch. 

https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption--user

Seems safe enough.

**Comment by Th3Mouk** [comment]
This doesn't solve the installation problem.

**Comment by Chlodochar** [comment]
Just to note, this doesn't work so well with `virtualenv`, but it removes the need of virtualenv in my case (needing to use root). It's better than what it was before. :+1: for merging this once rebased.

**Comment by primaxius** [comment]
tested on virtualenv too ..not good.  Someone tried this and messed up his install as he had stuff installed in 2 locations causing conflicts

**Pull request closed without merging**
