### PR TITLE
Add a spawnpoint clustering script to Tools

### PR DESCRIPTION
**Pull request by gabrielsoldani**
## Description
This is a different spawnpoint clustering algorithm than the ones in #868 and #765.

In my computer it compresses 7001 spawnpoints into 4834 clusters in 40 seconds.

## Motivation and Context
#868 is too slow
#765 picks a spawnpoint and removes all spawnpoints near it
We should instead be scanning the centroid of the clusters, so more spawnpoints can be fitted inside each cluster.

## How Has This Been Tested?
It includes a `test` function that verifies all spawnpoints in a cluster are within `radius` meters from its centroid, and the difference between the earliest and latest spawn time in the cluster does not exceed `time_threshold`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ottowayne** [comment]
Haven't analyzed the code in detail but the results do seem nice.
> python cluster.py ../../spawns.json -os spawns_compressed.json -r 70 -t 20
> Processing 1316 spawnpoints...
> Completed in 2.34 seconds.
> 1147 clusters found.
> 87.16% compression achieved.
>
> python cluster.py ../../spawns.json -os spawns_compressed.json -r 70 -t 30
> Processing 1316 spawnpoints...
> Completed in 2.44 seconds.
> 1098 clusters found.
> 83.43% compression achieved.
>
> python cluster.py ../../spawns.json -os spawns_compressed.json -r 70 -t 90
> Processing 1316 spawnpoints...
> Completed in 1.89 seconds.
> 928 clusters found.
> 70.52% compression achieved.
>
> python cluster.py ../../spawns.json -os spawns_compressed.json -r 70 -t 120
> Processing 1316 spawnpoints...
> Completed in 1.80 seconds.
> 871 clusters found.
> 66.19% compression achieved.

**Comment by MangoScango** [comment]
This is definitely nice. With a 3 minute window it took me from 1799 to 1312. Pretty painless optimization. It needed an edit for my spawns.json though. It was generated with TBTerra's spawnScan and used "sid" instead of "spawnpoint_id".

**Comment by clvv** [comment]
A forseeable problem is with `--jitter` turned on. A plausible solution is to just run this upon launch and take jitter option into account.

**Comment by gabrielsoldani** [comment]
My idea was that you could account for jittering with a smaller radius (so, for example, if you're adding a 10m jitter, `-r 60` should work).

**Comment by justsomedudeonthenet** [comment]
Please if possible make it work for json files that don't have the spawnpoint ID.

Depending on what tools were used to create it, the json file could have `spawnpoint_id`, `sid` or nothing.  The fields required by the main program are just `lat`, `lng`, and `time`.

I am super happy to see this as an optional script.  There's no need to put this in the main program.  The people who need this will be willing to go to the extra couple minutes of effort to compress it once.

**Comment by gabrielsoldani** [comment]
@justsomedudeonthenet Fixed :wink:

**Comment by averylarry** [comment]
Just gonna throw this idea out there.
Could we incorporate jitter directly into spawnpoint scanning compression?
Uncompressed spawnpoint scanning could use a jitter of 69.9m.  However, once you compress the spawnpoints, each new scan cluster will have a unique maximum jitter based on how spread-out the grouped spawnpoints happen to be.  If the compression algorithm also calculated maximum jitter, and stored that in the .json, and then the spawnpoint scanning could use that . . .

It's a lot to ask, I'm thinking.  It seems like a good idea from a jitter/randomizing/more-human-looking perspective.  OK -- I'm probably just trying way too hard.

**Comment by DoktorJ** [comment]
How do I run this pull? I've merged it into my local copy, but it looks like it's just operating on the regular spawnpoint scan (so if there's a tight cluster of, say, 5 spawn points it scans the same area 5 times). Do I need to use something other than the `-ss` flag?

**Comment by gabrielsoldani** [comment]
@DoktorJ This patch does not automatically compress spawnpoints when you launch `./runserver.py` with `-ss`. You must run `./Tools/Spawnpoint-Clustering/cluster.py` before and configure your `./runserver.py` instances accordingly.

`./Tools/Spawnpoint-Clustering/README.md` has instructions on how to run it.

All you have to do afterwards is point the searchers to use the newly generated `spawnpoints.compressed.json` file instead of your uncompressed spawnpoints file.

Note that it will still scan the same area multiple times if the `time` between them is bigger than `time_threshold` (defaults to 180 seconds, can be set with the `-t` command-line arg).

**Comment by topcatzero** [comment]
Nicely done!

I noticed a few clusters consisting of a single spawn point. Some of these had spawn points from larger clusters within the supplied distance. Have you considered finding an algorithm with less greedy clusters, resulting in more evenly distributed spawn points? I'm not sure how complex that would be, but I'm thinking it might look less bot-like if the number of scans centered directly on a spawn point are minimized.

**Comment by beccasafan** [comment]
Here are my numbers comparing this to the [compress_spawnpoints.py](https://gist.github.com/justsomedudeonthenet/f1f4f27d4aa90a616b517e8ced949d88) algo: https://gist.github.com/beccasafan/083ad91cbf0cedb07a6983a4d9702e7a

It doesn't look like it's starting from the biggest clusters. It'd increase the computation, but might be a worthwhile optimization? (Or I just missed that while glancing at it?)

**Comment by beccasafan** [comment]
@averylarry yes, both algorithms take in a time and pair that with the location.

**Comment by averylarry** [comment]
@beccasafan I wasn't clear -- I wanted to check that you and others understood that the algorithms account for time.
For instance -- IF topcatzero is simply looking at the scan circle on the map and thinks that every spawnpoint inside the circle is getting scanned -- that is not correctly taking into account that the "cluster" of spawnpoints is not simply physically close but also within a certain timeframe of each other.

I didn't understand what you meant by not starting "from the biggest clusters" (and I still might not).  I thought it maybe referred to the actual scanning starting with the largest clusters, which clearly wouldn't account for time.  Now I think you're meaning the algorithm should start with the largest physical clusters theorizing that there are more potential physical + time clusters in a dense area.  As such, I think that is hinted at in the code:

169            # pick a random id from a clustered spawnpoint
170            # we should probably not do this

Sorry -- I wasn't trying to sound like I was stupid nor was I wanting to be condescending.  ;-)

**Comment by beccasafan** [comment]
@averylarry ah, yeah I'm using the term "cluster" to match both on time and distance. I was just curious if it was sorting by the number of spawnpoints in a cluster before removing them. Maybe it should start from the lowest though...that might eliminate some more that way because you'd end up with less single clusters perhaps? I'd have to think about that much more.

**Comment by gabrielsoldani** [comment]
@beccasafan I'm a little confused about what you mean, since the algorithm never removes any spawnpoint.

The order in which the spawnpoints are clustered hardly matters because, naturally, each cluster's centroid moves a little as more and more spawnpoints are added to it. To test it, run `random.shuffle(spawnpoints)` before the algorithm starts and you'll the difference in compression between all the different orders will never be higher than 2% with real-world data.

**Comment by shadi1989** [comment]
There's an issue with the compression calculation.
72.89% is kept, not compressed. 27.11% is removed so only 27.11% compression.
If it was 72.89% compressen you would keep a lot less spawnpoints.

https://images-2.discordapp.net/.eJwFwdENhCAMANBdGIDWckh1G4IEjUoJ1Phxud3vva95-mVWs6u2sQJsx0jSNztUeizZFpFy5diOYZPcEFVj2u9cdQDhxzkOc1gIg-fAHogI2TFPC6Kb0BPDU88qb7WtFvP7Awf2It0.SU_wQHswbP4XuCdUjXAbW7po9XM.png

**Comment by averylarry** [comment]
Depends on your interpretation.  It is compressed to 72.89% of it's original size.  I don't think it's wrong, but it could be misunderstood.  I would, though, suggest changing the wording and reversing the number so a bigger percentage=better compression.  Something like "removed 25% by compression" or "compressed to 45% fewer scan points".

**Comment by gabrielsoldani** [comment]
I was using the 'compression ratio' that shows when you're using software
like 7-zip and WinRAR, which is what I assume most people are familiar
with. I agree that it could be reworded to avoid confusion, though.

**Comment by jchristi** [comment]
With this option, because its creating a clustered spawn point file to be used as input for pogom, that means that if you want to view spawn points on the map, it will actually show cluster points instead?

**Comment by averylarry** [comment]
No.  Spawnpoints on the map are not affected.  The generated file is a list of scanning locations instead of spawnpoints.  The only gui representation is looking at scanned locations.

**Comment by justsomedudeonthenet** [comment]
I have been using this extensively and it works great.

**Comment by Obihoernchen** [comment]
I get some strange error after some time. I added some debug:

```
spawnpoint_id: 47a8523879f
spawnpoint_position: (52.56669878525873, 13.385848618759656)
cluster_centeroid: (52.49566257972049, 13.422290675560475)
lat1: 0.917461970707  lat2: 0.916222155032  lon1: 0.233627131571  lon2: 0.234263165448
spawnpoint_id: 47a8523879f
spawnpoint_position: (52.56669878525873, 13.385848618759656)
cluster_centeroid: (52.50582956386427, 13.460281795661672)
lat1: 0.917461970707  lat2: 0.91639960238  lon1: 0.233627131571  lon2: 0.234926235581
spawnpoint_id: 47a8523879f
spawnpoint_position: (52.56669878525873, 13.385848618759656)
cluster_centeroid: (52.5666987852587, 13.3858486187597)
lat1: 0.917461970707  lat2: 0.917461970707  lon1: 0.233627131571  lon2: 0.233627131571
Traceback (most recent call last):
  File "cluster.py", line 200, in <module>
    main(args)
  File "cluster.py", line 138, in main
    clusters = cluster(spawnpoints, radius, time_threshold)
  File "cluster.py", line 109, in cluster
    c = min(clusters, key=lambda x: cost(p, x, time_threshold))
  File "cluster.py", line 109, in <lambda>
    c = min(clusters, key=lambda x: cost(p, x, time_threshold))
  File "cluster.py", line 74, in cost
    distance = utils.distance(spawnpoint.position, cluster.centroid)
  File "/home/obi/PokemonGo/PokemonGo-Map/Tools/Spawnpoint-Clustering/utils.py", line 14, in distance
    return acos(sin(lat1)*sin(lat2) + cos(lat1)*cos(lat2) * cos(lon2-lon1)) * R
ValueError: math domain error
```
Problem is `(sin(lat1)*sin(lat2) + cos(lat1)*cos(lat2) * cos(lon2-lon1)` is > 1
So acos(>1) fails.

Any idea why?

**Comment by Imoq** [comment]
I got 3 dumps made correctly but found an issue on the 4th:

```
root@raspberrypi:~/PokemonGo-Map/spawns# python cluster.py borely-spawns.json -os borely-spawns-compressed.json -r 70 -t 180
Processing 348 spawnpoints...
Completed in 0.83 seconds.
145 clusters found.
41.67% compression achieved.
root@raspberrypi:~/PokemonGo-Map/spawns# python cluster.py perier-spawns.json -os perier-spawns-compressed.json -r 70 -t 180
Processing 486 spawnpoints...
Completed in 1.97 seconds.
192 clusters found.
39.51% compression achieved.
root@raspberrypi:~/PokemonGo-Map/spawns# python cluster.py prefecture-spawns.json -os prefecture-spawns-compressed.json -r 70 -t 180
Processing 376 spawnpoints...
Completed in 1.20 seconds.
144 clusters found.
38.30% compression achieved.
root@raspberrypi:~/PokemonGo-Map/spawns# python cluster.py vieuxport-spawns.json -os vieuxport-spawns-compressed.json -r 70 -t 180
Processing 526 spawnpoints...
Traceback (most recent call last):
  File "cluster.py", line 197, in <module>
    main(args)
  File "cluster.py", line 135, in main
    clusters = cluster(spawnpoints, radius, time_threshold)
  File "cluster.py", line 106, in cluster
    c = min(clusters, key=lambda x: cost(p, x, time_threshold))
  File "cluster.py", line 106, in <lambda>
    c = min(clusters, key=lambda x: cost(p, x, time_threshold))
  File "cluster.py", line 71, in cost
    distance = utils.distance(spawnpoint.position, cluster.centroid)
  File "/root/PokemonGo-Map/spawns/utils.py", line 14, in distance
    return acos(sin(lat1)*sin(lat2) + cos(lat1)*cos(lat2) * cos(lon2-lon1)) * R
ValueError: math domain error
root@raspberrypi:~/PokemonGo-Map/spawns#
```

**Comment by Obihoernchen** [comment]
It's the very same error

**Comment by Obihoernchen** [comment]
It looks like `sin(lat1)*sin(lat2) + cos(lat1)*cos(lat2) * cos(lon2-lon1)` is greater than 1 sometimes. And acos for more than 1 doesn't work.

If I change the code like this (just a ugly fix which is probably not correct) it works without a failure:
```diff
diff --git a/Tools/Spawnpoint-Clustering/utils.py b/Tools/Spawnpoint-Clustering/utils.py
index a2af21b..a064c61 100644
--- a/Tools/Spawnpoint-Clustering/utils.py
+++ b/Tools/Spawnpoint-Clustering/utils.py
@@ -10,8 +10,12 @@ def distance(pos1, pos2):
     lon1 = radians(pos1[1])
     lat2 = radians(pos2[0])
     lon2 = radians(pos2[1])
+    #print ("acos(sin("+str(lat1)+")*sin("+str(lat2)+") + cos("+str(lat1)+")*cos("+str(lat2)+") * cos("+str(lon2)+"-"+str(lon1)+")) * "+str(R))
+    step=sin(lat1)*sin(lat2) + cos(lat1)*cos(lat2) * cos(lon2-lon1)
+    if step > 1:
+        return 0.0
+    return acos(step) * R

-    return acos(sin(lat1)*sin(lat2) + cos(lat1)*cos(lat2) * cos(lon2-lon1)) * R

 def intermediate_point(pos1, pos2, f):
     if pos1 == pos2:
@@ -22,8 +26,12 @@ def intermediate_point(pos1, pos2, f):
     lat2 = radians(pos2[0])
     lon2 = radians(pos2[1])

-    delta = acos(sin(lat1)*sin(lat2) + cos(lat1)*cos(lat2) * cos(lon2-lon1))
-
+    step=sin(lat1)*sin(lat2) + cos(lat1)*cos(lat2) * cos(lon2-lon1)
+    if step <= 1:
+        delta = acos(step)
+    else:
+        delta = 0
+
     if delta == 0: # too close
         return pos1 if f < 0.5 else pos2
```

**Comment by gabrielsoldani** [comment]
I suspect it's calling acos(1.000000000000187) or something similar because of floating point precision. Can anyone confirm this is the case?

@Obihoernchen since you can reproduce this issue, can you please print `step` when it's greater than `1` to see if that's the case?

**Comment by Obihoernchen** [comment]
@gabrielsoldani okay that's very interesting I added print step and also print lat1,2 lon1,2.
`step` is printed 1.0 ?! I don't get that because than it shouldn't go to this if/else case but ok xD

What's interesting is that every time `lat1 == lat2 and lon1 == lon2` there is this issue (see below).
It's printing `step` and `lat1 lat2 lon1 lon2` for `distance` and `intermediate_point` function if step > 1.
```
$ python cluster.py -os spawnpoints.clustered.json spawnpoints.json -r 70 -t 840
Processing 18986 spawnpoints...
1.0
1.0
0.917461970707 0.917461970707 0.233627131571 0.233627131571
1.0
1.0
0.917461970707 0.917461970707 0.233627131571 0.233627131571
1.0
1.0
1.0
0.916738666026 0.916738666026 0.233771025827 0.233771025827
1.0
1.0
0.916738666026 0.916738666026 0.233771025827 0.233771025827
1.0
1.0
1.0
0.917402372657 0.917402372657 0.236833507926 0.236833507926
1.0
1.0
0.917402372657 0.917402372657 0.236833507926 0.236833507926
1.0
1.0
1.0
1.0
Completed in 531.63 seconds.
8961 clusters found.
47.20% compression achieved.
```

Maybe we should just do `if step > 1: step = 1.0`?

**Comment by gabrielsoldani** [comment]
@Obihoernchen Likely because pos1 and pos2 are different, but they become equal after the conversion to radians. Thanks for your output. See if https://github.com/gabrielsoldani/PokemonGo-Map/commit/691e016e1f8fc25521a23fc65d395c07f28acfa9 fixes it.


Btw, GitHub experts, do I need to make a separate PR for this?

**Comment by Obihoernchen** [comment]
works fine now thank you 👍

**Comment by jchristi** [comment]
@gabrielsoldani yes, your branch was merged at point of a previous commit. You should submit a new PR, but you can still use the same source branch since its now at a later commit.

**Comment by thatsweater** [comment]
I believe the convention for "percentage compression" is backwards, or at least per what you would expect. I ran a series of compressions, dumping to different files, and the general trend i see here is as follows,

10 seconds:
> Processing 10732 spawnpoints...
Completed in 158.51 seconds.
6175 clusters found.
57.54% compression achieved.

20 seconds:
>Processing 10732 spawnpoints...
Completed in 152.25 seconds.
5656 clusters found.
52.70% compression achieved.

30 seconds:
>Processing 10732 spawnpoints...
Completed in 146.03 seconds.
5334 clusters found.
49.70% compression achieved.

As you can see, even though for 30 seconds there are less clusters as you would expect, it states that a lesser compression was achieved than when running 10 seconds, which is counterintuitive. I would think it would follow 1-(current compression percentage).

**Comment by Gallifery** [comment]
Both the spawnpoint and this cluster technique make the scan points scattered. Current direction of improvement has been trying to maxize the size of area each worker can cover per unit time. However, after applying this technique, I believe the 'teleport' effect becomes a concern and I think it's time to review the problem. So, the fundamental benefit from the spawnpoint scan and this technique is that the number of API calls are reduced to cover a same area, meaning with the same number of accounts, you can scan a larger area. The drawback is that each worker will behave like teleporting from one point to another. Meanwhile, probably for most users, the area to scan is not very big. I guess most of the users just want to scan their neighbourhood or something up to 10 km^2. And for that, the combination of these 2 techniques can assure maybe 15 accouts is enough. Instead of an even larger area, I think it is more meaningful to make the scan behave more like regular player. So, for example, if the user has 5 additional accounts but it is not useful for him to scan a larger area, it makes more sense if he can feed the program with 20 accounts while the program can intelligent assign the search task to each of the 20 worker. By that, I mean techniqeus like each worker should be limited to an area locally and if it has finished scanning that area, it standby at that area as if an player is standing still and wait for new scan requests assigned by the program. Furthermore, also to avoid the teleport problem, the pgogram should be able to calculate a route of the worker to walk/run from one point to another. Of course, this would be slower than teleport, but it would behave more like human. The general idea is to add some redundant account so that each worker can be configured not to work in an aggressive way.

**Comment by gabrielsoldani** [comment]
@Gallifery Defining the order in which spawnpoints get scanned to minimize
teleports is out of the scope of this commit. This is just a single
component of something bigger which could handle the issues you mentioned:

1. Compress the spawnpoints to find the minimum acceptable amount of scan
locations (this algorithm).
2. Partition the compressed spawnpoints in k groups based on their location
so you can assign each group to one of your k workers (k-means clustering).
3. For each of the k groups, calculate the optimal path that visits every
spawnpoint at the appropriate time with the least possible distance walked
(traveling salesmen problem with time windows).

**Comment by averylarry** [comment]
Current improvements are not trying to maximize the area that a worker can cover per unit of time.  It is about getting spawn information as quickly as possible while minimizing account bans.
Teleport has always always been a concern (beehive scanning path changed to a circuit, default scan delay).  This compression helps.  There are numerous other PR's that address additional aspects.  Off the top of my head in increasing complexity: speed limit, clustering (where a given account stays in a certain area instead of flying all over the total scan area), and traveling salesman.

**Comment by neutron666** [comment]
What is this doing ? Is there any documentation about it how to use it right ? All i see is, it's decreasing the number of spawn points i already scanned...how to use it ?!

**Comment by averylarry** [comment]
@neutron666 It's in the tools\spawnpoint-clustering folder.  cluster.py runs it -- and there's a readme.

**Pull request merged**
