### PR TITLE
Turn scanned_id into a PrimaryKeyField

### PR DESCRIPTION
**Pull request by invisiblek**
This is a much smaller field than concatenating the lat and long into a character field and using that for an id.

### CODE REVIEW

**Comment by invisiblek** [comment]
This is going to cause people to have to dump their database (or at the very least their ScannedLocation table).

**Comment by chuyskywalker** [comment]
This is a breaking change; people can't upgrade their way through it blindly.

We don't have an `upgrading.md` for this kind of stuff :/

**Comment by invisiblek** [comment]
Yea, I know. I'll think of something.

**Comment by invisiblek** [comment]
K, this is looking pretty good now.

FWIW: I want to merge this separately: https://github.com/PokemonGoMap/PokemonGo-Map/pull/388

Having the commit that actually makes use of the migration stuff will be handy for others to know how this should work.

**Pull request merged**
