### PR TITLE
Move spawnpoints to seperate table for easier access

### PR DESCRIPTION
**Pull request by Darkknightz**
## Description

```
Move spawnpoints to seperate table for easier/faster access
```
## Motivation and Context

Generating spawnpoints from pokemon table everytime is very CPU consuming

Also fixes an issue that was introduced in #1303, sending only new spawnpoints would miss the ability to determine if the spawnpoint is "special" (multiple spawn times) or not.
## How Has This Been Tested?

Tested locally with -mock
## Screenshots (if appropriate):

The following is using a relatively small db. 498997 Pokes, 3727 spawnpoints.

On CPU I now barely see MySQL use anything when using map to generate spawnpoints vs full usage on old map.

before:
capture2

after:
capture

First startup generates the spawnpoints (and is updated when pokes are upserted)
capture
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Ashex** [comment]
You meant separate table, right?

**Comment by Darkknightz** [comment]
Yea lol

**Comment by Salamek** [comment]
Yea, pulling spawnpoints from table with 3,000,000> pokemons was just "sick" +1 pls merge ASAP

**Comment by Darkknightz** [comment]
Also fixes an issue that was introduced in #1303, sending only new spawnpoints would miss the ability to determine if the spawnpoint is "special" (multiple spawn times) or not.

**Comment by Darkknightz** [comment]
Realize made a small error regarding 'appear_time'. Will have fix tomorrow.

**Comment by kbtbc** [comment]
@Drakknightz -- this is great!  ... don't know how ambitious you might be, but take a look at some of these related requests: https://github.com/PokemonGoMap/PokemonGo-Map/issues/1472

**Comment by Darkknightz** [comment]
Had to roll back some changes i did regarding spawntime, should now have same response as before.


@kbtbc that's more of a front end thing, not for this PR. If I see a somewhat easy solution I might try a separate PR

**Comment by Ashex** [comment]
Can we get some people to test this PR before it is merged in?

**Comment by Darkknightz** [comment]
I've compared the responses old vs this and I get the same data in one fourth of the time, and practically no CPU usage on MySQL.

I am curious if others find the same, or even better improvements.

**Comment by kbtbc** [comment]
I copied my db and pulled this request to help test:  Upon launch I get this error:  `2016-10-14 07:06:04,589 [      MainThread][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "C:\temp\pokemongo\Map\PokemonGo-Map-spawnpoints\runserver.py", line 303, in <module>
    main()
  File "C:\temp\pokemongo\Map\PokemonGo-Map-spawnpoints\runserver.py", line 277, in main
    spawns = Pokemon.get_spawnpoints(None, None, None, None, spawntbl=True)
  File "C:\temp\pokemongo\Map\PokemonGo-Map-spawnpoints\pogom\models.py", line 396, in get_spawnpoints
    spawnpoints[sp['spawnpoint_id'] + str(sp['time'])] = sp
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
`

**Comment by Darkknightz** [comment]
@kbtbc Does this help?

**Comment by kbtbc** [comment]
Yes, gets past the error... I will edit & update more in a few

**Comment by Darkknightz** [comment]
If we can get this merged I am working on a follow up PR for #1472

**Comment by Salamek** [comment]
ehm... ping

**Comment by M4d40** [comment]
Is there any Reason this is not merged yet?

**Comment by simonbuehler** [comment]
would be great if it was merged pls

**Comment by Mr-Groch** [comment]
I'm getting lots of exceptions, I have disabled cautching all exceptions in main worker thread and got this traceback:

```
2016-11-14 15:51:23,296 [ search-worker-3][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "runserver.py", line 75, in run
      run_old(*args, **kwargs)
	    File "/opt/lib/python2.7/threading.py", line 754, in run
		    self.__target(*self.__args, **self.__kwargs)
			  File "/volume1/homes/groch/PokemonGo-Map/pogom/search.py", line 578, in search_worker_thread
			      parsed = parse_map(args, response_dict, step_location, dbq, whq, api)
				    File "/volume1/homes/groch/PokemonGo-Map/pogom/models.py", line 878, in parse_map
					    spawnpointids = [(p['spawnpoint_id']) for p in encountered_pokemon]
						TypeError: tuple indices must be integers, not str

```

**Comment by Darkknightz** [comment]
The Dev team is currently looking into a big overhaul of the database as a whole. That plus the recent changes in the spawnpoints this becomes obsolete. Pokémon currently don't show the right despawntime so it has become harder to deduct the new spawnpoints from the Pokémon.

For know I'm closing this. 

Once folks have figured out despawntime, I might redo the PR. If the database refractor isn't done yet..

**Pull request closed without merging**
