### PR TITLE
2captcha balance checking

### PR DESCRIPTION
**Pull request by birdstream**
## Description

Pause scanning in case 2captcha balance reaches under limit

## Motivation and Context

Last morning i woke up to realize that my 2captcha balance was zero and so all of my accounts had been been captcha'd. Not nice. This PR aims to take care of that, and automagically suspend scannnig to avoid this scenario. Thought this should be in there...

## How Has This Been Tested?

On my own map

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by trew** [comment]
Do you really need to check every 30 seconds? Imo that should be configurable.

**Comment by m3g4mInD** [comment]
@trew  change for the value you whant  "time.sleep(1500)"

**Comment by birdstream** [comment]
Added 2Captcha wallet balance to ps output. I know i should not be using globals but i just couldn't figure out how to avoid that. If anyone would like to give directions on how to do that, it'd be appreceated! I still have a lot to learn. However, using globals in this case should not be harmful since only one thread modifies balance...

**Comment by birdstream** [comment]
I'll make a fix when i get back from work.

**Comment by birdstream** [comment]
Rebased #1726

**Pull request closed without merging**
