### PR TITLE
Experimental spawn-point clustering

### PR DESCRIPTION
**Pull request by TBTerra**
### I'm currently absent from this project due to focussing on my masters degree, by all means use this code for development
# Original post
Using k++ means clustering to break the big spawn list into a small list covering a small area for each worker. does not eliminate teleporting (needs a simple speed limiter for that) but limits the distance teleported to within the cluster

## Description
Instead of loading the list of spawns and then adding them to a queue shared between all workers (where a worker may be tasked with teleporting across the entire scan area), instead the list of spawns is clustered with each worker handling the entire of one cluster, this means that the worker will only ever have to travel across the cluster (in a city with a cluster of 100spawns, the cluster size is less than 1km)

## Motivation and Context
This is one step towards tackling the issue of accounts being banned for teleporting across the map, it achieves this without having to add excessive delays that a usual speed limiter may have to as well

When  combined with a simple speed limiter it should both minimize teleport bans, whilst keeping a high spawns to workers ratio

## How Has This Been Tested?
The clustering algorithm has been tested on datasets of up to 10k spawns, and the full implementation is being tested by various members of the community

## Screenshots (if appropriate):
example clustering of 5800 spawns split into 60 clusters (note that there are only 18 colors so some clusters are only differentiated by their letter)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

this code is not compatible with pr 901

### CODE REVIEW

**Comment by Infernoman** [comment]
love you babe <3 glad to see you ALMOST back lol

**Comment by presidenten** [comment]
Do the clustering handle areas that are separated by some space? Like two sides of a lake or if you have points of two towns?

**Comment by presidenten** [comment]
Also, would it be possible to cluster first, and then run this as search algorithm #787 ?

**Comment by presidenten** [comment]
I only get one cluster with 10000+ spawns. Am I missing something?

**Comment by justinkwaugh** [comment]
Yes, this plus #787 would be pretty ideal

**Comment by justj0sh** [comment]
Can someone please make an updated branch of this

**Comment by primaxius** [comment]
Closed as not compatible with current code base. Please resubmit if re-written to be compliant.

**Comment by thatsweater** [comment]
i pray

**Pull request closed without merging**
