### PR TITLE
Fix notifications from crashing page on Chrome for Android

### PR DESCRIPTION
**Pull request by Studio-XP**
Repull of #623

## Description
Fixes notifications from crashing the page on Android. I'm an ass, so I didn't realize that I shouldn't make pull requests on default branch on my forked version :/ Proper pull request for #461

## Motivation and Context
With notifications enabled while viewing on your phone, the page would crash, not showing any new Pokemon #338 #418. This commit prevents the page from crashing, while enabling mobile users to receive push notifications on their phone.

## How Has This Been Tested?
On both Chrome and Firefox for both desktop and Android.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by FabianSperrle** [comment]
Breaks the map for me. Whenever clicking an icon (Pokemon, Gym, ...) the info window does not open, but the map moves to the upper left instead.

**Comment by Studio-XP** [comment]
I don't see why this would produce those errors.  This doesn't touch anything with the info windows.

**Comment by mew905** [comment]
Breaks my map as well. Works excellent on Android Firefox and Desktop Chrome, but Galaxy S6 default browser and Android Chrome browser have issues with it. Specifically these changes stop the pokemon from updating. No notification is ever sent, and the pokemon with the notification setting turned on no longer scale with the map like the others do, they stay the same size no matter how far/close you zoom. Timer on other pokemon counts down (I can still open info window), but after expiring they stay on the page, and no new pokemon ever appear. My site has SSL. Have not tested on iOS but I imagine it doesn't work there to begin with anyway.

Remedy for the issue is to block notifications in browser site settings and refresh the page. Again, works just fine in Android Firefox.

**Comment by Studio-XP** [comment]
@mew905, did you run npm build after importing this pr? What you're describing is the current bug without the fix, that's why I'm asking.

@FabianSperrle, do you have any other prs pulled into your map?

You guys can contact me in discord if you'd like some 1 on 1 support

-xP

**Comment by mew905** [comment]
yes, before merging this PR chrome simply didnt respond to the notifications. It didn't send any, but it also didn't lock up, seemingly ignoring it. After adding this (I noticed the code looked a lot like service Workers, which is what I was looking for at the time) the chrome page essentially died altogether whenever a notification was issued, with the above symptoms. Works perfectly fine on android Firefox, as well as desktop browsers.

**Comment by Studio-XP** [comment]
I'll mess with it if/once they reverse engineer the new api

**Pull request closed without merging**
