### PR TITLE
Fix misaligned hex

### PR DESCRIPTION
**Pull request by Scyntrus**
If coordinates were provided for the location, override the longitude and latitude value returned from the API. (keep the altitude)

## Motivation and Context

Hexes were misaligned again.

## How Has This Been Tested?

Tested on own server.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by chuyskywalker** [comment]
uhhhhh https://github.com/Scyntrus/PokemonGo-Map/blob/8e764e02df8a01878373be6aaaef2c60167bc6f3/runserver.py#L91 ?

**Comment by Scyntrus** [comment]
Looks like I'm sort of blind. Anyways I changed the original regex.

**Comment by Scyntrus** [comment]
Ok something else is wrong.

**Comment by Scyntrus** [comment]
Yeah, someone else already fixed the bug. When I created the commit that regex wasn't there yet. It got in after I rebased my commit.

**Comment by chuyskywalker** [comment]
That was me, sorry bout it :D

**Pull request closed without merging**
