### PR TITLE
Add lured pokemon

### PR DESCRIPTION
**Pull request by Zoruk**
## Description

The problem here is that lure_info field is only present when the scan is close enough to the pokestop this way if we store those info in the pokestop database as soon an other scan find the pokestop but is too far from the stop to get the lure_info field it will erase the lured pokemon from the database

So we have two possibility:

1. Store the lured pokemon in the pokemon table like I did here but with a fake spawnpoint id 
2. Add a new table for lured pokemon

## Motivation and Context

Since last api change the lured pokemon arent displayed 
FIX https://github.com/PokemonGoMap/PokemonGo-Map/issues/715

## How Has This Been Tested?

Tested on my own server

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Becold** [comment]
`'spawnpoint_id': 'lure',`

Can you add the pokestop id in there but keep the difference between pokemon and lured_pokemon ?
Or create an other table with only lured_pokemons.

That would be cool to display which pokemons has been spawned at eatch pokestop.

**Comment by j16sdiz** [comment]
.. and we need webhook for that too.

**Comment by Zoruk** [comment]
Now it use it's own table

I'm not really familiar with python OO, is there any other way to access parent class from static method ?
https://github.com/Zoruk/PokemonGo-Map/blob/063242e9c006d3fa9e42b1cd98b505d958760048/pogom/models.py#L82
https://github.com/Zoruk/PokemonGo-Map/blob/063242e9c006d3fa9e42b1cd98b505d958760048/pogom/models.py#L155

**Comment by Zentriert** [comment]
Can't wait for this to be merged, I much appreciate your work Zoruk! Sincere thanks.

The ability to see which Pokemon spawned at which Pokestop would be awesome too .. I swear I recently saw a screenshot of this exactly (a pop up box showing which Pokemon had spawned at that Pokestop when it was clicked on) and maybe it would even help you .. but sadly I cannot find the link.

**Comment by Becold** [comment]
@Zentriert https://github.com/PokemonGoMap/PokemonGo-Map/pull/669

**Comment by Zoruk** [comment]
Like this :

**Comment by BaIthamel** [comment]
Do not make a fake spawnpoint in pokemondb, that could break the smartscan scrape. If you do have to, make sure we can easily identify them.

**Comment by Zentriert** [comment]
@Becold that's it! I couldn't find it earlier. Looks awesome to me.

@Zoruk, yes that's exactly how it used to be a few days ago before Niantic changed the API (from what I've gathered) and I'd much appreciate having it back! I noticed it missing last night when I was out hunting and I almost missed a few good lured Pokemon like Ryhorn and Dratini.

**Comment by Zoruk** [comment]
@BaIthamel It's now 100% separated from pokemon table. The lured pokemon are stored in a new one (lurepokemon)

@Zentriert Now it's exactly like it was before

**Comment by Zentriert** [comment]
Awesome Zoruk thank you again. Can't wait till it's merged :+1:  :)

**Comment by SkOODaT** [comment]
@Zoruk can you add this into this request

                    if lure_info is not None:
                        d_t = datetime.utcfromtimestamp(lure_info['lure_expires_timestamp_ms'] / 1000)
                        webhook_data = {
                            'encounter_id': b64encode(str(lure_info['encounter_id'])),
                            'pokemon_id': lure_info['active_pokemon_id'],
                            'pokestop_id': f['id'],
                            'latitude': f['latitude'],
                            'longitude': f['longitude'],
                            'disappear_time': calendar.timegm(d_t.timetuple()),
                            'active_fort_modifier': active_fort_modifier
                        }
                        send_to_webhook('pokemon', webhook_data)

i separated it out from the pokestop webhook this one is just for lured pokes

**Comment by Zoruk** [comment]
@SkOODaT Web hook added :+1:

**Comment by Becold** [comment]
@Zoruk @SkOODaT I think it should be `send_to_webhook('lured_pokemon', webhook_data)` to keep the distinction between pokemon and lured_pokemon

**Comment by Zoruk** [comment]
@Becold I think of that but most hook will use both the same way. If they need they can make the distinction with the field pokestop_id only present on lured pokemon

**Comment by SkOODaT** [comment]
yea i would be all for "lured_pokemon" but all the current apps utilizing pokemon webhook alerts use "pokemon"

**Comment by Zerotask** [comment]
How strong does it increase the requests sent to niantic? Last time I implemented such a feature I got instantly an IP ban.

**Comment by Zoruk** [comment]
@Zerotask It's exactly the same number of requests. This just parse more received data.

**Comment by Zoruk** [comment]
I finaly renamed the webhook because some app requires spawnpoint_id that's not aviable in lured pokemon

**Comment by Zerotask** [comment]
It didn't work for me with spawn scanning.

**Comment by j16sdiz** [comment]
Can we bring back the `is_lured` in webhook?

It was there until https://github.com/PokemonGoMap/PokemonGo-Map/commit/530b3c9276a7ff9acea3fff62f13bc7d52876b1a#diff-541e2b217ba4a7d7859dae2cb443b6b7L337

**Comment by SkOODaT** [comment]
@j16sdiz  pretty sure all you do is half to add it back in 'is_lured': True

                if lure_info is not None:
                    d_t = datetime.utcfromtimestamp(lure_info['lure_expires_timestamp_ms'] / 1000)
                    webhook_data = {
                        'encounter_id': b64encode(str(lure_info['encounter_id'])),
                        'pokemon_id': lure_info['active_pokemon_id'],
                        'pokestop_id': f['id'],
                        'latitude': f['latitude'],
                        'longitude': f['longitude'],
                        'disappear_time': calendar.timegm(d_t.timetuple()),
                        'active_fort_modifier': active_fort_modifier
                        'is_lured': True
                    }
                    send_to_webhook('pokemon', webhook_data)

**Comment by Zoruk** [comment]
@Zerotask What diden't work ? Now lured pokemon only appear if you are in range (70m) from the pokestop

@j16sdiz @SkOODaT We can att is_lured field but it wont work with some app like https://github.com/Brideau/pokelyzer which require spawnpoint_id

**Comment by Zoruk** [comment]
It's looks like you have an invalid caracter (é) in the map template file that's is encoded using Windows-1252 and not utf-8

and i checked line 124 is not in the function fullmap in my sources. have you applied others patches and/or edited a template file using a windows text editor ?

**Comment by SkOODaT** [comment]
yea i have and i have no idea where i would find that lmao

**Comment by Zoruk** [comment]
Send me your source folder I'll check just to be 100% sure it didn't come from this PR but i can't reproduce your error

**Comment by SkOODaT** [comment]
how would i do that (whats best way/site) im still pretty new to all this stuff and what exactly do you want the pogom and static folders?

**Comment by Zoruk** [comment]
Just compress the folder and use any site you want, just don't forget to remove config file if you have one with private data like account/password

**Comment by SkOODaT** [comment]
readded your code and yea getting the error again

https://dl.dropboxusercontent.com/u/28008884/PokemonGo-Map-develop.rar

**Comment by Zoruk** [comment]
Ok it's because the `é` on line 59 is encoded in windows like style and not UTF-8 as it is in the git repository.

**Comment by SkOODaT** [comment]
yes thank you fixed lol.... my mistake

**Comment by CosmoRing** [comment]
@Zoruk, can you check to see if this is working when merging with the current develop branch? Was working yesterday but now that you rebased to a more recent commit, when i merge with the current branch it doesn't do anything.

**Comment by Zentriert** [comment]
Maybe I'm an idiot (really new I apologize in advance sir) but I've copied the four new commits RAW and replaced the code in my files, the scanner is working fine and showing Pokestops with correct time left, but no lured pokemon ..  

I'm uncertain if I've done anything wrong because it's scanning with no errors? I really appreciate your time!

**Comment by Zoruk** [comment]
Since the update 0.33.0 you need to be in range to see the lured pokemon (70m) otherwise the field that contain the lure info is not present with the pokestop and lured pokemon stay less then 3 min so if you have a long scan delay you will misss most of them.

**Comment by Made123** [comment]
Work fine. But before the app was able to show lure pokemon all the time. I mean that the scan was not need to scan the lure to display the pokemon in it. Right now, we have to wait the scanning zone pass over the lure to show the pokemon.

**Comment by Zentriert** [comment]
@Zoruk so it's almost useless with -ss? (spawns.json) by default it doesn't even search a spawn point till 60s after spawn ... that's why I'm getting so few lured pokemon. Damn. 

So lured Pokemon are entirely random and we can't even log their spawn points for -ss? So sad. At least I have some of them and I thank you for that.

**Comment by Becold** [comment]
This seems to be an issue with -ss feature (@TBTerra)

**Comment by Zentriert** [comment]
@Becold yes I believe so, [check this post](https://github.com/PokemonGoMap/PokemonGo-Map/issues/743#issuecomment-240200634)

I have made that change from 60s to 10s and will see if it makes any difference, pretty sure it will but I'm unsure if it will get 100% of Lured Pokemon because I don't know if scanSpawn tracked lures (and it only could if they were active at the time of initial scan ..)

**Comment by Asafffff** [comment]
A nooby question, how can I download and add it to my own server? tried finding a download button in files changed / commits without any success...

**Pull request closed without merging**
