### PR TITLE
Added cell id radius to fix most bad scans

### PR DESCRIPTION
**Pull request by Skorfius**
## Description
Speed uses pokestops and gyms to determine bad scans from good scans.
The master branch of pogodev api changed this to 500, so I changed it back to 1000.

This fix wont work for everyone if there was no gyms or pokestops around to begin with.
I was getting too many empty results and this fixed my map and allowed it to go from less than 10% on the initial scan to over 90% in the first hour of running it.

## Motivation and Context
wasted $30 on captchas from pure bad scans in 3 days, it had to be fixed.

## How Has This Been Tested?
My map

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sebastienvercammen** [comment]
Unfortunately this isn't a fix, it's a quick hack to work for some very specific users. Bad scans (which is also not a right term: most cases are good scans but they have nothing to compare to) should still be looked into properly.

**Comment by Obihoernchen** [comment]
But I think we have to set cell id radius to >= 900 for gym scanning (-np).
https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/pogom/schedulers.py#L143

**Comment by bbdoc** [comment]
@sebastienvercammen It could still help on rural zones as speedscan will find pokestops and gyms within 1000m that it didn't find within 500m. I do agree this is no real fix as if the first stop is 1001m away you still end up with a bad scan, but is there any good reason not to adapt to 1000m already ? I had no issues on my map at the time PR1501 was initially released and now my Initial scanned is freezing around 10%, I guess this change from 1000m to 500m on pogodev api is the reason behind it...

**Comment by Obihoernchen** [comment]
@bbdoc the client is requesting 500m, so requesting 1000m all the time could be an alert for niantic.

**Comment by bbdoc** [comment]
would it be possible to make this value cofigurable through command line ? I have an instance where I do need it, even if it means more captchas, but another one where it's not needed, so better stick to 500m. Thanks

**Comment by bbdoc** [comment]
I've been testing that since yesterday. Pretty happy with it. It helped a lot on my gym only scan, got better results on my rural scan, and really didn't notice any increase in my captcha rate, so I guess Niantic isn't monitoring this.

Anyway in my opinion, better solution would be to keep 500m the default but make it a configuration option. Ideally this option should adapt all references to 500m in the code.

**Comment by Obihoernchen** [comment]
I think 1000 for no_pokemon + configurable (for rural areas), otherwise default 500 would be the best solution.

**Comment by MikeShiner** [comment]
I went from 90% bad scans to 0 with this patch. Definitely better than disabling max-failures but not sure if this a necessary fix for the majority of players.

**Comment by sebastienvercammen** [comment]
Closing this PR in favor of continuing discussion of a proper fix in one of the current open PRs (in order of currently preferred approaches): #1662, #1672.

**Pull request closed without merging**
