### PR TITLE
updated example.py

### PR DESCRIPTION
**Pull request by FrostTheFox**
added new elif to example.py
## Description

bang lure?
## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.

elif fuck.lower() == "india":
  print("bang lure?")

### CODE REVIEW

**Comment by FrostTheFox** [comment]
dedicated to @AHAAAAAAA for not readding .landscape.yml so my PR will work :( https://github.com/AHAAAAAAA/PokemonGo-Map/pull/3475

**Comment by FrostTheFox** [comment]
wat

**Comment by AHAAAAAAA** [comment]
I feel like fuck.lower() should be fuck.upper() for better readability.

**Comment by FrostTheFox** [comment]
@AHAAAAAAA make a PR, then ;)

**Pull request merged**
