### PR TITLE
Create a "community tools" page under the "extras" heading.

### PR DESCRIPTION
**Pull request by razorasadsid**
Added a community tools page under the extra's section to gather all the community tools in one place

## Description

It currently has PTCaccountgen, Cor3's map calculator, and Honeyspots 

## Motivation and Context

Sometimes pikabot goes down and also users should be able to find useful tools through the wiki

## How Has This Been Tested?

the page ougta work

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by FrostTheFox** [comment]
+1

**Comment by Damananth** [comment]
+1

**Comment by FrostTheFox** [comment]
Change PTC gen to https://github.com/skvvv/pikapy

**Comment by razorasadsid** [comment]
Aye captain!

**Pull request merged**
