### PR TITLE
Multiply max db connections by number of accounts (threads) used

### PR DESCRIPTION
**Pull request by invisiblek**

### CODE REVIEW

**Comment by BaIthamel** [comment]
try running this with only server, fails because accounts is 0

**Comment by invisiblek** [comment]
rofl, good call

**Comment by Toetje585** [comment]
Confirm fails when you start a server only mode :)

**Comment by invisiblek** [comment]
fixed in latest patch

**Comment by Toetje585** [comment]
Still:

python runserver.py -os -fl -l 'xxxx, xxxx''
2016-08-09 02:29:09,866 [      MainThread][     runserver][    INFO] Parsed location is: 50.8514/5.6910/54.3097 (lat/lng/alt)
2016-08-09 02:29:09,869 [      MainThread][        models][    INFO] Connecting to MySQL database on localhost:3306
Traceback (most recent call last):
  File "runserver.py", line 129, in <module>
    db = init_database(app)
  File "/home/michel/Bureaublad/PokemonGo-Map-develop/pogom/models.py", line 35, in init_database
    if len(args.accounts) > 0:
AttributeError: 'Namespace' object has no attribute 'accounts'

**Comment by invisiblek** [comment]
derp, that should do it

**Comment by Toetje585** [comment]
Fixed, testing now!

**Comment by BaIthamel** [comment]
+0.5 doesn't instantly crash this time

**Comment by Toetje585** [comment]
Now i see this sometimes:


-st 5 -lp 5 -t 4 --accounts accounts.csv


search][   ERROR] Search step 1 map parsing failed, retrying request in 20 seconds
Traceback (most recent call last):
  File "/home/michel/Bureaublad/PokemonGo-Map-develop/pogom/search.py", line 242, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/home/michel/Bureaublad/PokemonGo-Map-develop/pogom/models.py", line 299, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

However using -st 5 -lp 5 -t 3 --accounts accounts.csv

Fixes the problem:)

**Comment by invisiblek** [comment]
not sure how that could be related =/

**Comment by Infernoman** [comment]
not using the --accounts argument myself so this doesnt help me at all. all of my accounts are on the command line still. useless to switch to 50+ account.csv's when i have 1 script controlling everything.

**Comment by invisiblek** [comment]
works fine with command line args, i specified 2 accounts, it did 10 connections

**Comment by Infernoman** [comment]
still not fixing itself for me, even with 100k available database connections

**Comment by Toetje585** [comment]
Keep an eye on ram and cpu, other then that no more database errors only:

Exception while downloading map: list index out of range
2016-08-09 03:31:03,362 [ search_worker_0][        search][   ERROR] Search step 13 area download failed, retrying request in 30

Now and then :)

**Comment by BaIthamel** [comment]
I make this a +1 now been running for longer than usually takes to get the crash

@Toetje585 that looks like a cli for beehive. Whut?

**Comment by Infernoman** [comment]
after finally updating to 100 connections per account, I was able to continue.

**Comment by Toetje585** [comment]
@BaIthamel  cla? or do you mean "cli"?

**Comment by Toetje585** [comment]
@BaIthamel  Yhea it is :+1:

**Comment by Toetje585** [comment]
So back to the topic, @invisiblek fix helped, if you are running lots of workers.
Improvement to connection to the database for me so :+1:

**Comment by billbo99** [comment]
I may not be fully understanding this .. but in a beehive setup there are multiple worker processes all trying to update the database.   

Does the max_connections apply to db sessions available to the individual worker ?
Or does each worker override the max_connections setting on the MySQL server ?

I am running a hive with 37x workers each with 7x accounts .. I should ideally have 1295 (37 x 7 x 5) sessions available on the DB server.

**Pull request merged**
