### PR TITLE
Provide Historical Spawn data for a region defined by the current viewed area

### PR DESCRIPTION
**Pull request by snapper67**
## Description
For issue: [Feature Request] Spawnpoint analysis #538
All spawn history for all spawnpoints in the viewable area are aggregated and a percentage of appearance is calculated.

## Motivation and Context
Gives the ability to zoom into an area and see stats on all the spawns of each type.
## How Has This Been Tested?
Tested Locally. Opening history closes stats and vice versa. Request for data is made when drawer is opened

## Screenshots (if appropriate):
screen shot 2016-08-12 at 5 05 30 pm

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

…wing area

### CODE REVIEW

**Comment by FlarumHostingCo** [comment]
I don't have a file named .eslintrc.json

**Comment by snapper67** [comment]
It is part of the project
https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/.eslintrc.json

**Comment by nolageek** [comment]
Or how about a drop down on the stats page that lets you select different Locations that have been scanned? For example I have a region near work and a region near home but the 'stats' screen has them all aggregated into one list. Would be nice to be able to select from the different locations that are being scanned and just show those.

**Comment by justsomedudeonthenet** [comment]
Closing because it has merge conflicts and hasn't been updated in 25 days.  If this is still an issue feel free to resubmit an updated PR.

**Pull request closed without merging**
