### PR TITLE
Add relative color and info window with time to spawn point markers

### PR DESCRIPTION
**Pull request by beccasafan**
## Description

- Adds an InfoWindow to the SpawnPoint circles that provides the mm:ss the spawn will occur. Includes a note if the spawn is not a regular 15m spawn as these are handled a bit oddly by the map. Data is included as part of the spawnpoint query driven by the Spawn Points marker settings.
- Varies the colors of the spawn circle based on its spawn time relative to the current time:
  - Default color is purple
  - At 5 minutes, spawn circles turn light blue and becomes darker until the spawn time
  - At spawn time, spawn circles turn green and change to red over the course of the active spawn

## Motivation and Context

Spawn point timing is already collected and stored, and becoming more important with Spawn Point Scanning. Surfacing this data makes it easier to keep an eye on your scans and also clues you in to when you might want to head to a location.

The colors give you an idea of what areas you might want to head to maximize the spawns you'll see. This would also enable people to run only the server and use only the spawn time information, without running search workers to show which 'mon are spawning.

## How Has This Been Tested?

Ran against both MariaDB and SQLite. Viewed spawn points with a single time (regular 15m spawn) and also multiple times (30/45m spawns).

## Screenshots (if appropriate):
image
(screenshot taken at :42)

image
(screenshot taken at :44)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Ardarel** [comment]
Thanks! That's exactly what I wanted.

**Comment by DiscoTim** [comment]
is it possible to add distance? or maybe that isn't wanted?

function i'm using for distance:

```
function getPokemonDistance (item) {
  if (!(locationMarker)) {
    return 0
  }
  return parseInt(google.maps.geometry.spherical.computeDistanceBetween(locationMarker.getPosition(), new google.maps.LatLng(item.latitude, item.longitude)))
}
```

**Comment by justsomedudeonthenet** [comment]
I like it.

**Comment by Ardarel** [comment]
What about switch to show only "spawned" spawns. It would be possible to track nearby pokemons without runing scanner relative easy.

**Comment by beccasafan** [comment]
@DiscoTim Personally, not sure about adding location. Having the map location marker and the spawn marker gives you a visual for the distance. Not sure I'm seeing much value from it, but open to it if people do think it'd be useful.

On discord it was suggested to add colors to the spawn points based on the spawn time. Purple by default, light blue changing to dark blue as a spawn time approaches, then the green changing to red as a spawn expires. I like that so I plan to add that.

@Ardarel those spawn colors would get a bit of the way to what you're going for I think, but remember a spawn point only tells us the *when* and not the *what*. If mapping gets broken in the future, then those who have a history already stored could continue and introducing the UI toggle you propose could be very useful.

**Comment by ottowayne** [comment]
Very useful, I'd like this addition

>  On discord it was suggested to add colors to the spawn points based on the spawn time. Purple by default, light blue changing to dark blue as a spawn time approaches, then the green changing to red as a spawn expires. I like that so I plan to add that.

I fear that this will mix up the colors with other markers and would make this optional if added.

Also I already thought about adding spawnpoint times but also wanted to add an history of Pokemon for the selected spawn to see what pokemons frequently appear on that spot. Might add this myself if this gets merged.

**Comment by TheNewDarkOne** [comment]
I have a feeling this will be future when mappers are broken, at least for the short term until the wise people update unknowns and find a way to defeat captcha. Then it'll be who finds a way to map out an ideal "walking route" or "driving route" so you path through areas at good times. Basically where to be and when with the most popping at x times that have a good history of better pokemon. Generally speaking better pokemon tend to stick to certain spots too so such a thing would need to remember that.

**Comment by btctx** [comment]
I really like this idea. I have it running on my system with just a few workers, but it allows me to share my info with a few friends without them needing to move the search location. You can use the spawn colors to get a quick glance of likely spawn points for anything showing up in the actual app.

**Comment by rrbailey89** [comment]
I try clicking on my spawn points and I see nothing pop up at all.

**Comment by beccasafan** [comment]
@rrbailey89 can you pop in the discord chat? it'll be easier to help you there!

**Comment by hagehg** [comment]
Some "might appear as early as"-values have negative seconds for me:

```
Spawn Point
Every hour from 00:57 to 15:57
May appear as early as 30:-3
```


The irregular disappear times from my db for this spawnpoint are
```
"disappear_time"
"2016-08-30 14:05:02"
"2016-08-29 11:03:51"
"2016-08-23 00:04:51"
"2016-08-22 18:11:36"
"2016-08-22 13:03:51"
"2016-08-20 08:10:35"
"2016-08-19 23:01:02"
"2016-08-14 00:01:51"
"2016-07-18 21:53:35"
```

**Comment by beccasafan** [comment]
@hagehg can you pop in the discord chat? it'll be easier to help you there!

**Comment by ottowayne** [comment]
Works fine for me. Just had to clear my Chrome cache (STRG+F5) # :+1:

**Comment by malopetrov** [comment]
i had a problem with flickering info window on mouseover when pointer in upper half of the circle.
solved it by moving the position of the info window above circle (instead of center):



    content: spawnpointLabel(item),
    disableAutoPan: true,
    position: {
      lat: item['latitude'] + 0.00001 * 5,// * n - radius of the circle
      lng: item['longitude']
    }

**Pull request merged**
