### PR TITLE
On Demand Mode

### PR DESCRIPTION
**Pull request by KyleBoyer**
## Description
I made changes to a few files, to track when the last web request was(heartbeat). This then has a timeout that will stop the bot from scanning if there is no activity in a certain period of time, configured by "-odt" or "--on-demand_timeout". Thus, "--on-demand_timeout 900" will activate this mode, and set the timeout to 15 minutes. One thing to note, is that the timeout is in seconds. Finally, the scanner will also startup in standby mode(waiting to start) until the first client connects.

## Motivation and Context
Solves https://github.com/PokemonGoMap/PokemonGo-Map/issues/1142 and https://github.com/PokemonGoMap/PokemonGo-Map/issues/1132

## How Has This Been Tested?
Tested locally and on my server, by connecting and disconnecting, turning off and on on demand

## Screenshots (if appropriate):
N/A
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tiagomartines11** [comment]
I like the idea! It puts us closer to the path I saw on #1108, so that multiple users can "demand" certain areas to be active. We could dynamically allocate accounts and what not :)

**Comment by kiraacorsac** [comment]
I hope this will get merged in upstream, I really carve this feature.

**Comment by joeubi** [comment]
Great idea.

**Comment by kiraacorsac** [comment]
Will the conflicts be resolved? I actually use this feature, however I cannot update to latest version and merge it again now.

**Comment by KyleBoyer** [comment]
Closing and making a new PR with conflicts resolved.

**Pull request closed without merging**
