### PR TITLE
changing requirements.txt to use pogodevorg/pgoapi

### PR DESCRIPTION
**Pull request by rbryson74**
## Description

changed repo on pgoapi from PokemonGo-Map to pgodevorg

## Motivation and Context

will keep us up to date for now with issues fixed on mainline pgoapi master

## How Has This Been Tested?

The repos are essentially identical already with the change made earlier today on our fork.  

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by FrostTheFox** [comment]
I shall take care of this when the fix is fixed and merged to fix the fix on the fix of the pgoapi fix

**Comment by FrostTheFox** [comment]
idk anymore i just got home so i was bored and i wrote that

**Comment by rbryson74** [comment]
Just so if anyone that looks at this is curious we are putting this "On-Hold" for now to see what happens with 0.37

**Comment by primaxius** [comment]
Closed due to MinVersion 0.39.0 being forced. Will revise when/if 0.39.0 API released.

**Pull request closed without merging**
