### PR TITLE
Fix basic config example.

### PR DESCRIPTION
**Pull request by NoobDev3**
## Description
basic config example should represent the -l attribute value with double quotes rather than single.

In addition added reminders to make sure you're still in the directory of PokemonGo-Map.

## Motivation and Context
When trying to complete installation and run, additional research required to fully execute.

### CODE REVIEW

**Comment by chuyskywalker** [comment]
Why? Double quotes cause most shells to jump into a form of interpolation which you don't want for a field like this.

**Comment by NoobDev3** [comment]
@chuyskywalker have you tried to run it using single quotes in windows? it doesn't work.

Actually this PR doesn't completely fix it, because the other params need double quotes as well:

-u
-p
-l
-k

**Comment by chuyskywalker** [comment]
omg windows...why you suck so much. Go ahead and change them all.

**Comment by NoobDev3** [comment]
New commit has the changes for all parameters.

**Comment by chuyskywalker** [comment]
LGTM

**Pull request merged**
