### PR TITLE
Add Spawnpoint history sidebar

### PR DESCRIPTION
**Pull request by wobblybobz**
## Description

Added a Sidebar that shows history for the spawn point
## Motivation and Context

New Feature to get more details for a specific spawn point

## How Has This Been Tested?

Tested on my running laptop with large amounts of spawn point data
Clicking on spawn points in map and clicking the View Previous Spawns Link to show sidebar with the history of that spawn point

## Screenshots (if appropriate):

IVs and Moves switch on
screenshot from 2016-10-02 17-14-33

IVs and Moves switch off
screenshot from 2016-10-02 17-14-08
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Cubkyle** [comment]
Seems to work perfectly on my build. Nice addition.
Two nitpicky requests. 
Is it possible to make the sidebar a little larger to get rid of the horizontal scroll?
And can this backward American get an option somewhere to put the month first followed by the date? :)

**Comment by mew905** [comment]
my only request is to make the sidebar dynamic in the sense that I don't scan for IV's and have no plans to, so the ADS/Moveset are just unused space for me. Maybe something like (pseudo below)

if IV['atk'] == !null:
    display IV/moveset table

I'd love to use spawnpoint history otherwise, thank you for this!

**Comment by wobblybobz** [comment]
The columns could be shown / hidden based on the --encounter flag but then if people are running beehive the -os would need to also have --encounter to make these visible, is this a problem for anyone?

**Comment by FlarumHostingCo** [comment]
Sidebar opens for me. but no past info loads.

**Comment by sLoPPydrive** [comment]
There is a bug in `map.js` which makes the stats load **very** slowly for me. In function `showSpawnDetails()` the following lines have to be pulled out of the `each` loop:
```
$('#spawnHistory_table').dataTable().show()
spawnHistoryTable
  .clear()
  .rows.add(spawnHistory)
  .draw()
```
Currently these lines are being executed with each and every spawn (> 1000 in my case) meaning the data table will be redrawn > 1000 times which makes things awfully slow!

**Comment by FlarumHostingCo** [comment]
Nothing loads and inspecting with browser I receive the error in console..

DataTable is not a function TypeError:

**Comment by wobblybobz** [comment]
Still working fine for me, are you trying to merge this with another PR or something
to test this out did you do just the following to test this out?
- git fetch origin pull/1412/head:SpawnpointHistory
- git checkout SpawnpointHistory
- npm run build

then start your server (./runserver.py) with whatever commands you use (Restarting is required because of the changes to the templates/map.html file)

and refresh your browser.

**Comment by sLoPPydrive** [comment]
After some time playing around with this I think an alternative view where Pokémon are grouped by their ID (and their number of occurences of course) would be awesome. I actually don't have a use-case where I need the complete list of past spawns on a spawnpoint but I'd really like to see if a particular spawn produces more Pokémon of a specific species than others.

**Comment by nhumber** [comment]
i cloned wobblybobz branch with all the bells and whistles, i personally only collect IV and stats info for a few pokemon so many many show 0 0 0 0 for stats. could we get either a grouping function like stated above or possible toggle IV stats to off and give us a way sort by amount of spawns and also pokemon ID or something similar or grouping

**Comment by wobblybobz** [comment]
I have taken these into consideration and am currently working on another commit that will add grouping by the pokemon_id and will be expandable to show the extra details like when they appeared and what their stats were

**Comment by sebastienvercammen** [comment]
We're cleaning up some old PRs that have been left around from before we had the time to handle everything properly. With the last few weeks going fantastically well, cleaning up the PR and issue queue will let us move forward again :) If this PR is still valid, don't hesitate to re-open and poke us.

**Pull request closed without merging**
