### PR TITLE
added *.csv,*.bat, *.sh, and *.log to .gitignore

### PR DESCRIPTION
**Pull request by rbryson74**
## Description

adds *.csv, *.bat, *.sh, and *.log to the .gitignore file
forced !ignore for some sh and bat files. 

## Motivation and Context

when using a csv file for accounts the file will show as new or changed in git. we want git to ignore those files. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by justsomedudeonthenet** [comment]
Maybe tell it to ignore .bat and .sh files too?

**Comment by rbryson74** [comment]
well the easy-setup.sh and setup.bat files are included in the repo. would have to do a "not ignore" for those. There might be others as well.

**Comment by justsomedudeonthenet** [comment]
Yeah, definitely specifically keep the ones that are part of the project.  But I assume most of us have startup scripts that git should ignore.

Maybe .log too.

**Comment by rbryson74** [comment]
yeah, there are a couple of sh files in contrib/supervisord and a make.bat in docs. let me see about adding these.

**Comment by justsomedudeonthenet** [comment]
I think you can make it ignore in the root directory but not subdirectories.  I forget how to do it though.

**Comment by rbryson74** [comment]
node_modules is already ignored so I didnt have to worry about the stuff that was in there.

**Comment by rbryson74** [comment]
Why is it changing the chmod for the file too? sigh

**Pull request merged**
