### PR TITLE
Experimental spawn-point clustering

### PR DESCRIPTION
**Pull request by TBTerra**
Using k++ means clustering to break the big spawn list into a small list covering a small area for each worker. does not eliminate teleporting (needs a simple speed limiter for that) but limits the distance teleported to within the cluster

## Description
Instead of loading the list of spawns and then adding them to a queue shared between all workers (where a worker may be tasked with teleporting across the entire scan area), instead the list of spawns is clustered with each worker handling the entire of one cluster, this means that the worker will only ever have to travel across the cluster (in a city with a cluster of 100spawns, the cluster size is less than 1km)

## Motivation and Context
This is one step towards tackling the issue of accounts being banned for teleporting across the map, it achieves this without having to add excessive delays that a usual speed limiter may have to as well

When  combined with a simple speed limiter it should both minimize teleport bans, whilst keeping a high spawns to workers ratio

## How Has This Been Tested?
The clustering algorithm has been tested on datasets of up to 10k spawns, and the full implementation is being tested by various members of the community

## Screenshots (if appropriate):
example clustering of 5800 spawns split into 60 clusters (note that there are only 18 colors so some clusters are only differentiated by their letter)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

this code is not compatible with pr 901

### CODE REVIEW

**Comment by TBTerra** [comment]
as the title suggests this is experimental, it probably has some bugs and is definitely missing useful features. ones to add atm are: simple speed limiter, load pre clustered spawns from file. suggestions are welcome

**Comment by clvv** [comment]
The issue is to figure out exactly what is the banning criteria. Is it speed? Is it distance jumped? or something else entirely ("behaving" like a human player)?

My guess is that there's probably a speed limit and a distance jump limit (i.e. even if you go over speed limit, but jumped distance is small, then there's no penalty). Speed limiting and clustering solves each of the aspect respectively. Now we will just have to see which will result in less bans.

**Comment by Becold** [comment]
Is there any calc to calculate the amounts of accounts per cluster (like beehive setup) or is it using automatically?
And if so, does it use the same accounts per cluster even after a reboot of the server?
> Idea: Maybe we can insert the accounts inside the database like http://feathub.com/PokemonGoMap/PokemonGo-Map/+49

**Comment by Goldvivi1** [comment]
Scanned Locations also needs clustering.

**Comment by mew905** [comment]
looks like it takes your number of workers and splits them up evenly. If this is functional, I'd love to try this

**Comment by TBTerra** [comment]
@Becold the algorithm makes one cluster per account, the tricky bit is working out how many clusters you need, it is also deterministic so if the server is re launched on the same dataset it will return the same clusters in the same order to prevent an account teleporting because its cluster changed

**Comment by TheNewDarkOne** [comment]
Pretty much waiting for this before using -ss again. my accounts survived every ban using a pretty non teleporting beehive but when i switched to -ss they didn't even last 24 hours and every one of them got killed. I watched how it behaved and the teleporting with 6 accounts with a 9 step and over 600 spawn points was pretty bad.

**Comment by Forbes256** [comment]
Is this idea dead? Seems like an incredible improvement.

**Comment by TheNewDarkOne** [comment]
Agreed, and sorely needed. Although I suspect with Niantic stepping up their game now, Terra probably realizes more is needed than this and has gone back to refactoring something better. This is a start but just simply isn't enough. Teleporting needs to be eliminated not just reduced. That's even assuming it gets done in time to reap benefit of it before captcha is enabled, which will set mapping back for a while until the geniuses figure out a way to handle it.

**Comment by TBTerra** [comment]
sorry it got auto closed when i moved the changes to a new 'experemental' branch in my repo, will re-pull shortly

**Pull request closed without merging**
