### PR TITLE
Add captcha listings to status page

### PR DESCRIPTION
**Pull request by gabaod**
## Description

Add a captcha column to status.html with a captcha field in workerstatus table

## Motivation and Context

It helps us figure out which accounts are being captchad and how often

## How Has This Been Tested?

ran for 5 min and captchas appeared 

## Screenshots (if appropriate):
captchasdrf

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by myntath** [comment]
I had to manually update the database adding the column 'captchas' to workerstatus table to get this to work. This should happen automatically.

**Comment by gabaod** [comment]
This is designed to play off the base develop POGO branch, not with any PR added. I tested by creating NEW DB and it creates the column automatically.  IF you have installed a PR its likely it already updated you to db10, thus quick fix is to do what you did, or edit pogom/models.py and at the bottom change > 10  to > 11

**Comment by gabaod** [comment]
ffd

please let me know if you have any issues like this after restarting your scripts. Cant seem to pinpoint what is causing a blank worker name with a creating thread...  that hangs.

**Comment by myntath** [comment]
Thanks, that was the issue with the Database. I was already at v10 from 1530. 

I haven't seen the issue you describe above.

**Comment by SkOODaT** [comment]
works great but i noticed on -ps the "message" line is blank i had to removed "skipped" for it to show again im pretty sure were just past the line character limit works great tho

**Comment by gabaod** [comment]
simple fix SkOODaT.  all updated.

**Comment by SkOODaT** [comment]
you have another error lol 
`status = '{:10} | {:5} | {:' + str(userlen) + '} | {:' + str(proxylen) + '} | {:7} | {:6} | {:5} | {:7} | {:8} | {:10}'`

**Comment by m3g4mInD** [comment]
Hey,well i have install  by develop POGO branch, i chnage the 3 files and i started  the map,but i still dont have the captcha fiel,the field is good on status.js but dont push to status.html like the others fields.I miss anything?thanks

**Comment by badeanda** [comment]
You might want to do npm install and npm run build

**Comment by m3g4mInD** [comment]
@badeanda yeap i miss the npm run build now is work thanks

**Comment by gabaod** [comment]
If you changed the 3 files that says you didnt git fetch this, thus you will need to alter the workerstatus table in sql according to the bottom of the utils.py file

**Comment by m3g4mInD** [comment]
@gabaod  when i have said dont work  it was my fault because i have forgget to "npm run build", after npm run buld  i run the map and work fine in status page shows the captcha fiel .but as you can see the account have 0 finds, and in captcha fiel its says 0= same dont need captcha right?! well its so wrong because i  have see  the logs and dat account its looking for the captch but in status page still 0.The captcha colum in file.pb is creat like normal.
CREATE TABLE "workerstatus" ("username" VARCHAR(50) NOT NULL PRIMARY KEY, "worker_name" VARCHAR(255) NOT NULL, "success" INTEGER NOT NULL, "fail" INTEGER NOT NULL, "no_items" INTEGER NOT NULL, "skip" INTEGER NOT NULL, "captchas" INTEGER NOT NULL, "last_modified" DATETIME NOT NULL, "message" VARCHAR(255) NOT NULL);.....

**Comment by gabaod** [comment]
are you providing a captcha key to have it solved? or just seeing if it triggers and ignoring that its captchad ?

**Comment by m3g4mInD** [comment]
@gabaod i just whant to see if triggers without captcha key,but i have read the code and  works fine with key,but like you know not all people have captcha key.

**Comment by gabaod** [comment]
in search.py.   where it says                     if consecutive_empties >= 2:
                        captcha_url = captcha_request(api)

                        if len(captcha_url) > 1:
                            status['captchas'] += 1
 you could move the status['captchas'] += 1 line above the if len(captcha_url) >1:  line  I think that will give you that ability but havent tested, rather keep it set so you know how many captchas an acct does, as if it doesnt clear the number would never go above 1.

**Comment by m3g4mInD** [comment]
@gabaod  thanks for all ,i gonna try ,because  in some point in 20 accs in 1h i have 4/5 captchas and i whant to know what is the % of captchas in 24h in 20 accs,just for me,then i can make a calcule about increase the accts and the money for solving captchas.

**Comment by boby360** [comment]
@m3g4mInD If you use 2captcha service their website does tell you.

**Comment by badeanda** [comment]
I might try this when the code doesn't conflict with PR 1530, which is pretty mandatory for most.

**Comment by gabaod** [comment]
im new to working with github and making prs, so not sure how to quickly test how the conflict or not but after reviewing their edit changes, the only conflict I can see is https://github.com/PokemonGoMap/PokemonGo-Map/pull/1576#issuecomment-262104110   that where they both are using ver 10 since neither have been migrated to develop yet and both do changes to the sql table structures, though maybe theres something I am missing.

**Comment by AdrienNguyenWorldline** [comment]
On this that is availabe in compact log mode and should be on status page (and db ?) is the webhook and db queue sizes.

**Pull request closed without merging**
