### PR TITLE
Enable automated recaptcha solving with 2captcha

### PR DESCRIPTION
**Pull request by chowderchow**
## Description

CODE FLOW:
1. If account has 2 consecutive empty scans, a check is performed to see if the account is encountering a captcha
2. If yes, it attempts to solve the captcha. If not, operation resumes. 

USAGE:

Below are the flags added:
[-cs --CAPTCHA-SOLVING]: Enables captcha solving.
[-ck --CAPTCHA-KEY]: 2captcha API key.
[-cds --CAPTCHA-DATASITEKEY]: `data-sitekey` for the captchas

## Motivation and Context

Solves captcha'd accounts.

## How Has This Been Tested?

Ran for 48 hours with 400 workers. 12 captcha'd accounts solved without any errors.

## Screenshots (if appropriate):

image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by willydk** [comment]
I would love this to be released

**Comment by jorgitoh** [comment]
Empty scans means 0/0/0? Because without -ss is totally normal get a lot of 0/0/0.

**Comment by chowderchow** [comment]
@jorgitoh Yes, and yes. 

@willydk You can pull the PR.

@iluretar Can do. Easily done with a few lines.

**Comment by willydk** [comment]
what is this data-sitekey?

**Comment by chowderchow** [comment]
@willydk the `googlekey` POST parameter (https://2captcha.com/newapi-recaptcha-en)

For PoGo captchas, this is always `6LeeTScTAAAAADqvhqVMhPpr_vB9D364Ia-1dSgK`

**Comment by willydk** [comment]
@chowderchow i see, thanks

**Comment by gabaod** [comment]
Why does this require a -cds flag ?  when the code has a default=  of it, its still expecting an argument after -cds  Just seems a little messy to require it, if its hard defined to always be the same variable for everyone.

**Comment by chowderchow** [comment]
@gabaod for the time being it doesn't require a `-cds` flag to work. It's just there in the event that the `data-sitekey` parameter for the captchas change.

**Comment by gabaod** [comment]
Well good work young lad.  Seems to work flawlessly.

**Comment by fantasy4u** [comment]
image
I have some program like this pic, How can I fix it?? 
There are no any detail info. But I check in the Mysql, I got the detail info. Howerver,  it suddenly doesn't shown the info on the box

**Comment by chowderchow** [comment]
@fantasy4u Are you using this PR?

**Comment by Stuck7hrottle** [comment]
+1

I threw whatever accounts I had that I knew were Captcha'd into a csv file and let it run. All accounts have been unCaptcha'd and map is scanning great. Love it.

**Comment by hayelf** [comment]
I was looking into https://2captcha.com/newapi-recaptcha-en . What do I fill up for method, googlekey and pageurl ?

**Comment by chowderchow** [comment]
@hayelf You just need to provide a 2captcha API key. Please read the first post.

**Comment by alexccs** [comment]
Is it possible to provide also an option to redirect the recaptcha to the web interface for volunteer solving?

**Comment by chowderchow** [comment]
@alexccs No plans for this.

**Comment by tomballgithub** [comment]
This was easy to set up and works great!  Many thanks...

**Comment by Spurlex** [comment]
Working well. Thanks.

**Comment by nullpixel1** [comment]
Tested. +1

**Comment by willydk** [comment]
my balance stays the same ~8h after I pull the speed limit code

**Comment by ic4roswings** [comment]
@chowderchow I have a method to do the captchas without 2 captcha maybe useful for small maps ore people like who cant make a payment in 2 captcha care to help me out ?

**Comment by kbtbc** [comment]
I did two things today and it seems my captcha'ed count has gone up  1) started used the -sc flag to actually start checking the accounts and 2) added pr #1530 'valid times' ... I don't think the later actually is making any extra calls to niantic, so I'm wondering if checking to see if an account is captached on only two empties is actually causing more captchas?   (previously, I was checking manually and solving them through PokeAlert).

In normal scanning condition two consecutive empties is common.  Perhaps this value should be a variable?

Also, it would be nice if there was a separate log for accounts that have been captcha'ed.

**Comment by l3lackitty** [comment]
Where can I find these files to make the changes to use 2captcha? Thanks.

**Comment by Stuck7hrottle** [comment]
No files needed. Instructions are in the description above under Usage. You need to sign up with 2captcha.com to get your 2Captcha key.

**Pull request merged**
