### PR TITLE
Fix IndexError exception when using 'none' or 'round' proxy-rotation

### PR DESCRIPTION
**Pull request by birdstream**
## Description

Fix issue #1627 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by WalterMagnum** [comment]
This works.  This should be merged.

**Comment by Albert62** [comment]
Already fixed in #1619

**Comment by birdstream** [comment]
Sorry, missed that :) Although it was a pretty simple error, after all

**Comment by sebastienvercammen** [comment]
Merged #1619

**Pull request closed without merging**
