### PR TITLE
Change pokemon link to more useful website pokemongo.gamepress.gg

### PR DESCRIPTION
**Pull request by hd1080**
Pokemon.com website has not really useful information about Pokémons in
this game. On the other hand the pokemongo.gamepress.gg website is all
about Pokémon Go. So with one click we get all the needed information
about that Pokémon.

## Description
Changed the website from pokemon.com to pokemongo.gamepress.com

## Motivation and Context
pokemongo.gamepress.com provides a lot more information than pokemon.com. This is also useful when PR #1272 gets merge because it shows the moves from a Pokémon and on this new website you see if the move is a strong one or not.

## How Has This Been Tested?
Tested on my local server in Chrome and iOS Safari.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ChipWolf** [comment]
:+1:

**Comment by ottowayne** [comment]
I disliked the pokemon.com link for quite some time because it also hands them the URL of your map in the referer...

**Comment by damnitimlost** [comment]
I just recently installed PR#1272 by using the following steps
git fetch origin pull/1272/head:test
git checkout test
npm install 

How would I go about installing this PR? Is it:
git fetch origin pull/1293/head:test
git checkout test
npm install

Thanks for the help!

**Comment by ottowayne** [comment]
@hd1080 I think you added various other commits to your pull request that don't belong here

**Comment by hd1080** [comment]
@ottowayne oh shit, first time using git. I guess I have to create a separate branch for this PR. Best is probably to delete this PR and create a new one.

**Comment by hd1080** [comment]
I will create a new PR.

**Pull request closed without merging**
