### PR TITLE
PR1576 - Updated - Add Captcha to ps and status

### PR DESCRIPTION
**Pull request by gabaod**
I have merged pr 1578 login delay and added captcha count by worker to status and ps outputs

## Description

Sorry I have no clue how to rebase etc when develop was updated, so I recreated it from the latest develop branch

## Motivation and Context

helps the user see captcha use

## How Has This Been Tested?

personal

## Screenshots (if appropriate):
captchasdrf

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by gabaod** [comment]
yea i had issues trying to get sourcetree access to that shared drive. Ill see if i can figure out which ones all changed. gotta be a simple diff cmd to figure that out ;x

**Comment by gabaod** [comment]
ok I think file perms and all should be fixed.

**Comment by gabaod** [comment]
is that correct now?  think it finally went through on git.

**Comment by callfbr** [comment]
file changes 626 seems something wrong?
and why the diff replace the whole file and not just some code?

**Comment by gabaod** [comment]
I had my dir structure at chmod644, and the dev branch is 755 so I had to go through and update all files for the file permissions only in the last commit.  If that was not the right method to fix his requested changes than I need FrostTheFox to inform me.

**Comment by lastrolo** [comment]
I noticed one file had ^M characters at the end, windows to unix conversion issue

**Comment by st0nec0ld** [comment]
It is possible to add a link for solve captcha, similar to PokeAlert app?

**Comment by Thyllz** [comment]
I just pulled this to try it out, and I got error message:

"C:\...\PokemonGoMap\PokemonGo-Map>runserver.py -os -fl -l "lon, lat" -nsc
Traceback (most recent call last):
  File "C:\...\PokemonGoMap\PokemonGo-Map\runserver.py", line 25, in <module>
    from pogom.search import search_overseer_thread
  File "C:\...\PokemonGoMap\PokemonGo-Map\pogom\search.py", line 543
    <<<<<<< HEAD
    ^
IndentationError: unexpected unindent"

This error might be obvious to some people but I don't know what is causing it. Any ideas?

**Comment by simonbuehler** [comment]
@Thyllz not specific to this PR, you have unresolved merge conflicts, resolve them using e.g. gitextensions or commandline 

works good for me, don't forget to run 
```
npm install
npm run build
```

**Comment by Thyllz** [comment]
@simonbuehler Thanks for the info. I started over with a clean clone to try out a few PR's. Seems to be working fine now.

**Comment by Alderon86** [comment]
Could u please fix the compatibility to 1501? i just cant get it to work, too many conflicts

**Comment by gabaod** [comment]
@lastrolo what file was that?  

@Alderon86 https://github.com/gabaod/PokemonGo-Map/tree/test1501  just replace the models.py and search.py files and run this query,  alter table workerstatus add captchas int default 0

**Comment by Alderon86** [comment]
@gabaod tried it, cloned a new map, merged 1576 and 1501, changed models and search.py, captchas is at default, now the only error msg left that theres no default value on last_scan_date what would i have to put there?

**Comment by divnotded** [comment]
@gabaod Thanks for the integration to 1501 instructions followed your advice works like a charm. Running 1501 with 1580, 1591 and 1597 Dramatic decrease captchas since the holiday event spike I saw. Needed a better way to monitor thank you for this

**Comment by tomballgithub** [comment]
This check-in is a mess with 626 changed files.    However, the PR does work great with manual changes made to models.py, search.py, and status.js.  It is very convenient to see the statistics both individually per worked and at the bottom in aggregate.

**Comment by gabaod** [comment]
Yea I agree.  Youre welcome to redo it for me.. It was ready to be merged but I guess I did a chmod +x at somepoint and pushed it to my github which changed some perms and fox told me to fix it so I just removed the s bit through git on the full dir structure and was never reinformed if that was improper or not.   For the time being most folks are using 1501, so Ive been just keeping this updated https://github.com/PokemonGoMap/PokemonGo-Map/pull/1597#issuecomment-264610982 instead, obviously not the proper way to issue someone to do a pr, but it works as prs arent really meant to be for other prs.   By all means go ahead and make a new pr with how this was supposed to be for dev, but hopefulyl 1501 is optimized first and merged which can easily include this as its redesigning the status output and changing mysql already.

**Comment by onilton** [comment]
Hi I really liked the PR so I have cleaned it up a little bit and opened another pull request: #1604 . Also I have removed #1576 to keep the PR to single thing.

**Comment by gabaod** [comment]
Closing this due to above comment. plus messy file structure.

**Comment by tomballgithub** [comment]
@gabaod Thank you for creating this PR.  It's fantastic...

**Comment by springjools** [comment]
I don't like this at all. It just messes with the output.

**Pull request closed without merging**
