### PR TITLE
Improving sprite image

### PR DESCRIPTION
**Pull request by Diblo**
## Description
A necessary command was added to the documentation (_basic-install/index.rst_) in order to get the sprint image to work on the windows.
Images was removed from "Notify of Rarity" option.

## Motivation and Context
A command to install the module "Flask CacheBust" was added to the documentation because the sprite image was missing. This affected only windows.
Sprite image was removed from suggests Common, Uncommon, Rare, Very Rare and Ultra Rare options as there have no image.

## How Has This Been Tested?
First I ran `pip install --upgrade git+https://github.com/maddhatter/Flask-CacheBust.git@38d940cc4f18b5fcb5687746294e0360640a107e#egg=flask_cachebust`.
After that I deleted the folder `dist`. and ran `npm install && npm run build` to rebuild the folder.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Diblo** [comment]
> A command to install the module "Flask CacheBust" was added to the documentation because the sprite image was missing. This affected only windows.

Windows do not install the forked version of flask cachebust when you are installing requirements (`pip install -r requirements.txt`). See the conversation between  @aldarund and me https://github.com/PokemonGoMap/PokemonGo-Map/pull/1333#pullrequestreview-524112

> Sprite image was removed from suggests Common, Uncommon, Rare, Very Rare and Ultra Rare options as there have no image.

The options (Common, Uncommon, Rare, Very Rare and Ultra Rare) for "Notify of Rarity" under the "Notification Settings" show a image / icon of Bulbasaur, but there have no pictures that fit them.

**Comment by aldarund** [comment]
>Windows do not install the forked version of flask cachebust when you are installing requirements (pip install -r requirements.txt)

Not true. And i told you this. Because u already have installed flask cachebust and didnt provide --upgrade flag to pip.  I told this in prev pr..

**Comment by primaxius** [comment]
See above.

**Comment by Diblo** [comment]
I do not know pip and it says that you must perform pip install -r requirements.txt not pip install -r requirements.txt --upgrade. But what the hell it is not me who has an error. It is not me showing a Bulbasaur as an icon next to the options Common, Uncommon, Rare, Very Rare and Ultra Rare.

**Pull request closed without merging**
