### PR TITLE
Fix for gevent.

### PR DESCRIPTION
**Pull request by woest85**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

Standard install of gevent fails. With --user flags it does install.

### CODE REVIEW

**Comment by woest85** [comment]
Without this change on El Capitan gevent can't be installed. It tries to write to a protected system directory not even root can write to.

Also see https://github.com/gevent/gevent/issues/679

**Comment by woest85** [comment]
Also, gevent leaves the whole runserver.py broken atm. I seems this doesn't play nice with SIP in osx el capitan. Even with it being installed I get the following error:

Traceback (most recent call last):
  File "runserver.py", line 20, in <module>
    from gevent import pywsgi
ImportError: No module named gevent

**Comment by mbg032373** [comment]
I couldn't get it to install properly no matter what I did with requirements.txt.  If you manually install it on it's own, it works though.

`sudo -H pip install gevent`

**Comment by woest85** [comment]
@mbg032373 gevent is installed for me now, but still get the error about the module not existing when running runserver.py

Are you running a homebrew version of Python?

**Comment by mbg032373** [comment]
Not using homebrew.

And it would "install" using requirements.txt, but something would obviously not getting installed properly with requirements.txt.  No matter how I installed it through requirements.txt, I got the same error you are getting.  When I manually installed it on it's own, the error went away.

**Comment by pheiberg** [comment]
Use https://virtualenv.pypa.io to prevent conflicts with the Max OS X system python installation.

**Comment by woest85** [comment]
@pheiberg I'll look into that, thnx

**Comment by jorgebsa** [comment]
Also, if you need to run the server anyway while you still try to fix gevent, you can run it on Dcoker for the time being, been using the docker image since last weekend and it works flawlessly with develop branch. If new to docker, check the following PR #1057 for more in-depth instructions on how to run with docker (it's pretty simple, really)

**Comment by gabrielsoldani** [comment]
What's your `pip --version`? I could only install it properly on Ubuntu with pip 8.1.2. The installation failed with pip 8.1.1, which came by default from the package manager.

**Comment by SeeingBlue** [comment]
> C:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map>pip install gevent
> Requirement already satisfied (use --upgrade to upgrade): gevent in c:\python27\lib\site-packages
> Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.9 in c:\python27\lib\site-packages (from gevent)
> 
> C:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map>C:\Python27\Python.exe c:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map\runserver.py -os -H 0.0.0.0 -P 5000 -nsc -fl -k A************o -l "36.214, -83.2949"
> Traceback (most recent call last):
>   File "c:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map\runserver.py", line 20, in <module>
>     from gevent import pywsgi
>   File "C:\Python27\lib\site-packages\gevent\__init__.py", line 49, in <module>
>     from gevent.hub import get_hub, iwait, wait, PYPY
>   File "C:\Python27\lib\site-packages\gevent\hub.py", line 11, in <module>
>     from greenlet import greenlet, getcurrent, GreenletExit
> ImportError: DLL load failed: The specified procedure could not be found.
> 
> C:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map>pip --version
> pip 8.1.2 from c:\python27\lib\site-packages (python 2.7)

**Comment by NHBavaria** [comment]
Same problem here...

D:\Temp\PogoServer\PokemonGo-Map>python ./runserver.py --help
Traceback (most recent call last):
  File "./runserver.py", line 20, in <module>
    from gevent import pywsgi
  File "C:\Python27\lib\site-packages\gevent\__init__.py", line 49, in <module>
    from gevent.hub import get_hub, iwait, wait, PYPY
  File "C:\Python27\lib\site-packages\gevent\hub.py", line 11, in <module>
    from greenlet import greenlet, getcurrent, GreenletExit
ImportError: DLL load failed: The specified procedure could not be found.

**Pull request closed without merging**
