### PR TITLE
Persistent Data of Pokemon Notifications/Exclusion

### PR DESCRIPTION
**Pull request by lix7**
## Description
When restarting the server and browser, the list of pokemons to notify/exclude/rarity are cleared. I've created json file to save those list so you don't have to keep updating the list. 

The file is located in ROOT/static/pokelist.json
It has a few pokemons already in the file to provide an example of how to modify it and also to make people aware of this file. Although this should be discussed if the json file should be empty so people dont think this is some kind of bug and mention this in the documentation. An alternative approach can be to include the location of pokelist.json in the placeholder text of the notify/exclude/rarity text boxes so people know where to look.

The contents of pokelist.json: Exlcludes pidgey, rattata, raticate, drowsee. Nofifies charizard, blastoise, venusaur, mewtwo
{
 "exclude" : [16,20,19,96],
 "notify"  : [3,6,9,150],
 "rarity"  : ["Ultra Rare","Rare"]
}

The order of the pokemon numbers are not important. Currently, this feature only reads data but doesn't write. For example, modifying the list in the browser will not update the pokelist.json file. 

## Motivation and Context
Many have requested for this feature. It also very hard clicking the map on mobile when there too many pokemon on the map.

## How Has This Been Tested?
I've tested this in Firefox and Chrome. Once the webpage loads. The list of pokemon from the file should appear in the corresponding dropbox menus of the Options tab.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by GenuineSounds** [comment]
> When restarting the server and browser, the list of pokemons to notify/exclude/rarity are cleared.

There is no problem with the persistent state of the webpages' settings unless it's on your client only. I don't think this is necessary at all, and especially not as a global state for all users that connect to the server. Fix your browser not to delete everything on close or deal with it.

**Comment by BaIthamel** [comment]
Agreed this is not an issue for me, i can clean and reinstall the repo and my browser still holds the settings.

**Comment by chuyskywalker** [comment]
While the above statements are true, there's been a lot of chatter from other places where people do want default lists. But I'd ask for them to be compatible with the `arg`/`config` setup we already have instead of making people code in yet another format for configuration.

**Comment by CometX** [comment]
This is awesome, please keep this current and hope for merge! Would be nice if you could make it work with current config file as well.

**Comment by CometX** [comment]
Does this still work with current Dev branch?

**Comment by primaxius** [comment]
This is an issue with your browser. Not an issue that needs fixing on the servers.

**Pull request closed without merging**
