### PR TITLE
Solve linting errors and enable eslint in travis

### PR DESCRIPTION
**Pull request by Chlodochar**
## Description

This solves the linting errors for the JS files. It also enables ESLint in Travis again.

## Motivation and Context

* The current JS code is messy. This is a first step in improving the quality.
* It makes linting useful again. At the moment linting (using `grunt lint`) results in 2000+ errors. These are all solved with this PR.
* It also makes sure future PRs are using the same coding-style as the rest of the project.

## How Has This Been Tested?

Going through the various features of the game and trying them out manually.

This was previously also submitted to AHAAAA's repo. One concern there was that the mapstyle-JSON objects were also formatted. These styles could be inlined, but will result in linting errors and is messy anyway. These need to be split up to another file eventually.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [?] My code follows the code style of this project. (What code style?)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Chlodochar** [comment]
Linting runs without errors: https://travis-ci.org/PokemonGoMap/PokemonGo-Map/builds/150486003#L1939

**Comment by Becold** [comment]
+1

**Comment by JZ6** [comment]
+1 @invisiblek

**Comment by invisiblek** [comment]
<insert random excuse for not seeing this commit earlier>

Rebased and working here: https://github.com/invisiblek/PokemonGo-Map/commits/lint

**Comment by chuyskywalker** [comment]
+1 with rebase; let's get this cleaned up so we can keep it clean going forward.

**Comment by invisiblek** [comment]
pushed

**Comment by Chlodochar** [comment]
Thanks!

**Pull request closed without merging**
