### PR TITLE
Make -ac csvinput ptc-acc-gen compatible again

### PR DESCRIPTION
**Pull request by Darkknightz**
## Description

ptc-acc-gen adds location and nickname to CSV.

## Motivation and Context

most folks would use ptc-acc-gen which inputs 5-6 fields in CSV, previous code only worked with 3 or less fields.

## How Has This Been Tested?

Locally with multiple CSV layouts

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Darkknightz** [comment]
@FrostTheFox This needs to be merged to be compatible with the output of your acc gen. https://github.com/FrostTheFox/ptc-acc-gen

**Comment by FrostTheFox** [comment]
Meh, I mean in reality it's not *that* hard to make it compatible, just have o dump the extra fields. Best to save those for other things. Thanks for the PR, though.

**Comment by Darkknightz** [comment]
Just made this in response to folks commenting in original PR #1199. Also fixes issue #1284 but I see there is another PR#1283 for it also.

**Comment by k4n30** [comment]
Why can't this be merged @FrostTheFox ?

**Pull request closed without merging**
