### PR TITLE
Add a flag to allow purging stale pokemon from the database

### PR DESCRIPTION
**Pull request by invisiblek**

### CODE REVIEW

**Comment by JZ6** [comment]
+1 but why a week lol, a day or even an hour would make more sense for the average user

**Comment by Chlodochar** [comment]
I might be missing something, but the code seems to suggest they are removed after 12 hours, not a week. Other than that, this seems like a useful addition :+1:.

**Comment by Cronick** [comment]
Would this not go against the purpose of the stats page?

**Comment by Mr-Groch** [comment]
"Full stats" page data will be incomplete

**Comment by Chlodochar** [comment]
I don't think so. With this the stats will only show a timeframe of a week. @invisiblek, maybe change the option to accept the number of days Pokemon are kept.

**Comment by Cronick** [comment]
I don't know why, but I don't really experience the same amount of data used on 30 minutes. I have about 220k rows in my database for Pokemons, and it's only about 30-40 mb.

Must be some crazy areas you guys are scanning to find Pokemons that can fill 10 gb of data in 30 mins.

**Comment by Frozen-byte** [comment]
Please don't delete after 7 days, or let the user set the expire time.

**Comment by TallGuy74** [comment]
Would it be possible to leave the default on what it is now (0 = disabled)?

**Comment by invisiblek** [comment]
Possible? Yes.

I think we should be cleaning peoples' db by default though. I feel like its bad practice to let users' databases just fill up forever, even though we KNOW that most of the data expires and is basically useless after the given time.

**Comment by huanga** [comment]
Can we make this configurable? Personally, I have large enough storage, and would much rather capture as much data as possible for future machine learning exercises.

**Comment by invisiblek** [comment]
The current patch is configurable.

**Comment by invisiblek** [comment]
Now defaulting to disabled. Users can set as they see fit.

**Comment by chuyskywalker** [comment]
lgtm

**Comment by Chlodochar** [comment]
Looks good :+1:

**Pull request merged**
