### PR TITLE
Fix MariaDB migrations after 81739ff

### PR DESCRIPTION
**Pull request by ottowayne**
## Description
Same as in f863d96

## How Has This Been Tested?
On my own live deployment

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ottowayne** [comment]
If you already ran into this problem you won't be able to fix this by just merging my changes.

Your migration version will probably already have been increased (like in issue #1006) and you will get this error:
> Your database version (6) appears to be newer than the code supports (5).

If that happend run this query on your database:
> UPDATE versions SET schema_version =5;

That should fix it without resetting your database. **I do not take guarantee for this.**

**Comment by ultrafunkamsterdam** [comment]
when is this implemented? yesterday it still worked fine. will try this later this evening. thanks!

**Comment by maddhatter** [comment]
What version of MariaDB are you using?

**Comment by ottowayne** [comment]
Server version: 10.0.24-MariaDB-7 Ubuntu 16.04

**Comment by ultrafunkamsterdam** [comment]
@maddhatter 

from https://github.com/PokemonGoMap/PokemonGo-Map/issues/1006#issuecomment-242731331

my versions

2016-08-26 13:35:14,333 [ MainThread][ models][ ERROR] Your database version (6) appears to be newer than the code supports (5).
2016-08-26 13:35:14,333 [ MainThread][ models][ ERROR] Please upgrade your code base or drop all tables in your database.

running : mysql Ver 15.1 Distrib 10.1.16-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

+--------------------------+
| VERSION() |
+--------------------------+
| 10.1.16-MariaDB-1~xenial |
+--------------------------+
1 row in set (0.00 sec)

SHOW VARIABLES LIKE "%version%";
+-------------------------+---------------------------------+
| Variable_name | Value |
+-------------------------+---------------------------------+
| innodb_version | 5.6.30-76.3 |
| protocol_version | 10 |
| slave_type_conversions | |
| version | 10.1.16-MariaDB-1~xenial |
| version_comment | mariadb.org binary distribution |
| version_compile_machine | x86_64 |
| version_compile_os | debian-linux-gnu |
| version_malloc_library | system jemalloc |
| version_ssl_library | OpenSSL 1.0.2g-fips 1 Mar 2016 |
| wsrep_patch_version | wsrep_25.13 |
+-------------------------+---------------------------------+

npm version 3.10.3
nodejs version 6.4.0

This came after a new git clone. I did chown -R the folder and set chmod -R 775 to the folder and contents.

I ran the pip install -r requirements.txt
npm install
npm run build

If anyone knows a simple way of solving this without losing my database (it covers whole region), please let me know.

Thanks in advance!

**Pull request merged**
