### PR TITLE
Add marker icon image

### PR DESCRIPTION
**Pull request by hklcf**

### CODE REVIEW

**Comment by Becold** [comment]
Screenshot of the new marker?

**Comment by hklcf** [comment]
#660 https://raw.githubusercontent.com/PokemonGoMap/PokemonGo-Map/a66908aabca6ad1ec57feee8ba8c79d436ff9a03/static/marker_icon.png

**Comment by hklcf** [comment]
@chuyskywalker done

**Comment by Studio-XP** [comment]
I took it a step further and created an aminated version.  Save it as marker_icon.gif to /static/, and in the line under `icon: 'static/marker_icon.gif',` add `optimized: false,`. You're more than welcome to it if you'd like :)

marker_icon

**Comment by invisiblek** [comment]
I love the animated one, however I'm a bit concerned it would be distracting

**Comment by hklcf** [comment]
@Studio-XP will you submit PR for the aminated version?

**Pull request merged**
