### PR TITLE
Gym Filtering

### LINKED ISSUE #1574: [Feature Request] Add detailed gym filter on the sidebar
alp-bitcoin submitted a PR for this but closed it because he didn't want to maintain it anymore:
https://github.com/PokemonGoMap/PokemonGo-Map/pull/1288

Would appreciate if someone else could pick this up and re-submit it.

### PR DESCRIPTION
**Pull request by Rook25**
## Description

Have rebased #1288 by @alp-bitcoin which added gym filtering to the map front end. #1288 added the ability to filter based on the min/max level of a gym, which team's gym, when the gym was last scanned, how close the gym was to having an open slot etc. 

I have also fixed up some minor issues with the gym controls still showing even when gyms were switched off.

This fixes #1574

## Motivation and Context

This change isn't required but allows map users to hunt/target gyms more efficiently. 

## How Has This Been Tested?

Tested on my own map installation

## Screenshots (if appropriate):

2017-01-11 09_10_19-pokemon go map

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sebastienvercammen** [comment]
Remove the possibility to search for trainer name (because it will only fuel witch hunts and negativity) and [fix Travis issues](https://travis-ci.org/PokemonGoMap/PokemonGo-Map/builds/190737427), and we'll review this to be merged.

**Comment by Rook25** [comment]
Sorry. Didn't realise the trainer name search would be considered a problem. I use it to figure out where my pokemon are. Will close this as without that feature this is identical to #1288 .

**Comment by sebastienvercammen** [comment]
With @alp-bitcoin out of the picture (it's been several months and a lot has changed on PokémonGo-Map's side), the original PR being closed, and this PR already being rebased, we can use this PR to merge if you're up for it.

Only needs to have the trainer name removed. :)

**Comment by fufufabulous** [comment]
I did changes but options do not show up, am i missing something ?

**Comment by Rook25** [comment]
You need to 'npm install' and refresh the browser for changes to take effect.

**Comment by jde1126** [comment]
I hate to ask, but HOW does a person like me, use this pull request?

**Comment by sebastienvercammen** [comment]
@jde1126 We generally don't recommend trying to use pull requests if you're not used to git/github, as it will complicate things when we push an update to the main branch and you want (or need) to use those updates.

If you'd like to learn, there are a lot of git/github tutorials out there.

**Comment by Rook25** [comment]
@jde1126 Unfortunately, pull requests are no longer supported. So it's up to you to figure out how to integrate a pull request to test the code (google - checkout pull request github). If enough people approve this change it will eventually get merged into the dev branch so you could just wait til then.

**Comment by m3g4mInD** [comment]
This is a cool feature,i need to do a try on this, thanks @Rook25

**Comment by drallieiv** [comment]
Worked well, also combined with opacity from #1706

**Comment by drallieiv** [comment]
You should add : "fixes #1574" 
in the main description of the PR, that way gitlab we know to close the issue if it gets merged

**Comment by Qualimiox** [comment]
I just updated to the latest dev-branch and I really like this addition. The only thing I noticed: When I switch to "Open Spot"-view, neutral gyms disappear. Shouldn't they technically stay visible since anyone can claim them and therefore they have an "open spot"?

**Comment by Rook25** [comment]
@Qualimiox to be honest, it's so rare that I see a neutral gym I didn't even think about it. I can check to see whether this can be added as a separate pr/bugfix.

**Comment by alp-bitcoin** [comment]
Thanks for getting this in!  I was surprised when I noticed this feature in an update!  I didn't realize this map even still worked until I saw it on a local map.  Props to @Rook25 for running with this!

**Comment by Rook25** [comment]
@alp-bitcoin Thanks for doing the legwork! I added in the Trainer Search feature but that got vetoed so all I actually did was rebase your pr in the end.

**Pull request merged**
