### PR TITLE
Add proxy support

### PR DESCRIPTION
**Pull request by invisiblek**

### CODE REVIEW

**Comment by porcoRedwood** [comment]
Thanks for adding this!

However, I'm getting the following error:
...
2016-08-10 17:47:26,469 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-10 17:47:26,469 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-10 17:47:26,620 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-10 17:47:26,629 [ search_worker_0][        search][ WARNING] Exception while downloading map: RpcApi instance has no attribute '_session'
2016-08-10 17:47:26,629 [ search_worker_0][        search][   ERROR] Search step 1 area download failed, retrying request in 10 seconds

Help would be much appreciated!

**Comment by viliam-jobko** [comment]
Same issue as @porcoRedwood. Tried with two different proxies (one in Poland and one in Brazil).

**Comment by invisiblek** [comment]
This is needed: https://github.com/keyphact/pgoapi/pull/77/files

**Comment by viliam-jobko** [comment]
Works fine with provided pgoapi fix. Thanks!

**Comment by ottowayne** [comment]
Yep, can confirm that it works with Noctem's pgoapi fix so this should be merged when Noctem's pull request has been merged and the pgoapi version has been upgraded in the requirements.txt

**Comment by insomnia9669** [comment]
Does this proxy support, work with authentication?

**Comment by RyanHickman** [comment]
@insomnia9669 Just include the authentication following the protocol (e.g. http://username:password@hostname/IP:port). 

I've confirmed support for this I THINK, though my results seem to be mixed. I'm getting the following...

```
[user@asdf PokemonGo-Map]# python runserver.py -st 7 -a PTC -u XXXX -p XXXX -k XXXX -l lat,lon -ng -nk -px "http://user:pass@ip:port"
2016-08-10 23:13:36,752 [      MainThread][     runserver][   ERROR] Unable to retrieve altitude from Google APIs; setting to 0
2016-08-10 23:13:36,752 [      MainThread][     runserver][    INFO] Parsed location is: lat/lon/0.0000 (lat/lng/alt)
2016-08-10 23:13:36,752 [      MainThread][     runserver][    INFO] Parsing of Pokestops disabled
2016-08-10 23:13:36,752 [      MainThread][     runserver][    INFO] Parsing of Gyms disabled
2016-08-10 23:13:36,755 [      MainThread][        models][    INFO] Connecting to local SQLite database
2016-08-10 23:13:36,756 [   search_thread][        search][    INFO] Search overseer starting
2016-08-10 23:13:36,757 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-10 23:13:36,758 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-10 23:13:36,758 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 1)
2016-08-10 23:13:36,759 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: XXXX
2016-08-10 23:13:37,184 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-10 23:13:37,185 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-10 23:13:37,305 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-10 23:13:38,837 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-10 23:13:45,844 [ search_worker_0][        search][    INFO] Search step 2 beginning (queue size is 125)
2016-08-10 23:13:46,133 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
2016-08-10 23:13:56,143 [ search_worker_0][        search][    INFO] Search step 3 beginning (queue size is 124)
2016-08-10 23:13:56,424 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
```

Is it the altitude I'm having trouble with? Or could it be the proxy authentication?

**Comment by insomnia9669** [comment]
I tried what you said, and I get this error: 
Traceback (most recent call last):
  File "C:\Users\PokemonGoMap\Desktop\PokemonGo-Map-develop\PokemonGo-Map-develop\pogom\search.py", line 195, in search_worker_thread
    api.set_proxy({'http': args.proxy, 'https': args.proxy})
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 127, in __getattr__
    raise AttributeError

**Comment by CtrlAltDefeat94** [comment]
@NaderCHASER did you find a fix for the 0 pokestops/gyms/pokemon? I seem to be having the same (authless proxy)

**Comment by max1404** [comment]
Doesn't work with:

run in screen
`ssh -N -D2000 username@server`

start map
`python2.7 runserver.py -a ptc -u XXX -p YYY -l 'ZZZ' -dc -L de -k ABCDEFG -px socks5://127.0.0.1:2000`

The socks5 proxy was not used.

**Comment by NaderCHASER** [comment]
@CtrlAltDefeat94 I did just now actually! I was using DD coordinates and my decimal precision was 6. When I switched to -l "ADDRESS CITY, STATE ZIP" everything started working. That's when I discovered that a decimal precision of 7 was necessary to start seeing Pokemon.

I can confirm that proxy support a) works (tested) and b) supports authentication. I'm now able to retrieve data on my GCE instances using a SOCKS5 proxy.

Thank you @invisiblek!

**Comment by sngreco** [comment]
@NaderCHASER How did you add support for the proxy switch?  I just updated the repository and tried -px switch like your example above and it says it's an unrecognized argument

**Comment by max1404** [comment]
@NaderCHASER Can you post then command line with proxy settings, please?

**Comment by mrfantomex** [comment]
Still getting this on latest release:

Exception while downloading map: RpcApi instance has no attribute '_session'

**Comment by Nik0lashka** [comment]
@invisiblek hi! First of all i would like to thank you for your great work! 
I found, that python terminal session besides proxy from settings, connects to niantic: 

Could it be somehow fixed and does it need to be fixed? By the way, if i use 10 accounts even through proxy i have higher probability to get IP ban, am i right?

@max1404 if it is still needed i use this:
...
gmaps-key:xxx
proxy: socks5://74.75.185.59:4362
#webhook:
...

**Pull request merged**
