### PR TITLE
Emulate the actual API calls made as if it was from an app

### PR DESCRIPTION
**Pull request by chowderchow**
get_map_objects, encounter and fort_details/get_gym_details were modified to mimic an actual request envelope made by an Android app

## Description
With these changes, the captcha detection has been moved to be checked with every GMO request, since the response now contains the CHECK_CHALLENGE field. Thus removing the need for the captcha_request function. 

## Motivation and Context
Hopefully helps to avoid ban/softban/captcha detection

## How Has This Been Tested?
Previously ran with these changes in another PR, changes were unaltered and carried forward.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by therealssj** [comment]
I dont think you need to do 
` x = req.check_challenge()` just doing `req.check_challenge()` should queue the request and in the end you do `x = req.call()` like you have done

**Comment by simonbuehler** [comment]
Shouldn't correct elevation values be part of this ? Like getting from Google API, saving in DB, using the value for all locations within x Meters distance. If location is too far away, look up DB for data and if not already Cached call API to get New value,save to DB and done

**Comment by therealssj** [comment]
I can say that the elevation doesn't matter much. Google API has rate limits so its better to leave it out.

**Comment by chowderchow** [comment]
@therealssj it's for verbose/very verbose logs 

@simonbueler elevation implementations will be in a separate PR.

**Comment by PokeSearcher** [comment]
I've got roughly 80 accounts running on individual positioned processes with -st 4 -sd 15 and been trying this pull request for the last couple of hours. Completely subjectively (I didn't record numbers) it didn't seem to make much difference to captchas, I still had maybe 25-30% of the accounts captchad.

**Comment by FrostTheFox** [comment]
Double testing this now, should be good.

**Comment by k4n30** [comment]
@chowderchow assuming you forgot to include reporting bad captchas when they are verified against the API?

**Pull request merged**
