### PR TITLE
Added pokesniper url for those so-inclined

### PR DESCRIPTION
**Pull request by Subodai**
## Description

Added a pokesniper url to the details card for pokemon on the map for easy sniping when scanning locally.

## Motivation and Context
Saves having to copy-paste the co-ords if you use pokesniper which due to the map refresh can be a bit hit and miss.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

Added a pokesniper url for easy local sniping.

### CODE REVIEW

**Comment by Slivo-fr** [comment]
Seems usefull, why not :)

**Comment by invisiblek** [comment]
No. We do not support/promote botting or things of this nature.

**Comment by Slivo-fr** [comment]
Not really botting related imo ...

**Comment by Subodai** [comment]
No worries, was just a convenience thing. As I noticed it was used here and there.

**Pull request closed without merging**
