### PR TITLE
Added a wave_delay for once the step_limit has been reached

### PR DESCRIPTION
**Pull request by LurkerLurks**
## Description

Setting WAVE_DELAY (-wd) in seconds will delay the start of the next wave of scanning once the STEP_LIMIT has been reached.

For example, you want to scan your immediate area once every 5 minutes and you have 7 accounts setup you can set STEP_LIMIT to 3 and scan your immediate area all at once and then have WAVE_DELAY postpone the next wave for 300 seconds.

## Motivation and Context

Built out a solution for my feature request (Issue #570). Sorry it was posted in the wrong place. Let me know if you want it reposted to feathub.

## How Has This Been Tested?

I ran it and looked at the CLI output. There is a delay in the scan once the step limit is hit. I tested various delays: 30, 60 and 120. It worked flawlessly. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

I wasn't sure if documentation needed updating. I figured the commandline help text was enough. Let me know if I need to do that. 

This is my first PR to an opensource project. Please be patient with me.

### CODE REVIEW

**Comment by chuyskywalker** [comment]
Actually, this isn't working how you think.

The overseer loop is designed to be, basically, continously looping and not pausing for anything. It doesn't get to that `time.sleep(1)` and pause there till the search set is done.

You should actually add this here:
```
         if search_items_queue.empty():
             log.debug('Search queue empty, restarting loop')
```
into
```
         if search_items_queue.empty():
             log.info('Search queue empty, restarting scanners after %d second wave delay', args.wave_delay)
             time.sleep(args.wave_delay)
```

**Comment by LurkerLurks** [comment]
I just tested this it seems to be working ok. I want the delay to start after the first scan so I moved it down alittle bit.  I tried switching between log.info and log.debug and tried using the -d debug flag but I am not seeing the added log message in the console. I am not sure what I am doing wrong in that regard. The pause does seem to be working appropriately through.

**Comment by chuyskywalker** [comment]
This, also, will have unexpected results. It's only working for you because you have a higher number of accounts and a limited set of scan steps. If someone had, say, 200 scan steps, and only a few accounts, the queue will finish well after `wave-delay` does, and they'll be left wondering, "Hey, why didn't wave delay add X seconds after the queue hit zero?"

**Comment by chuyskywalker** [comment]
If you don't want to have it happen on the first scan (which is reasonable) you'll need to add a "isFirstScan" variable to the overseer loop so you can flip that boolean. But the wait will still need to be in the place where I original showed above

**Comment by LurkerLurks** [comment]
That makes sense. I will have some more time to work on it later this weekend. Thanks for walking me through the process.

**Comment by chuyskywalker** [comment]
Of course, thanks for contributing -- I know it can be a hassle to open a PR in somebody else's pool.

**Comment by LurkerLurks** [comment]
Sure, it has been a good learning experience. So does something like this work?

````python
        if search_items_queue.empty():
            if args.wave_delay > 0 & isFirstScan > 0:
                log.debug('Waiting for %d second wave delay', args.wave_delay)
                time.sleep(args.wave_delay)
            log.debug('Search queue empty, restarting loop')
            for step, step_location in enumerate(generate_location_steps(current_location, args.step_limit), 1):
                log.debug('Queueing step %d @ %f/%f/%f', step, step_location[0], step_location[1], step_location[2])
                search_args = (step, step_location)
                search_items_queue.put(search_args)
            isFirstScan = 1
````

I am not sure where/how I should declare the isFirstScan variable. My experience with python is limited to a few afternoons of playing with the beautifulsoup4 library a few months ago. I understand the very basic programming principles but have not developed software before. I don't know why I waited so long to get into it. It is a lot of fun.

**Comment by chuyskywalker** [comment]
You have to set the `isFirstScan = True` way closer to the top of the function so that it's set when the function starts, but is only set once. then it'd be more like

```
if (args.wave_delay > 0 and isFirstScan):
  time.sleep(args.wave_delay)

# queue stuff here
isFirstScan = False
```

**Comment by LurkerLurks** [comment]
The only issue with is is that if you wait for the wave delay to move the position, The pause and scan must run gain before it picks up the new move. I am testing putting the pause before the move check.

**Comment by LurkerLurks** [comment]
I removed the delay after the overscan but there is still an overscan. I am not sure how to avoid that. 

**Overscan Example:** If you have 3 accounts and set the step limit to 7. After the last scan the delay is triggered. During the delay you move the location. Once the pause completes the first 3 scans of the original wave are repeated. Once for each account. The scan then snaps to the new location and starts scanning as usual. 

> This, also, will have unexpected results. It's only working for you because you have a higher number of accounts and a limited set of scan steps. If someone had, say, 200 scan steps, and only a few accounts, the queue will finish well after wave-delay does, and they'll be left wondering, "Hey, why didn't wave  delay add X seconds after the queue hit zero?"

This would be fine/prefered. It was Option B in my original request but seemed more complicated to implement. The goal is being able to set a  standard cadence between scan waves.  This would be a "start a new waves no sooner than 5 minutes apart"  kind of a thing.

**Comment by primaxius** [comment]
Conflicts - resubmit if needed  - Cleaning old PR's

**Pull request closed without merging**
