### PR TITLE
Re add lure pokemon

### PR DESCRIPTION
**Pull request by Zoruk**
## Description

The problem here is that lure_info field is only present when the scan is close enough to the pokestop this way if we store those info in the pokestop database as soon an other scan find the pokestop but is too far from the stop to get the lure_info field it will erase the lured pokemon from the database

This version use a new table to srote lure info.

Most of the frontend code was allready present from previous implementation

## Motivation and Context

Since last api change the lured pokemon arent displayed 
FIX https://github.com/PokemonGoMap/PokemonGo-Map/issues/715

## How Has This Been Tested?

Tested on my own server

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Zoruk** [comment]
Same as https://github.com/PokemonGoMap/PokemonGo-Map/pull/768 but from an other branch

**Comment by nunopitbull** [comment]
I replaced all raw files to the files and nothing changed. Only thing changed was text in the Options. No lured pokemons. Do I need to do something extra rather then just copy/paste?

**Comment by MonjoNL** [comment]
The map.js has to minimized to a map.min.js. Just run npm install again.

**Comment by nunopitbull** [comment]
I open a command in POkemonGo-map directory and run npm install?

**Comment by MonjoNL** [comment]
Yes, just like you did when installing the project.

**Comment by nunopitbull** [comment]
Thaanks!! It actually worked!!!

**Comment by Garuk** [comment]
Please forgive my ignorance, I got this fix working but the lured pokemon only show when accessing the map on "localhost:port" , if I try to access the map with it's LAN IP (192.168.etc etc) it shows the map I had before working correctly but with no lured pokemon.

**Comment by Garuk** [comment]
Pokemon that appear from used lures aren't being registered in the "stats" page, is this some kind of error or is it intentional?

Also, thanks for the fix it's working nicely.

**Comment by SirPownzalot** [comment]
It's intentional. You gotta realize that spawns are fixed, while lured pokemons are random. Hence, there's no point in having a log of which pokemon showed on lures. There is though good reason to want a database with all spawnpoints near you, so you can better scan your area.

**Comment by darkelement1987** [comment]
It gives me an internal server error when running server with these files.

**Comment by moggd** [comment]
I get an ImportError froom pogom.models - cannot import name init_database error when using these files

**Comment by Zoruk** [comment]
Can you give a full traceback plz ?

**Comment by Zentriert** [comment]
@Zoruk http://i.imgur.com/qY41XEw.jpg  

I had it runnning fine yesterday from about 10am-midnight with no errors, I was out catching Pokemon and it was good. I came home around 12:30am EST and looked in the console there and it had given me that message. 

Coincidentally it only started JUST as I was getting home from hunting Pokemon, when saw it, it was on retry number 4-5 just giving the same error message but putting another 12 seconds on the timer each attempt. 

I have no idea why it broke at that time but I'm thinking maybe something has changed? It was literally running for over 12 hours solid before that with no issues. 

I noticed they pushed some commits between yesterday morning and tonight, I tried the latest commit with this code and it gives the exact same error in the screenshot. 

Much appreciate your time as always! Let me know if you need anything :)

**Comment by Zoruk** [comment]
It's not related to this PR: https://github.com/PokemonGoMap/PokemonGo-Map/issues/448

**Comment by Zentriert** [comment]
So then my account was randomly banned at the same time I got home ... interesting. I don't leave it on 24/7 like a lot of people, only when I'm using it and that account had been used for weeks with no issues, so I guess Niantic finally got to it. 

Want to note that was the longest continuous period I ever had it running, 14ish hours? First time I've ran it that long and bam, ban?

**Comment by darkelement1987** [comment]
I just copy/pasted the files you made and overwritten, then rebooted server and it gave me 'Internal Server Error', when putting original files back it worked again.

**Comment by Zoruk** [comment]
@darkelement1987 I can't help you if you don't give more informations

**Comment by darkelement1987** [comment]
Well, i just grabbed your files (see my zip: www.tjielup.nl/lured.zip) and just pasted them over the existing original files, then rebooted my server (runserver.py) and it gave me the Internal Server Error when visiting my map in the browser, after that i put the original files back, rebooted and everything was fine again. How should i install it properly?

**Comment by Zoruk** [comment]
@darkelement1987  What's the result of the cmds 

git status
git log
git diff

**Comment by darkelement1987** [comment]
C:\Server 3>git status
fatal: Not a git repository (or any of the parent directories): .git

C:\Server 3>git log
fatal: Not a git repository (or any of the parent directories): .git

C:\Server 3>git diff
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>

C:\Server 3>

**Comment by Zoruk** [comment]
@darkelement1987 Heu you need tu be in the sources folder

**Comment by darkelement1987** [comment]
You mean c:\Server 3\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-regenerator\node_modules\babel-core\node_modules\source-map\

?

**Comment by Zoruk** [comment]
Go MP on discord plz stop flood the PR

**Comment by darkelement1987** [comment]
Don't have time right now, ill be there tomorrow morning.

**Comment by jnovack** [comment]
@Zoruk I refuse to spend the time to follow this thread (not your fault that it was derailed).

Can you post a status-update message and update the first post so we can all catch up on this post's progress?

**Comment by Zoruk** [comment]
@jnovack It's fully working maybe it will need just a little refactoring but everything is working fine. It's running for 4 days with 50 beehive with 3 accounts each without any troubles

**Comment by TachyonRSA** [comment]
Have been using it most of the day as well, works perfectly @Zoruk

**Comment by jnovack** [comment]
Why are you making a new table?  It seems to me that Pokemon are Pokemon.. and should just have the `is_lured` tag on it.  

If there's an issue with spawn point extracts, then that code should be updated, we shouldn't be making new tables because of old code.

**Comment by Zoruk** [comment]
@nunopitbull Just refactoring to functional update

**Comment by Zoruk** [comment]
Because Pokemon table contain spawnpoint_id wich is not present for lured pokemon

**Comment by jnovack** [comment]
> Because Pokemon table contain spawnpoint_id wich is not present for lured pokemon

... so then leave it NULL.

**Comment by LordNeoZ** [comment]
Pseudo code

If null then show_as_lured
Else show_normal

And theb add some "remove null" on the database cleaning rutine

**Comment by slideup-benni** [comment]
Why not do this like before? in the pokestop table in the cell lured_pokemon?

**Comment by Asafffff** [comment]
A nooby question, how can I download and add it to my own server? tried finding a download button in files changed / commits without any success...

**Comment by slideup-benni** [comment]
`git fetch origin pull/883/head:lured` and `git checkout lured`

**Comment by darkelement1987** [comment]
@slideup-benni thanks!!!!

**Comment by moleeternal** [comment]
It's working, thanks!

**Comment by madden1234007** [comment]
@slideup-benni Any idea why I would be see the server finding lured pokemon but not see them on the map after doing the commands you listed? Thanks!

**Comment by aczone** [comment]
@madden1234007
I have the same issue. And I got many warnings on Webhook queue is > 50 try increasing --wh-threads.
Tried solution here with no help.

**Comment by cpavanelli** [comment]
@madden1234007
do you have **no pokestops** config enabled? **-nk**
I had to remove this config to make it work here.

**Comment by aczone** [comment]
@cpavanelli 
I didn't have it enabled and still couldnt see

**Comment by Romfrosk2** [comment]
Would love to see this properly rebased on the current develop :)

**Comment by maddhatter** [comment]
I'm not sure what the reasoning for the extra table is either? Why not just leave spawn_id NULL if it's lured, and use that as the indicator that it was a lured pokemon?

What're your issues with #666? Maybe I can try to help resolve those?

**Comment by jnovack** [comment]
@maddhatter Again, AFK.  Do you think you can own this issue?

**Comment by chazhakagi** [comment]
@aczone
same > 50 problem with --db-threads
somehow it shows lured pokemon, tho

**Comment by maddhatter** [comment]
I opened #1079 as another approach to solving this problem. I'd love to discuss the differences between it and this PR (like, what's the use case behind disabling the display of lured Pokemon separately than others? That's something I didn't consider.) and find the best solution.

**Comment by primaxius** [comment]
closed going in favor of PR 1079

**Pull request closed without merging**
