### PR TITLE
Added script to generate a multi user run command

### PR DESCRIPTION
**Pull request by razorasadsid**
https://github.com/razorasadsid/HoneySpots
## Description

HoneySpots is a super easy fast tool to run multi-location multi-account worker setups, it parses through csv files (like the ones generated by the account generator) and can be configured to taste.
## Motivation and Context

It allows you to scan a couple specific areas very very fast with multiple workers without hassling through beehive or having to enter in data as flags in .bat files yourself.

## How Has This Been Tested?
Well i've had a couple people run it no problem and I'm fixing bugs as they come. Most updated version is obv going to be on github.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by razorasadsid** [comment]
Aw fugde my tab didn't save editing rq

**Comment by chuyskywalker** [comment]
Platform specific tools should be maintained in their own repos. I definitely don't want compiled code in the repo (`libencrypt` as the exception).

_We really need to get a wiki page of "community tools" put together for stuff like this..._

**Comment by mrlim0nad3** [comment]
is there a way to convert the honeyspots for mac command ?

**Comment by razorasadsid** [comment]
@mrlin0nad3 it's AHK so I'm sure it's not too terribly hard. Although I'm closing this because i'd rather have this on a wiki page and cause a lot's changing haha.

**Pull request closed without merging**
