### PR TITLE
Map Gym icons

### PR DESCRIPTION
**Pull request by Daemonmatrix**
Shows Level on gym icons without having to click on them, changes made by pandabithia from discord.
capture-20160810-222539

### CODE REVIEW

**Comment by Viper2k4** [comment]
Maybe u could use a function like this:

```
function getMarkerPath(item) {
	var gymLevel;
	if (item.gym_points >= 50000) {
		gymLevel = 10;
	} else if (item.gym_points >= 40000) {
		gymLevel = 9;
	} else if (item.gym_points >= 30000) {
		gymLevel = 8;
	} else if (item.gym_points >= 20000) {
		gymLevel = 7;
	} else if (item.gym_points >= 16000) {
		gymLevel = 6;
	} else if (item.gym_points >= 12000) {
		gymLevel = 5;
	} else if (item.gym_points >= 8000) {
		gymLevel = 4;
	} else if (item.gym_points >= 4000) {
		gymLevel = 3;
	} else if (item.gym_points >= 2000) {
		gymLevel = 2;
	} else {
		gymLevel = 1;
	}
	
	return 'static/forts/' + gymTypes[item['team_id']] + '_' + gymLevel + '.png';
}
```

and later:

`var markerPath = getMarkerPath(item);`

So u avoid writing the exact same code two times.

**Comment by Daemonmatrix** [comment]
Sorry didn't really pay attention to the code I was given pandabithia couldn't figure out how to submit a pull request on github so I volunteered. Worked like a charm though :-D

**Comment by FlarumHostingCo** [comment]
@Daemonmatrix I am using a domain to cache images via cdn   Using return 'https://cdn.xxxxxxxxxxxxx.com/' + gymTypes[item['team_id']] + '_' + gymLevel + '.png';  The gyms no longer load

**Comment by FlarumHostingCo** [comment]
@Daemonmatrix gyms still don't load for me after your changes

**Comment by Daemonmatrix** [comment]
Wait so you list them directly on https://cdn.xxxxxxxxxxxxx.com/ and not https://cdn.xxxxxxxxxxxxx.com/forts/
?

**Comment by FlarumHostingCo** [comment]
Correct

**Comment by FlarumHostingCo** [comment]
in jave console it is saying unfound and the url is  https://cdn.xxxxxxx.com/undefined_8.png Failed to load resource: the server responded with a status of 404 ()

**Comment by Daemonmatrix** [comment]
any chance of sharing the domain so i can try to replicate?

and you downloaded the new files right?

**Comment by FlarumHostingCo** [comment]
can you PM me and I'll give you..  Don't want to draw extra attention to my site of whom could be lurking.   I followed you so you can message me

**Comment by Daemonmatrix** [comment]
I'm on the pokemongodev discord

**Comment by primaxius** [comment]
-1 conflicts and kinda pointless

**Pull request closed without merging**
