### PR TITLE
fixed lured pokemon not showing up

### LINKED ISSUE #131: No pokemon icons for Lured Pokestops
## Expected Behavior

Show pokemon icon from lured pokestops on map.
Wild pokemons are working normaly
## Current Behavior

captura de tela de 2016-08-08 08 37 51
captura de tela de 2016-08-08 08 42 08

## Your Environment

* Version used: 9dd738b
* Environment name and version: Python 2.7.12
* Operating System and version: Ubuntu Server 16.04

### PR DESCRIPTION
**Pull request by Chlodochar**
## Description

After the linting was applied, some properties/fields related to lured pokemon were not named correctly. This fixes the issue by naming them correctly and using them as strings (instead of named references).

## Motivation and Context

Lured pokemon currently do not show up.

Balthamel:Assume this fixes #131
## How Has This Been Tested?

Looking at the map and seeing whether all pokemon show up.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by chuyskywalker** [comment]
lgtm

**Comment by invisiblek** [comment]
stupid landscape....

**Comment by Chlodochar** [comment]
(Hint, hint, wink, wink #201)

**Comment by blastagator** [comment]
This doesn't seem to make a difference for me.

**Comment by Chlodochar** [comment]
@blastagator Just to be sure, did you run `grunt build` and disabled cache?

**Comment by blastagator** [comment]
Derp - "npm cache clear" fixed it.  I had run the build but the cache got me.

Thanks, working now!

**Comment by Chlodochar** [comment]
@blastagator Great! Thanks for giving it a try.

**Comment by invisiblek** [comment]
bump. shipit?

**Comment by BaIthamel** [comment]
I'd +1 this

**Pull request merged**
