### PR TITLE
SSL Guide

### PR DESCRIPTION
**Pull request by rrbailey89**
## Description

Adds a detailed guide for setting up an SSL Cert.
## How Has This Been Tested?

My own PC
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

For those who are struggling to get SSL running.

### CODE REVIEW

**Comment by Becold** [comment]
Nice guide!

Is there an expiration date? If so, how do we renew it?

**Comment by rrbailey89** [comment]
@Becold the free cert is good for 1 year. Once it expires simply create a new certificate. There is no limit :)

**Comment by Becold** [comment]
Oh ok, i really doesnt know that. That's very cool !

Can you rename the file to ssl-guide.md
And use markdown to display the image ? Use https://stackedit.io/editor or https://jbt.github.io/markdown-editor/ if u need help with markdown.
Thank you!

(I already got my SSL Certificate. We need someone to test this guide.)

**Comment by rrbailey89** [comment]
@Becold I can do that tomorrow.  I would like someone to test.

**Comment by slideup-benni** [comment]
Why not let's encrypt?

**Comment by rrbailey89** [comment]
@slideup-benni let'sencrypt hardly had any support for Windows. The 3rd party apps all hardly support Windows either and not everyone uses apache, nginx, or iis,  so this guide is still helpful to the people who fall into that category.

**Comment by FrostTheFox** [comment]
Of course, but linux users would probably be better off using letsencrypt. Something to add in the future, though. I haven't followed the whole guide, but at a glance and having used startcom before, it seems accurate.

**Comment by FrostTheFox** [comment]
In fact, if you could add something somewhere that mentions letsencrypt being a better option for linux for the time being, that would be great.

**Comment by chuyskywalker** [comment]
35 steps! Woah. Let's encrypt with docker is, like...

```
docker run \
 -v .lego:/root/.lego
 -e 'CLOUDFLARE_API_KEY=tokenhere' \
 -e 'CLOUDFLARE_EMAIL=email@here.com' \
 zealic/letsencrypt-lego \
   lego -d domain.here.com --email email@again.com --accept-tos --dns cloudflare run
```

Then just reference the cert/key which show up in the `.lego` directory.

_(Of course, that's presuming you're on cloudflare for DNS; but lego supports a ton of other [dns providers]()https://github.com/xenolf/lego/tree/master/providers/dns)_

**Comment by rrbailey89** [comment]
@chuyskywalker ithe could be less steps... but I did my best to explain like the reader is 5.

**Comment by Cy4n1d3** [comment]
If you manage to set it up, [letsacme](https://github.com/neurobin/letsacme) works fine on windows and is python based.
I'm conducting automatic renewal of multiple certs with it.

I must agree however, it's not as easy to set up as web-based services like StartSSL.

**Comment by rrbailey89** [comment]
Made my changes. Hope its good to go now.

**Comment by chuyskywalker** [comment]
You really need to follow the contributing guide: http://pgm.readthedocs.io/en/develop/about/contributing.html

Right off the bat:
- The file name is wrong; it should end in `.md`
- The title is too long (it reads funny in the sidebar)
- There is no such thing as `[TOC]` (I don't know where you go thtat
- Most importantly, you haven't actually run the local server which will 100% show you if you've got everything right since it renders it for you.

The contribution is important, so I don't want you to feel disheartened, but at this stage, this can't be accepted as it because it's just plainly broken.

**Comment by Becold** [comment]
@chuyskywalker TOC means Table of content.
image

**Comment by chuyskywalker** [comment]
Not to sphinx. This is why you need to run the built-in local doc rendering server.

**Comment by rrbailey89** [comment]
@chuyskywalker I have changed the title and appended the .md (whoops). I however am on windows so as far as I know I cant run that `make` command to execute any sort of webserver.

**Comment by chuyskywalker** [comment]
I believe it comes with `make.bat build` as well, although I have no personally tested that. Should build a full static copy you can just navigate into an open in your browser.

**Pull request merged**
