### PR TITLE
Time Stamp for -ps

### PR DESCRIPTION
**Pull request by teknicsrx7**
## Description

Added a time stamp for each status message while using -ps that involves sleep so user can better keep track of when actions are expected to be taken or to look for possible freeze ups

## Motivation and Context

Just helps to keep track of what the workers are doing and when.

### CODE REVIEW

**Comment by chuyskywalker** [comment]
Not to be rude, but ew. There should be a better way to handle this more gracefully across the board. Check out #901 where I got tired of "username" being embedded in every damn message.

**Comment by teknicsrx7** [comment]
Suggestions? I find it useful to know when time related actions are occurring so I can monitor the situation. What's the point of saying "sleeping for 30 seconds" if you have no idea when that sleep started or will end? If there's a better way to implement it possibly point me in the right direction? I'm new and trying to get a hang of stuff so I'm starting small to get a hang of it.

**Comment by teknicsrx7** [comment]
Perhaps a column for "action Last Performed" with a time stamp that changes each time an action occurs?

**Comment by erikssonk** [comment]
@teknicsrx7 If time is important to show, I would do so in the start of each row. See mockup example below, just like you suggested. 

2016-08-22 13:58:21 - Worker 003 - Success: 9, Failed: 0, No Items: 8 - Waiting 3.195 seconds for scan delay
2016-08-22 13:58:21 - Worker 004 - Success: 8, Failed: 0, No Items: 8 - Waiting 3.145 seconds for scan delay
2016-08-22 13:58:21 - Worker 005 - Success: 7, Failed: 0, No Items: 9 - Waiting 3.152 seconds for scan delay
2016-08-22 13:58:21 - Worker 006 - Success: 8, Failed: 0, No Items: 8 - Waiting 3.2 seconds for scan delay
2016-08-22 13:58:21 - Worker 007 - Success: 6, Failed: 0, No Items: 9 - Waiting 3.198 seconds for scan delay
2016-08-22 13:58:21 - Worker 008 - Success: 5, Failed: 0, No Items: 10 - Waiting 3.19 seconds for scan delay
2016-08-22 13:58:22 - Worker 009 - Success: 6, Failed: 0, No Items: 9 - Waiting 3.207 seconds for scan delay
2016-08-22 13:58:22 - Worker 010 - Success: 6, Failed: 0, No Items: 9 - Waiting 3.207 seconds for scan delay
2016-08-22 13:58:22 - Worker 011 - Success: 7, Failed: 0, No Items: 7 - Waiting 3.121 seconds for scan delay
2016-08-22 13:58:22 - Worker 012 - Success: 6, Failed: 0, No Items: 8 - Waiting 3.193 seconds for scan delay
2016-08-22 13:58:22 - Worker 013 - Success: 7, Failed: 0, No Items: 7 - Waiting 3.192 seconds for scan delay
2016-08-22 13:58:22 - Worker 014 - Success: 4, Failed: 0, No Items: 9 - Waiting 3.198 seconds for scan delay
2016-08-22 13:58:22 - Worker 015 - Success: 5, Failed: 0, No Items: 8 - Waiting 3.21 seconds for scan delay
2016-08-22 13:58:22 - Worker 016 - Success: 5, Failed: 0, No Items: 8 - Waiting 3.212 seconds for scan delay

This would give a better understanding than "Sleeping for 30 sec at 2016-08-22 13:58:22" and it would be the time for last event occurred. Like they way you said  in your last post.

Imho - I think less is more, specially when it comes to logs (In file or on screen),  but time is one of those important things.

**Comment by teknicsrx7** [comment]
It would be much cleaner the way you've shown, I'd probably remove the date to keep it as time only to shrink it a bit, but it keeps everything looking uniform.

I agree about time, to me it's key when describing actions as happening for a certain time there should be a reference time.

**Comment by justsomedudeonthenet** [comment]
I have a variety of improvements to add to the status screen once #901 gets merged, including adding time stamps where relevant, better queue status, etc.

As for system uptime - on linux, use byobu, which shows a 2 line status at the bottom of the screen.

**Comment by teknicsrx7** [comment]
Great look forward to it once 901 happens

**Comment by justsomedudeonthenet** [comment]
#935 adds time information on sleep and a variety of other status improvements.

**Comment by teknicsrx7** [comment]
Nice I'll have to give it a run once I'm home

**Pull request closed without merging**
