### PR TITLE
Update pokemon.json

### PR DESCRIPTION
**Pull request by Omikakim**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

Adjusted the rarity of the Pokémon

Very Common
Common
uncommon
Rare
Very Rare
Special
Epic
Legendary

### CODE REVIEW

**Comment by FrostTheFox** [comment]
I agree with some of these, but some of them have been needlessly changed as well.

**Comment by SmartPappnase** [comment]
I updated this list locally to my personal likeing and restartet the server, however, the changes seam to be ignored in the browser. Does the notify grouping refer to a different file?

**Comment by Gagaro** [comment]
What did you use to determine the rarity ? Your location also affects the pokemon spawning, so rarity will depend on your location and won't be the same for everyone.

I also don't like the term you used. Is special better than rare? Or is rare better than special? Why remove Ultra Rare, which was easy to understand?

I agree that some of the rarities seem off, but I think adding a "Very Common" one would be enough. 8 rarities are a lot.

**Comment by Cronick** [comment]
@SmartPappnase You need to use "npm run build" again, as it makes a min version of the json file.

**Comment by Slivo-fr** [comment]
Agree with gagaro

**Comment by Romfrosk** [comment]
How will this affect my current db of over 1 million spawns

**Comment by tim95030** [comment]
The original rarities were grabbed based on spawn rates from a database. I really don't think adding these weird names makes any sense. I agree some of the things are not quite right from my original implementation. The hope was to eventually use the statistics to maybe run a task to update the rarities based on your location as the rarities are definitely heavily influenced by location. For example people see drowzees all the time in some places. By me there are maybe 1-2 per day. That is not common. I also heavily disagree on the term "special" this has absolutely no meaning. Also you will need to update all of the foreign languages if you make this change.

**Comment by JZ6** [comment]
Biased changes I guess, lets just keep the older labels

**Comment by SmartPappnase** [comment]
@Cronick Thanks a lot!!! now it works.

**Pull request closed without merging**
