### PR TITLE
Speed scheduler merge

### PR DESCRIPTION
**Pull request by Artifice**
Create new scheduler Speed scan, option -speed
Enhance ScannedLocation table to allow for minimal scanning to identify spawn points
Add gym and pokestop checking to 0/0/0 scans to allow rescanning after bad scans
Add last action time and location to worker status DB to use to prevent teleporting on program restarts
Add performance statistic reporting for -speed scan option
Add SpawnSighting db table to capture spawn sightings with times and time_til_hidden stamps for later use in identifying spawn types

### CODE REVIEW

**Comment by Artifice** [comment]
Description

Create new scheduler Speed scan, option -speed
Enhance ScannedLocation table to allow for minimal scanning to identify spawn points
Add gym and pokestop checking to 0/0/0 scans to allow rescanning after bad scans
Add last action time and location to worker status DB to use to prevent teleporting on program restarts
Add performance statistic reporting for -speed scan option
Add SpawnSighting db table to capture spawn sightings with times and time_til_hidden stamps for later use in identifying spawn types

Motivation and Context

Avoid banning due to worker teleports.
Reduce number of workers required to cover area
Enable smooth transition from hex scanning to spawn scanning

How Has This Been Tested?

Tested on my local machine. Regression tested running hex scan as well.

Types of changes

 New feature (non-breaking change which adds functionality)
 
Checklist:

X My code follows the code style of this project.
X My change requires a change to the documentation.
X I have updated the documentation accordingly.

**Comment by Artifice** [comment]
Flake8 fix done.

**Comment by smc87** [comment]
Hello, I read through your description but i was unsure, does this add separate queues for each worker or do they all still pull from a single queue?

If you have added separate queues what do you think about including this:
https://github.com/PokemonGoMap/PokemonGo-Map/pull/995/

This clusters workers into geographical locations..you could then apply your logic to further ensure speed limitation.
This would help reduce/complete remove any long delays where a worker is trying to scan too far from its last location. I have also found that it is the best way to combat 0/0/0 returns from softbans when scanning a huge area.

**Comment by Artifice** [comment]
Smc87,

This uses a single queue for all workers, but instead of using a deque and having each worker pull off the next target only, each worker evaluates all valid (after start and before end) spawns near them, and chooses to go to the closest one.

There is not long delays/skipping, since each worker looks for the closest spawn.

Clustering isn't necessary, since each worker ends up heading off into a different direction, and then catches all the spawns near him. Also, it's more efficient, since some area will have more or less spawn points, and the workers will naturally help busier areas if there are no spawn points closer to them.

**Comment by smc87** [comment]
Oh, very interesting! Sorry I had misunderstood.
I will test this soon, it sounds great!

**Comment by kbtbc** [comment]
I'm very interested in this.  What if you have already scanned spawnpoints -- will it use the existing spawn points?   Will this work with loading accounts from a .csv file allow 'spare' accounts?   

Are the conflicts easily fixed?

**Comment by Artifice** [comment]
This PR and it's functionality is included in [PR#1501](https://github.com/PokemonGoMap/PokemonGo-Map/pull/1501), which adds spawnpoint indentification, and is compatible with the dev code after the .44 API update. Closing this PR in favor of that one.

**Pull request closed without merging**
