### PR TITLE
[DO NOT MERGE] Please enable GitHub issues!

### PR DESCRIPTION
**Pull request by shark0der**
Please enable GitHub issues!

### CODE REVIEW

**Comment by hhu94** [comment]
We'll discuss it in the core team in detail tomorrow, please be patient with us as it's a new (re)launch.

**Comment by danieliser** [comment]
@sharkuder - I imagine this would not be a good idea at the moment. Too many people use issues to create help support tickets. If you have visited the discord help channel in the last 24 hours you will know that there would have been 100s or even 1000s of issues added last night alone by people desperate to get it working for themselves.

**Comment by shark0der** [comment]
I see. I guess for now devs should use discord? How about those who don't
have access to the dev channel?

**Comment by marauder37** [comment]
#help

**Comment by shark0der** [comment]
Thank you!

**Comment by danieliser** [comment]
@shark0der And if you have a bug there is a dedicated bug channel. Same for dev I believe. They are accepting PR though if you have code to submit.

**Comment by shark0der** [comment]
Can you give me a link to the discord channel?

**Pull request closed without merging**
