### PR TITLE
History for spawn points and viewable area

### PR DESCRIPTION
**Pull request by snapper67**
## Description

Provide a way to view spawn history for a single spawn point or all spawns in a viewable area
## Screenshots (if appropriate):

screen shot 2016-10-02 at 11 16 54 pm

screen shot 2016-10-02 at 11 19 04 pm
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by palmercm** [comment]
This looks fantastic. Super useful. It would be great to be able to identify spawn points that consistently spit out specific pokemon.

Love it.

**Comment by F1delis** [comment]
This is very cool. Do we have the option to view the whole history of all spawned Pokemon of a spawnpoint? So not just a summary, but more like a log?

**Comment by Bart274** [comment]
any update on this PR?

**Comment by AdrienNguyenWorldline** [comment]
rebase would be nice

**Comment by sebastienvercammen** [comment]
We're cleaning up some old PRs that have been left around from before we had the time to handle everything properly. With the last few weeks going fantastically well, cleaning up the PR and issue queue will let us move forward again :) If this PR is still valid, don't hesitate to re-open and poke us.

**Pull request closed without merging**
