### PR TITLE
Release: 3.0.0

### PR DESCRIPTION
**Pull request by invisiblek**

### CODE REVIEW

**Comment by chuyskywalker** [comment]
Ah, yup, good point.

**Comment by invisiblek** [comment]
i was planning to ship this once we had all 3.0.0 milestones finished...

https://github.com/PokemonGoMap/PokemonGo-Map/milestone/1

**Comment by chuyskywalker** [comment]
Yeah, but I'd already tagged 3.0.0 on the releases page. We should probably change that milestones name to 3.1.0

**Comment by chuyskywalker** [comment]
....and so I did.

**Pull request merged**
