### PR TITLE
Decommission faulty accounts

### PR DESCRIPTION
**Pull request by Shibby7986**
Decommission faulty accounts

## Description
If an account produces errors replace it with a fresh account from an accounts buffer

## Motivation and Context
holes in map due to accounts no longer working

## How Has This Been Tested?
work in progress
Have tested the remove_account method and is working with manually passed variables

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by n3cr0cr0w** [comment]
How do you setup accounts in CSV, how does that work with multiple instances. I have several servers running 12 instances with 30 accounts each. This would help a great deal.

Did I miss something? I don't remember seeing CSV accounts outside of the beehive generator.

**Comment by Shibby7986** [comment]
Yeah, you use the accounts.csv from the beehive or create one.
you could have a common buffer of accounts for all the servers.

**Comment by Shibby7986** [comment]
I have to go to work but ill have a play later.
Any help is appreciated.

**Comment by n3cr0cr0w** [comment]
Would it not be better to make this a table? I put it up on feathub.

http://feathub.com/PokemonGoMap/PokemonGo-Map/+49

**Comment by Shibby7986** [comment]
I'll change it to use the DB

**Comment by BaIthamel** [comment]
And if you have more than one worker, they start pulling the same names from the db...

**Comment by tkSimon** [comment]
They could remove the account from db upon fetching it..

**Comment by Shibby7986** [comment]
yeah I was thinking flags for active and in use for all accounts
than it just pull an account that is active and not in use

**Comment by irus99** [comment]
I like where all this is going but I feel like first we should get it to just remove faulty accounts then we can add all of this other cool stuff to it. IMHO I would not want any accounts in reserve as I would want it to search as fast as possible so putting unused users in a database doesn't really make sense to me. But I would definitely love for this to remove faulty accounts when it happens.

**Comment by jccwright** [comment]
@Irus, keep in mind different people have different uses for all this. Not
everyone is a faster is best approach.

**Comment by IRus** [comment]
^ cc @irus99

**Comment by irus99** [comment]
@jccwright yeah I know and I agree with you, I was just giving my 2 cents :)

**Comment by Shibby7986** [comment]
@irus After I get this going I can probably setup an option to take accounts from other workers when there are none on standby. That way there are never idle accounts. It would shuffle the amount accounts per worker

**Comment by irus99** [comment]
@Shibby7986  Is the issue that you can't just close a thread when the account gets banned, so it needs to be replaced

**Comment by CtrlAltDefeat94** [comment]
Does it take soft bans/ip bans into account?

**Comment by n3cr0cr0w** [comment]
@Shibby7986 can you re-base your code for the database/accounts handling?

**Comment by Shibby7986** [comment]
@n3cr0cr0w not sure what you mean :/ git noob here
Do u mean move it out of models or make a separate branch or...

**Comment by n3cr0cr0w** [comment]
No, you already did it. I was asking for code that was updated to work on the newer version. A lot of changes happened since this was updated.

**Comment by Shibby7986** [comment]
@n3cr0cr0w  sweet :)
I moved this over to #1037

**Pull request closed without merging**
