### PR TITLE
Changed gym description to text field

### PR DESCRIPTION
**Pull request by zachbadgett**
## Description
Long description in gyms causes a 'data too long' error
```
2016-08-27 23:52:26,597 [ search-worker-0][        models][ WARNING] (1406, u"Data too long for column 'description' at row 3")... Retrying
2016-08-27 23:52:26,599 [ search-worker-0][        models][ WARNING] (1406, u"Data too long for column 'description' at row 3")... Retrying
2016-08-27 23:52:26,601 [ search-worker-0][        models][ WARNING] (1406, u"Data too long for column 'description' at row 3")... Retrying
2016-08-27 23:52:26,602 [ search-worker-0][        models][ WARNING] (1406, u"Data too long for column 'description' at row 3")... Retrying
2016-08-27 23:52:26,604 [ search-worker-0][        models][ WARNING] (1406, u"Data too long for column 'description' at row 3")... Retrying
2016-08-27 23:52:26,606 [ search-worker-0][        models][ WARNING] (1406, u"Data too long for column 'description' at row 3")... Retrying
2016-08-27 23:52:26,608 [ search-worker-0][        models][ WARNING] (1406, u"Data too long for column 'description' at row 3")... Retrying
2016-08-27 23:52:26,609 [ search-worker-0][        models][ WARNING] (1406, u"Data too long for column 'description' at row 3")... Retrying
2016-08-27 23:52:26,611 [ search-worker-0][        models][ WARNING] (1406, u"Data too long for column 'description' at row 3")... Retrying
2016-08-27 23:52:26,613 [ search-worker-0][        models][ WARNING] (1406, u"Data too long for column 'description' at row 3")... Retrying
2016-08-27 23:52:26,615 [ search-worker-0][        models][ WARNING] (1406, u"Data too long for column 'description' at row 3")... Retrying
2016-08-27 23:52:26,616 [ search-worker-0][        models][ WARNING] (1406, u"Data too long for column 'description' at row 3")... Retrying
2016-08-27 23:52:26,618 [ search-worker-0][        models][ WARNING] (1406, u"Data too long for column 'description' at row 3")... Retrying
2016-08-27 23:52:26,620 [ search-worker-0][        models][ WARNING] (1406, u"Data too long for column 'description' at row 3")... Retrying
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by djv2** [comment]
your fix replaced the too long error with 'Column 'description' cannot be null' error

[ WARNING] (1048, u"Column 'description' cannot be null")... Retrying

**Comment by CalcMan** [comment]
On my setup we just need a change to the database, not a change to the model:
mysql> alter table gymdetails modify description TEXT;

Though as a note, attempting to run that command while there exist workers (like a scanning docker container), seemed to cause the DB to just lock up. Had to turn off all the workers so the alter command was successful.

**Comment by zachbadgett** [comment]
@djv2 Try now?

**Comment by zachbadgett** [comment]
@CalcMan I went down the same path when I initially fixed it, however, a change in the model will automatically create the table with a LONGTEXT so the users won't have to run raw sql queries.

**Comment by djv2** [comment]
seems like a combination of implementing both @CalcMan + @zachbadgett has fixed it, thanks!!

**Comment by CalcMan** [comment]
Is the gymdetails.url field getting truncated too? I know we around using those links, but we might want to in the future, and it seems like we might be chopping off the ends.

**Comment by chuyskywalker** [comment]
I rebased and made the migration over on #1054

**Pull request closed without merging**
