### PR TITLE
Showing timers under each Pokémon

### PR DESCRIPTION
**Pull request by venimo**
For mobile users it's a huge thing to do more taps then just looking at their phone.
With this timer feature every Pokémon has his own timer till disappear.
## Description

For mobile users it's a huge thing to do more taps then just looking at their phone.
With this timer feature every Pokémon has his own timer till disappear.
## Motivation and Context

I believe that many users would love this feature, because they don't have to tap on a Pokémon first if they want to see the time.
## How Has This Been Tested?

I have it tested on a VPS. Running all well.
## Screenshots (if appropriate):

naamloos
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Albert62** [comment]
GREAT!

**Comment by FlarumHostingCo** [comment]
Will this still allow you to click on the Pokemon as well to view the more detailed information?

**Comment by venimo** [comment]
@FlarumHostingCo Ofcourse, there is only something added. **AND** I changed the way of showing the time: 12m12s > 12:12

**Comment by primaxius** [comment]
also please fix. 
screenshot_7
screenshot_6

**Comment by DiscoTim** [comment]
needs to be tested on the statistics page. statistics.html needs to include the js, because it calls setupPokemonMarker.

**Comment by MichalCerny** [comment]
Actually you ripoff this code and remove all author things and comments? Why? 👎  https://cdn.rawgit.com/googlemaps/v3-utility-library/master/markerwithlabel/src/markerwithlabel.js

**Comment by venimo** [comment]
Added back again, it was more beautiful that way, but it's back. @MichalCerny

**Comment by FlarumHostingCo** [comment]
@venimo 
29584506-89cb-11e6-8887-7d6c832f56e7
   Nothing loads on the map and console in the browser inspection tool gives the error

**Comment by venimo** [comment]
I'm on it!

**Comment by venimo** [comment]
Fixed the problem @primaxius @FlarumHostingCo

**Comment by shadi1989** [comment]
Can you make it "optional" in config.ini?

**Comment by FlarumHostingCo** [comment]
Working great now.  Thank you!

**Comment by venimo** [comment]
@shadi1989 Going to look for it now.

**Comment by shockler** [comment]
@venimo  : this is an android app?

**Comment by venimo** [comment]
@shockler No, it's just an addition for the PokemonGo-Map.

**Comment by taihun-at-somewhere** [comment]
I'd throw in if (map.getZoom() > 15) to switch between default marker and MarkerWithLabel() so that timer label only shows when zoomed in (I personally liked  > 15...)

**Comment by DiscoTim** [comment]
@venimo cool, i see you added it now.

**Comment by Samael27** [comment]
+1 for this PR, I'm wainting it :)

**Comment by shockler** [comment]
@venimo how can I change my map to use these icons? Can it make the map faster?

**Comment by venimo** [comment]
@shockler There should be an option to switch to those icons in the map. (Options > Style options)

**Comment by shockler** [comment]
On my map, there is no option to switch icon, only its size.

**Comment by totoberg123** [comment]
Works great!

**Comment by st0nec0ld** [comment]
Nice Pull, plz add IV example 12:08 90%

**Comment by Slivo-fr** [comment]
> Nice Pull, plz add IV > example 12:08 90%
Not in the scope of this PR I guess, and I disagree with this idea btw

**Comment by Samael27** [comment]
@st0nec0ld : I don't think it'll be very usefull and on mobile device I don't think you'll be able to see clearly all this stuff :/

**Comment by shockler** [comment]
@venimo I merged this PR but it doesnt work,

**Comment by jorgitoh** [comment]
@shockler I merged this yesterday and the PR works fine. But i dont know why I need to refresh the map manually

**Comment by SkOODaT** [comment]
love this PR but yes it needs a front end switch older devices seem to LAG with alot of timers onscreen zoomed out lol also this breaks the heat maps in statistics but ive allready came up with a temp fix ...
recreate the original setupPokemonMarker just under this PRs one in map.common.js and name it as below setupPokemonMarkerHM
```
function setupPokemonMarkerHM (item, map, isBounceDisabled) {
  // Scale icon size up with the map exponentially
  var iconSize = 2 + (map.getZoom() - 3) * (map.getZoom() - 3) * 0.2 + Store.get('iconSizeModifier')
  var pokemonIndex = item['pokemon_id'] - 1
  var sprite = pokemonSprites[Store.get('pokemonIcons')] || pokemonSprites['highres']
  var icon = getGoogleSprite(pokemonIndex, sprite, iconSize)

  var animationDisabled = false
  if (isBounceDisabled === true) {
    animationDisabled = true
  }

  var marker = new google.maps.Marker({
    position: {
      lat: item['latitude'],
      lng: item['longitude']
    },
    zIndex: 9999,
    map: map,
    icon: icon,
    animationDisabled: animationDisabled
  })

  return marker
}
```
then in statistics.js search for the 2 setupPokemonMarker functions and just rename them setupPokemonMarkerHM  (HM stands for heatmaps)

**Comment by brianprak** [comment]
I get the following error when i start the map: 2016-11-17 11:52:29,903 [      MainThread][        models][   ERROR] Your database version (10) appears to be newer than the code supports (9).
2016-11-17 11:52:29,903 [      MainThread][        models][   ERROR] Please upgrade your code base or drop all tables in your database.

**Comment by kevdotcom** [comment]
Can someone update this and maybe make it hide the timers below a certain zoom level?

**Comment by sebastienvercammen** [comment]
We're cleaning up some old PRs that have been left around from before we had the time to handle everything properly. With the last few weeks going fantastically well, cleaning up the PR and issue queue will let us move forward again :) If this PR is still valid, don't hesitate to re-open and poke us.

**Pull request closed without merging**
