### PR TITLE
Prevent virtual keyboard appearing with select boxes on touch devices

### PR DESCRIPTION
**Pull request by DiscoTim**
This PR prevents the virtual keyboard from appearing when interacting with selection boxes on touch devices.

## Description

This pr sets the selection boxes input to readonly. This prevents the selection boxes from being searchable on touch devices, however it also prevents the virtual keyboard from interfering.

It targets all touch devices however it could be refined to only target mobile os's with touch.

long standing issue with select2 https://github.com/select2/select2/issues/1541

## Motivation and Context

This change is required because the virtual keyboard interferes with selecting/deselecting items in selection boxes.

https://github.com/PokemonGoMap/PokemonGo-Map/issues/835

## How Has This Been Tested?

This has been tested on Windows FF and Chrome, and Android FF and Chrome. On windows it does nothing as expected, and on android the virtual keyboard does not appear as expected. 

## Types of changes

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by DiscoTim** [comment]
This is the best solution I've found so far.

**Comment by Studio-XP** [comment]
Works here on Chrome for Android

**Comment by TachyonRSA** [comment]
Works for me on Opera & Chrome on iOS.

**Comment by chuyskywalker** [comment]
That's two confirmations enough for me.

**Comment by Teelve** [comment]
I'm on Chrome for Android (Oneplus One with CM 13.1 Android 6.0.1) and the keyboard still appear (especially when I try to remove a pokemon from the hide list)

**Comment by Studio-XP** [comment]
Did you pull this from git clone or did you load it in by hand? If you modified it by hand, remember that any changes to map.js are not seen by the app, and need to be rebuilt with grunt build or npm build

**Comment by Teelve** [comment]
Damn, my bad, did a git pull, but forgot to do the npm install x)

**Comment by NoobDev3** [comment]
I believe this PR caused this: https://github.com/PokemonGoMap/PokemonGo-Map/issues/1133

**Pull request merged**
