### PR TITLE
Hex Scan: Pokepath Mod

### PR DESCRIPTION
**Pull request by chuyskywalker**
See #809; this is only part 1.

Old:

old

New:

new

New Really Big:

big

### CODE REVIEW

**Comment by Mr-Groch** [comment]
Don't like this as default... Waiting for scan all locations north of my position to scan nearby circle at south? I'm using map with often location changes, for personal use and few friends who also travel...

**Comment by chuyskywalker** [comment]
Yeah, I noticed that too; feels a bit odd, but logically doesn't matter. As long as each scan point gets covered once per loop, it doesn't really matter which order that is.

**Comment by averylarry** [comment]
Hard to think that is much of an issue if you have -st 2 or 3.  Any more steps than that and you should maybe be looking at multiple workers plus it might not be very efficient for location changes (and you risk teleports causing account bans).

Part 2 of this (I presume) relates to starting different workers at different points along the path (staying synchronized).  Thus another worker would be starting close to the end of the path, which is south of your location.

But from a very strict closest-to-me first scan philosophy with 1 worker this is worse.  Unless maybe the starting point is adjusted to 7 (I think) circles along the path before the exact center.  Then the very beginning of the scan would catch all of the 2 step radius before scanning anything on the 3rd step radius.  If that makes any sense.  (Though we might just be trying too hard at this point.)

**Comment by chuyskywalker** [comment]
Yes, the next part will be to split workers up to start at different points in the path, but that's a fairly significant changes (queue per worker thread instead of one larger shared queue).

Location changing always risks teleporting -- only a per-workers rate limiter can ever stop that. (which can/should be covered in a different 

> closest-to-me first scan philosophy with 1 worker this is worse

Again, no it's not. Your perspective is merely presentational. It doesn't matter if you scan "loop center out" or **any other pattern**. All that matters is that each point gets scanned in less than < 15 minutes. If you've got too much `-st` to cover that correctly in center-out, you'll have the same problem.

**Comment by averylarry** [comment]
No no no -- I understand.  I'm just saying if you don't scan a whole city and you don't do spawnpoint scanning and all you want is to know what you can walk to immediately -- say you're driving around and decide on a whim to stop at a park.  In that scenario -- at the very least you'll *feel* better if you move the marker to your location and it strictly spiral scans outward from your location and you know what's closest first before finding things farther away.  It makes a difference for the first 30 seconds or a minute or 2 only.

I wasn't clear in that I think it's a miniscule edge usage case that shouldn't really be considered -- I just wanted to acknowledge what I thought was a theoretical accuracy while basically saying it doesn't matter at all.

**Comment by chuyskywalker** [comment]
I see what you mean, but I'm inclined write it off as an edge case. We kinda cater to two types: scanning a huge damn city/area with fixed location turned on, or scanning a tight area that can follow a user like a personal scanner. In cases where it's used as the personal scanner, the step distance is usually much tighter such that this pattern isn't a huge problem.

Regardless, it would technically be a reduction in functionality, but one I'm willing to make for the tradeoff we'll get (in a few PRs) with offset, non-teleport scanning.

**Comment by chuyskywalker** [comment]
> Unless maybe the starting point is adjusted to 7 (I think) circles along the path before the exact center. 

Actually, I kinda missed that statement, and it makes good sense. I may try to work that in so that if the center moves, when it rescans you at least get some of the central area before it moves on to the general path.

**Comment by chuyskywalker** [comment]
Works awesome:

pokepath

**Comment by jnovack** [comment]
I am not against the "non-central" start.  I like it.

**Comment by MonjoNL** [comment]
I like this PR too.
Have a look at a part of #787 for an assigning individual locations to each worker example. Although this is slightly different. The start positions should be spread out the path but all workers will need all locations in their queue to complete the path.

**Comment by chuyskywalker** [comment]
@MonjoNL that's exactly what the next pr after this will do.

I've let this simmer enough, in it goes :)

**Comment by rrbailey89** [comment]
Is this a switch or command line argument?

**Comment by chuyskywalker** [comment]
It's the default.

**Comment by rrbailey89** [comment]
Good to go

**Comment by Silvanus0** [comment]
Actually wouldn't it be easier to just have one path, but the option to start half the workers in reverse order? That way you still do the center first?

**Comment by NGPriest** [comment]
Is there a limit of workers that can do this? :S

**Comment by OverlordPhaethon** [comment]
@NGPriest Chuy stated above, in response to Monjo, that the next PR will allow multiple workers. If you try it now, your workers will follow the new path sequentially (worker 1 pos 1, worker 2 pos 2...), and depending on how large your step size is and how many workers you dedicate, they will cover great distances in a short amount of time (teleporting). That being said, I tried it anyway and it's amazingly fast, if you're willing to sacrifice accounts.

Love this method. Soon we will have no more multiple instance beehive for fear of teleporting, just one large step size to dump workers in and maybe one smaller to follow you outside your boundaries. Great work everyone.

**Comment by NGPriest** [comment]
@OverlordPhaethon Sorry about that, didn't read most of the above, just skimmed and missed it.
Thanks for answering :D

**Comment by springjools** [comment]
I like this. The less obvious movement probably makes it harder to flag as a bot, but maybe I'm thinking it from our perspective and not from theirs

**Pull request merged**
