### PR TITLE
New classified pokémon

### PR DESCRIPTION
**Pull request by Omikakim**
--- Very Common ---
Caterpie
Weedle
Pidgey
Rattata
Ekans
Sandshrew
Nidoran(Female)
Nidoran(Male)
Zubat
Geodude
Bellsprout
Machop
Poliwag
Mankey
Meowth
Venomoth
Paras
Oddish
Slowpoke
Magnemite
Gastly
Krabby
Voltorb
Goldeen
Magikarp
Eevee

--- Common ---

Bulbasaur
Charmander
Squirtle
Metapod
Kakuna
Pidgeotto
Raticate
Spearow
Arbok
Psyduck
Persian
Diglet
Golbat
Jigglypuff
Vulpix
Clefairy
Sandslash
Pikachu
Growlith
Abra
Machoke
Tentacool
Graveler
Ponyta
Magneton
Doduo
Seel
Koffing
Hitmonlee
Cubone
Exeggcute
Electrode
Drowzee
Haunter
Shellder
Grimer
Rhyhorn
Horsea
Staryu
Jynx

--- Uncommon ---
Butterfree
Fearow
Nidorina
Nidorino
Wigglytuff
Gloom
Parasect
Dugtrio
Kabuto
Golem
Tentacruel
Machamp
Kadabra
Poliwhirl
Chansey
Primeape
Golduck
Dratini
Dodrio
Cloyster
Scyther
Hypno
Seadra
Seaking
Starmie

--- Rare ---
Beedrill
Pidgeot
Weepinbell
Pinsir
Snorlax
Mr. Mime
Farfetch'd
Onix
Exeggutor
Muk
Arcanine
Rapidash
Rhydon
Kingler
Magmar
Flareon
Jolteon
Tangela

--- Very Rare ---
Gyarados
Lapras
Vaporeon
Kabutops
Ivysaur
Charmeleon
Wartortle
Porygon
Omanyte
Dragonair
Raichu
Nidoqueen
Nidoking
Vileplume
Gengar
Marowak
Dewgong
Kangaskhan
Victreebel
Electabuzz
Alakazam
Poliwrath
Venomoth

--- Epic ---

Aerodactyl
Venusaur
Charizard
Clefable
Tauros
Omastar
Dragonite

--- Legendary ---
Ditto
Articuno
Zapdos
Moltres
Mewtwo
Mew

### CODE REVIEW

**Comment by TachyonRSA** [comment]
Was the notifications updated as well?

**Comment by beccasafan** [comment]
Where does this classification grouping come from?

**Comment by BaIthamel** [comment]
Why have you made two PR's?

**Comment by aldarund** [comment]
On what this rarity classification is based? For example for me half of this list could be reversed. Doesnt make much sense. https://github.com/PokemonGoMap/PokemonGo-Map/pull/686 here a better approach

**Comment by DiscoTim** [comment]
these rarities should really have numeric or 'static' keys, and translated for the ui from that.

**Comment by TheNewDarkOne** [comment]
What Alardund said. half the ones on the very common are actually uber rare here. So this list is entirely subjective to your area/opinion.

**Comment by xioxxio** [comment]
In different areas/countries these lists will differ on commonality.  It s a useless exercise.

**Comment by BaIthamel** [comment]
Without some proper followup i'm going to close this for the above reasons. If you want to ask me about it I'm on Discord most days.

**Pull request closed without merging**
