### PR TITLE
Added account recycling for Accounts parsing "No Items".

### PR DESCRIPTION
**Pull request by kvangent**
## Description

If an account his a consecutive number of empties below, puts the account to sleep or 2 hours and gets a new account from the queue. You can specify the number of empties required with `--max-empties`.
## Motivation and Context

Addresses #1473.
## How Has This Been Tested?

I've been running this on a Ubuntu 64x Server VM for around an hour with no issues.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mew905** [comment]
line 445 in search.py "time.sleep(5);"
is the semicolon necessary? Implementing this and with my limited python knowledge I cant be sure, but it doesn't look right. Perhaps too much time in PHP?

**Comment by SkOODaT** [comment]
This is just a beginning, we still need a way to view accounts that have gotten the captcha and to solve it to put them back into rotation

**Comment by BaseCamp888** [comment]
Agreed but is a good quick fix to keep things running, I say merge asap and fix/improve when can.

**Comment by Obihoernchen** [comment]
works fine here

**Comment by iluretar** [comment]
i only need like 30-40 accounts for my map but have like 300, could this be used to put all 300 accounts and only use 30-40 and get new ones when they start to fail?

**Comment by thatsweater** [comment]
@iluretar You can do this with -ac, check the wiki

**Comment by iluretar** [comment]
@thatsweater i was using --accountcsv in my config.ini but i was missing --workers, thanks.

**Comment by mew905** [comment]
should have an if statement like if args.max-empties > 0 then check for account swaps.
I found this to be an issue with my gym scanner, with the "only parse new gyms/stops/pokes" a lot of the gym scans come up empty, and it thus tries to swap them out. That way I can set max empties to 0 (infinite) so my gym scanners don't get reduced to a single account. :) Just realized this now

**Comment by Darkknightz** [comment]
Would be awesome if a non 0/0/0 resets the counter you are checking for max-empties. To reduce the chance of false positive.

**Comment by Darkknightz** [comment]
@mew905 "only parse new gyms/stops/pokes" if you are talking about #1303, it's still sending the appropriate finds even though it didn't insert it into the database. And gyms are always inserted (updating last_scanned)

**Comment by F1delis** [comment]
Works very well, this is an important change. Had so many empty scans and no solution for this.
What exactly causes an empty scan and how can we avoid it?

**Comment by Lukiido** [comment]
How do I git pull and merge this into my current install?

**Comment by Arengo** [comment]
I have issues that no new accounts are pulled from "-ac" file, when --max-empties is reached. "-w" is specified and below "-ac" file's amount of account.

**Comment by Mattyx89** [comment]
runserver.py: error: unrecognized arguments: --max-empties

Help :(
I updated all of the map file, but I keep getting this error.
How can I fix?

**Comment by Arengo** [comment]
@Mattyx89 in my config.ini file the "max-empties: X" for X being an integer, didn't work out for me, too. However I managed to get it working with "-me X" for X being an integer, in any process I run.

**Comment by Mattyx89** [comment]
@Arengo I tried to insert max-empires in config.ini but continue does not work :(

**Comment by Obihoernchen** [comment]
Guys fix your typos -.-

**Comment by Mattyx89** [comment]
@Obihoernchen I misspelled it only on the thread. Still not working

**Comment by Obihoernchen** [comment]
It's a dash not an underscore

**Comment by SkOODaT** [comment]
Works great for me besides no way to solve the captchas easily lol

**Comment by Mattyx89** [comment]
Ok I also solved. Solution found by loading the new utlis.py

**Comment by m4rtint** [comment]
Is there any indication when an account has replaced a worker after hitting the empty threshold??

**Comment by Arengo** [comment]
@m4rtint I don't think so. I also just see them chillin' in my status page when hitting those 0,0,0.

**Comment by jnovack** [comment]
Noooo..  Accounts need to be in the database, not on the command line. 

For those running an army of scanners, the central repository is the database. In fact, most scanner armies need their configs in the database.  But that's a different topic.

To address this one, the scanner should be pulling the most cold account (however you want to identify it as such, `last_scanned` if you will) from the database and use those credentials.  When it fails, throw it back in, add a `needs_captcha` flag, and pull the next cold account.

Pros:

* ZERO command line arguments. 
* Hot removal/additional of accounts.
* Army does not have to be restarted to change accounts.

Cons:

* A little more work than 3 lines of code.

**Comment by Darkknightz** [comment]
This was great (while the map was working)

**Comment by Badiboy** [comment]
Allready implemented here: https://github.com/PokemonGoMap/PokemonGo-Map/pull/1235

**Comment by neskk** [comment]
I've merged this PR with current develop branch and worked out this solution which I think works out.

`@@pogom/search.py - line 442
                if consecutive_empties >= 2:
                    captcha_url = captcha_request(api)

                    if len(captcha_url) > 1:
                        if args.captcha_solving:
                            status['message'] = 'Account {} is encountering a captcha, starting 2captcha sequence'.format(account['username'])
                            log.warning(status['message'])
                            captcha_token = token_request(args, status, captcha_url)

                            if 'ERROR' in captcha_token:
                                log.warning("Unable to resolve captcha, please check your 2captcha API key and/or wallet balance")
                                account_failures.append({'account': account, 'last_fail_time': now(), 'reason': 'catpcha failed to verify'})
                                break

                            else:
                                status['message'] = 'Retrieved captcha token, attempting to verify challenge for {}'.format(account['username'])
                                log.info(status['message'])
                                response = api.verify_challenge(token=captcha_token)

                                if 'success' in response['responses']['VERIFY_CHALLENGE']:
                                    status['message'] = "Account {} successfully uncaptcha'd".format(account['username'])
                                    log.info(status['message'])

                                else:
                                    status['message'] = "Account {} failed verifyChallenge, putting away account for now".format(account['username'])
                                    log.info(status['message'])
                                    account_failures.append({'account': account, 'last_fail_time': now(), 'reason': 'catpcha failed to verify'})
                                    break
                                time.sleep(1)
                        else:
                            status['message'] = 'Account {} empty more than 2 scans and is encountering captcha. Switching accounts...'.format(account['username'], args.max_empties)
                            log.warning(status['message'])
                            account_failures.append({'account': account, 'last_fail_time': now(), 'reason': 'captcha'})
                            time.sleep(1)
                            break
                if consecutive_empties >= args.max_empties:
                    status['message'] = 'Account {} empty more than {} scans; possibly encountering captcha. Switching accounts...'.format(account['username'], args.max_empties)
                    log.warning(status['message'])
                    account_failures.append({'account': account, 'last_fail_time': now(), 'reason': 'captcha'})
                    time.sleep(1)
                    break`

The logic is: if I get 2 consecutive and I have 2captcha > uses new code from master to process captcha. If I don't have -cs enabled (captcha solving) and I'm still getting a captcha, then it should shutdown account.
If, for some reason, I'm getting empty results but not receiving captcha, when consecutive_empties reaches the value set in --max-empties  the account gets rotated as this PR intended.
This means you can use the map without 2captcha and still don't worry about having 100 workers getting empties but not stopping - which can itself be flagged server side.

**Comment by AdrienNguyenWorldline** [comment]
Please rebase on current master

**Comment by onilton** [comment]
@kvangent Seems this branch could use a squash. Are you still interested in this? If you're not, I can open another pull request squashing the commits to try to get this merge into with the mainteners. I think this is very nice and should be in develop =/.

**Comment by kvangent** [comment]
@onilton If the developers wish, they can squash and pull in one click. Since they have not reached out to me, they probably have something else in mind.

**Comment by sebastienvercammen** [comment]
We're cleaning up some old PRs that have been left around from before we had the time to handle everything properly. With the last few weeks going fantastically well, cleaning up the PR and issue queue will let us move forward again :)

If this PR is still valid, don't hesitate to re-open and poke us, but this functionality has since been implemented in the map.

**Pull request closed without merging**
