### PR TITLE
Partially account for invalid TTH values

### PR DESCRIPTION
**Pull request by averylarry**
## Description
Set disappear time = 1/1/1900 when TTH is unknown and no previous valid TTH values
have been recorded for the spawnpoint.
Add argument -dt, --default-spawn-timespan to indicate what timespan should be used
for unidentified spawntypes.  Currently uses a default of 30 minutes since 30 minute spawns
seem to be prevalent now where 15 minute spawns used to be heavily most common.
Changes the front end to provide more information regarding the status of spawns
and spawnpoints.
Does not identify spawntypes.
Does not change the DB schema.
Does not include a kitchen sink.

## How Has This Been Tested?
Poorly, hah.

## Screenshots (if appropriate):
image

image

image

image

### CODE REVIEW

**Comment by averylarry** [comment]
And let the Travis errors begin.

**Comment by Janglinator** [comment]
Some of those errors aren't actually your fault, #1563

**Comment by dubidios** [comment]
How can I install this modification?

**Comment by averylarry** [comment]
Rebased to PR #1570

**Pull request closed without merging**
