### PR TITLE
Queue refresh speed

### PR DESCRIPTION
**Pull request by Artifice**
**** Warning -- will upgrade your DB to version 11 ****
Recommended to back up DB before using

* Change DB scheme of ScanSpawnPoint to use foreignkeyfield instead of a char field. This significantly increases the speed to refresh the queue.
* Fix for categorizing 30 min spawns as 15 min spawns due to not checking
duration on last band scan
* Fix to prevent found TTH from being overwritten during migrations when
* Niantic sets all TTH to migration start time
* Minor text fixes

## Description
Drop the old ScanSpawnPoint table which links spawn points to scans, and recreate the table again using a foreign key field, so looking up spawn points within scanned locations will be faster. Table is re-populated by doing distance checks. No Initial scan or TTH data is changed or lost.

## Motivation and Context
People with slower DB connections reported long pauses when Speed Scheduler would show Nothing to Scan while the overseer refreshed the queue. This should fix that.

## How Has This Been Tested?
Tested on my local machine with both SQLite and MySQL

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Artifice** [comment]
Code from PR#1617 got mixed in, so will re-open with clean code.

**Comment by Artifice** [comment]
Currently having errors on MySQL like this:

`[ WARNING] (1451, u'Cannot delete or update a parent row: a foreign key constraint fails (`pokemongomapdb`.`scanspawnpoint`, CONSTRAINT `scanspawnpoint_ibfk_2` FOREIGN KEY (`spawnpoint_id`) REFERENCES `spawnpoint` (`id`))'). Data is:
2016-12-13 20:13:34,366 [    db-updater-0][        models][ WARNING] [(u'6018118ec4f', {'kind': 'hhhs', 'last_scanned': datetime.datetime(2016, 12, 13, 11, 13, 33, 15000), 'links': u'????', 'longitude': 19.623015407632, 'missed_count': 0, 'latest_seen': 812, 'latitude': 3.4394411137076, 'id': u'60185c8ec4f', 'earliest_unseen': 1621}), (u'60115c8edbf', {'earliest_unseen': 1652, 'latest_seen': 812, 'kind': 'hhhs', 'last_scanned': datetime.datetime(2016, 12, 13, 11, 13, 33, 15000), 'links': '????', 'latitude': 325.43920923240618, 'id': u'60185c8edbf', 'longitude': 19.62261703162517, 'missed_count': 0})]`

Anyone good with DBs that can help fix this so we can use Foreignkeys in Pogomap?

**Comment by divnotded** [comment]
InternalError: (1054, u"Unknown column 't1.scannedlocation_id' in 'field list'") It seems it is not updating the DB

**Comment by shockler** [comment]
@Artifice i got some errors about Foreing Key too.

**Comment by Artifice** [comment]
@shockler Fixed the foreign key errors. Had to turn off FOREIGN_KEY_CHECKS on MySQL, because it apparently is unable to recognize strings to update unicode keys for foriegn key fields, thus giving of foreign key constraint errors

**Comment by smint86** [comment]
It's running great for me and overall speed seems to have increased.

**Comment by Artifice** [comment]
Latest commit:
* Fix for categorizing 30 min spawns as 15 min spawns due to not checking
duration on last band scan
* Fix to prevent found TTH from being overwritten during migrations when
Niantic sets all TTH to migration start time
* Minor text fixes

**Comment by hagehg** [comment]
@Artifice this still gives me foreign key errors. See #1637. Any idea?

**Comment by bellowsj** [comment]
@Artifice - Found a spawn point that is not correct. According to the scanner it's an hour long spawn but went there for a lapras today and it was not there. I'm 100% sure I was on the correct spot. Could see the spawns around it but no Lapras where it should be: Looking at the db I noticed that this spawn point only has 7 entries in the spawnpointdetectiondata column and none of them seem to include a TTH.

mysql> select * from spawnpointdetectiondata where spawnpoint_id = "875212c46e3";
+-----------------------------------+------------------------------+---------------+---------------------+----------+
| id                                | encounter_id                 | spawnpoint_id | scan_time           | tth_secs |
+-----------------------------------+------------------------------+---------------+---------------------+----------+
| MTA0MjQwNjQxMTc0NTM2MDE4Mw==_2808 | MTA0MjQwNjQxMTc0NTM2MDE4Mw== | 875212c46e3   | 2016-12-16 20:46:48 |     NULL |
| MTcwMDg2NDQzNjMzODQ3NzMzMDQ=_1403 | MTcwMDg2NDQzNjMzODQ3NzMzMDQ= | 875212c46e3   | 2016-12-16 19:23:23 |     NULL |
| MTcwMDg2NDQzNjMzODQ3NzMzMDQ=_2085 | MTcwMDg2NDQzNjMzODQ3NzMzMDQ= | 875212c46e3   | 2016-12-16 19:34:46 |     NULL |
| MTI1MjY3ODk0OTEzNzIxODUzOTY=_2093 | MTI1MjY3ODk0OTEzNzIxODUzOTY= | 875212c46e3   | 2016-12-16 22:34:54 |     NULL |
| MTI1MjY3ODk0OTEzNzIxODUzOTY=_3494 | MTI1MjY3ODk0OTEzNzIxODUzOTY= | 875212c46e3   | 2016-12-16 21:58:15 |     NULL |
| MTI1MjY3ODk0OTEzNzIxODUzOTY=_563  | MTI1MjY3ODk0OTEzNzIxODUzOTY= | 875212c46e3   | 2016-12-16 22:09:24 |     NULL |
| MTI1MjY3ODk0OTEzNzIxODUzOTY=_568  | MTI1MjY3ODk0OTEzNzIxODUzOTY= | 875212c46e3   | 2016-12-16 22:09:28 |     NULL |
+-----------------------------------+------------------------------+---------------+---------------------+----------+
7 rows in set (0.11 sec)

mysql> select * from spawnpoint where id = "875212c46e3";
+-------------+------------------+-------------------+---------------------+------+-------+--------------+-------------+-----------------+
| id          | latitude         | longitude         | last_scanned        | kind | links | missed_count | latest_seen | earliest_unseen |
+-------------+------------------+-------------------+---------------------+------+-------+--------------+-------------+-----------------+
| 875212c46e3 | 40.6897610717526 | -111.458190762275 | 2016-12-18 07:12:03 | ssss | +++-  |            0 |         564 |             564 |
+-------------+------------------+-------------------+---------------------+------+-------+--------------+-------------+-----------------+

Shouldn't at least one of the spawnpointdetectiondata rows have a TTH that is not NULL?

**Comment by onilton** [comment]
@Artifice There still some spawnpoints that are 30 min and are being recognized as 15 min. Iit's not a lot like before, but it is still significant. More than 50% of my 15min spawpoints are actually 30 min. How can I help with this?

**Comment by filippounitn** [comment]
how to drop ScanSpawnPoint table with sqlite?
Tried to ask on discord but all I got was to drop the whole database and rescan everything.
Do I really need to do that?

**Pull request merged**
