### PR TITLE
Add feature #1257: Ignore to parse the Pokemon by IDs

### PR DESCRIPTION
**Pull request by Spiritvn**
It's good idea for people who's scanning large area and want to avoid large database input. We can ignore almost common Pokemons.
- Feature request: https://github.com/PokemonGoMap/PokemonGo-Map/issues/1257
## Description

- runserver.py: add info on ignore list running
- utils.py: Add -igl / --ignore-list config, validate values and store the ignore list by Set
- models.py: Check if Pokemon ID not in the ignore list, because the ignore list default empty so we dont need option to enable/disable. Who want to enable just need to input in the list.
- config.ini.example: Add sample line
## How Has This Been Tested?

- Add pigey, rattata ID to the list, no hide pokemon and see the screenshot

## Screenshots (if appropriate):

ignore-list
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by justsomedudeonthenet** [comment]
Personally I prefer to have all the statistical data, but I can see why some people would want this.

Beware though - you may not be able to get proper spawnpoint data from a database that is using this feature.

**Comment by gabrielsoldani** [comment]
Yeah, I don't know why anyone would want to throw away data about a Pokémon like that. Storage space is cheap, the Pokémon table is fairly optimized, and the front-end can already filter out specific Pokémon.

Anyway, I think this needs more polish: use a set instead of a list for faster lookups, use integers for the Pokémon ID, and validate the input.

**Comment by Spiritvn** [comment]
@justsomedudeonthenet @gabrielsoldani 

Nothing to disagree, i'm not going to use this but someone may need it as the request #1257 (Someone may not need or care about the spawnpoints but may have a limited resource vps). 

Anw, i'm just new to this so lack of standards, just implemented as @gabrielsoldani suggest:

1. Validate the list values
2. Change to use Set and Interger

**Comment by Dagothur** [comment]
@gabrielsoldani having 13k pokemon on my map at any given time is annihilating my data plan and (at least using the IV PR, not sure if main branch would be affected) is causing me some database headaches in terms of mysql crashing/getting killed and connection refused exceptions being thrown on my server instance and workers... i'm looking to this as a solution to cut the number of pokemon by 80-90% and hopefully alleviate both issues

**Comment by primaxius** [comment]
This would be a neat feature. You would not use this to prepare for spawn scanning but could use it afterwards. Will need to be tested with and without -ss enabled.

**Comment by Darkknightz** [comment]
@Dagothur your dataplan issues should be fixed with #1303

**Comment by sebastienvercammen** [comment]
We're cleaning up some old PRs that have been left around from before we had the time to handle everything properly. With the last few weeks going fantastically well, cleaning up the PR and issue queue will let us move forward again :) If this PR is still valid, don't hesitate to re-open and poke us.

**Pull request closed without merging**
