### PR TITLE
Fix finding spawnpoints when using -ss

### LINKED ISSUE #939: -ss not "finding" all the spawnpoints -- is it spawnpoint compression?
## Expected Behavior

Beehive scan shows n spawnpoints.  Using -ss should equally find n spawnpoints.
## Current Behavior

Using -ss "finds" fewer spawnpoints than exist in beehive.
## Steps to Reproduce (for bugs)

Is spawnpoint scanning compression on by default for -ss scanning?  #765 doesn't seem to have made it into dev branch.
In a small area, after clearing the database, I ran a -st 2 beehive for 2 hours:
runserver.py -l "my location" -st 2 -j -nk -ng

capture

There are 26 spawnpoints inside the beehive.  If you are conservative with edges, there are still at least 23 spawn points inside the beehive.  (Note the spawnpoints outside the scanned locations are from running -ss for a short period of time.)

When I then start a -ss session (without dumping a .json file), I get 17 spawn points to track:
runserver.py -l "my location" -st 2 -j -nk -ng
. . .
2016-08-22 14:07:18,375 [ search-overseer][        models][    INFO] Finding spawn points 2 steps away
2016-08-22 14:07:18,405 [      db-cleaner][        models][    INFO] Regular database cleaning complete
2016-08-22 14:07:18,469 [ search-overseer][        search][    INFO] Total of 17 spawns to track

If I increase to -st 3 (I read somewhere to +1 the steps for edge cases), I still only get 21 spawnpoints:
runserver.py -l "my location" -st 3 -j -nk -ng -ss
. . .
2016-08-22 14:11:52,065 [ search-overseer][        models][    INFO] Finding spawn points 3 steps away
2016-08-22 14:11:52,158 [ search-overseer][        search][    INFO] Total of 21 spawns to track

If I dump to a .json file it shows 17 or 21 depending on the step size, matching the above.

If not compression, could it be related to jitter?  I don't really know how since increasing to 3 steps should eliminate that as a possibility.  Plus it is consistent.  I always get 17 or 21.  I even tried -st 54 and it still only returned 21.
## Your Environment

* Version used: 0448f93
* Operating System and version (desktop or mobile): win7

### PR DESCRIPTION
**Pull request by averylarry**
## Description

Changes how the spawnpoint finder iterates through the list of spawnpoints to eliminate skipping some.
## Motivation and Context

Fixes #939
## How Has This Been Tested?

Ran -ss with --dump-spawnpoints and compared the resulting .json files using the orig. code and the new code.  Kept it small having done a beehive scan with -sd 2.  The new code finds more spawnpoints and the count matches what is visually seen on the gui.  The new code also did not have any duplicated spawnpoints.
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

(Hope I'm doing this right.)

### CODE REVIEW

**Comment by averylarry** [comment]
Looks like PR #951 would remove the code that this PR changes.

**Comment by gkuiper** [comment]
This PR works great for me, as it resulted in 40% more spawnpoints.

**Comment by MonjoNL** [comment]
In a new test I strip everything above 24 bits instead above 32 bits for the 595+ hour bug.
Looks promising, wil test it for a day or two.

**Comment by averylarry** [comment]
At this point my quick bug fix isn't quick.  I presume the commitment of #951 is imminent.  And if not some other enhanced version of this is coming and will eliminate the incorrect code.
Now if I can figure out how to close or delete this PR . . .

**Pull request closed without merging**
