### PR TITLE
webhook fix in config.ini

### PR DESCRIPTION
**Pull request by catnet23**
config.ini:
webhook: http://127.0.0.1 # for multiple webhooks [http://127.0.0.1:1345,http://127.0.0.1:12346]

commandline:
-wh http://127.0.0.1:1345 -wh http://127.0.0.1:12346

### CODE REVIEW

**Comment by PKMTracker** [comment]
Confirmed working from Config File after change.
~Smurfies

**Comment by kbtbc** [comment]
I confirm this works from command line using the stated format.  Launched two separate webhook ports, finds are going to both. -BigFun

**Comment by bluemode** [comment]
Can confirm this works! I have been using it for two days now, and not a single problem.

**Comment by bluemode** [comment]
Is this ready to merge now?

**Comment by callfbr** [comment]
Should be since day one. Was just a language typo

**Comment by PKMTracker** [comment]
Merge!

**Pull request merged**
