### PR TITLE
PokiiMap integration

### PR DESCRIPTION
**Pull request by kiideveloper**
PokiiMap can be used as a native android client to the server

## Description
added documentations about how to connect PokiiMap with the server

## Motivation and Context
PokiiMap provides a native android interface to the server

## How Has This Been Tested?
Yes

## Screenshots (if appropriate):
http://pokiimap.readthedocs.io/en/latest/livemap.html

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pyr0ball** [comment]
oh thank ghod finally someone built this

**Comment by pyr0ball** [comment]
@kiideveloper so I took some time to actually go through your app, and while the function to connect to a private server is a step in the right direction, It's not quite where it needs to be. I can't, for instance, use the notification service with the private map or request a new scan location if that's enabled on my map.

If possible I'd basically like to replace the phone's locally hosted search workers with the one I have hosted on my server, and use this app as a 1-to-1 dedicated front-end

**Comment by sebastienvercammen** [comment]
-1 to this PR.

While it's great that the PokiiMap dev has decided to add PokemonGoMap compatibility, linking to the app would imply we support the app itself, meaning people will come to us with their PokiiMap questions. It takes away from our focus on the map, so I recommend against it.

The app is also a bot (both pokémon catching and sniping), which is something we never support.

**Comment by kiideveloper** [comment]
@pyr0ball currently it's a view only, for people who want to share their server with others. management function will still need to be performed on the server

@sebastienvercammen  there's no botting feature in PokiiMap

**Comment by kiideveloper** [comment]
@sebastienvercammen and the current README links to an android app that has **AUTO ACCOUNT CREATION** , I would call that a bot . https://github.com/omkarmoghe/Pokemap

**Comment by sebastienvercammen** [comment]
@kiideveloper While the technical definition of a bot usually does include anything automated (e.g. account creation), the commonly used definition by our users is that of a "video game bot" as described by Wikipedia (to be used for automation to complete tasks in a game and/or gain an advantage). Account creation does not fall under this definition.

PokiiMap also definitely **is** a video game bot: it specifically lists **Catch pokemon** and **Pokemon Sniping** as its functionalities. You don't call a firearm "child-friendly" only because it doesn't hurt anyone as long as you _"don't load it and don't pull the trigger"_.

As for your other notes: yes, we do get questions regularly about environment, python, apache, MySQL/MariaDB, etc.

**Comment by kiideveloper** [comment]
@sebastienvercammen where the f*ck is the *automation* in PokiiMap? 

account creation is not "completing a task"? scanning for pokemon is not "completing a task"?

**Comment by pyr0ball** [comment]
@kiideveloper The difference is that your app can effect an individual account, giving it the ability to perform actions within the game that advance the account without needing to log into the native Pokemon Go app. That's where we draw the line. While that's an important distinction I wanted to explain, we also don't tolerate this kind of behavior, and by that reason alone we'll have to decline this request.

Good luck in your endeavors.

**Comment by FrostTheFox** [comment]
From a community manager, rather than a developer, we would not like to conduct business with the behavior you have exhibited in this PR.

Good day.

**Comment by kiideveloper** [comment]
@pyr0ball civil debate are welcome and respected, what I didn't like was the idiotic name calling and labeling. 

Best of luck with your endeavors as well.

**Pull request closed without merging**
