### PR TITLE
Add Lured Pokemon support

### PR DESCRIPTION
**Pull request by wobblybobz**
## Description

Add lured Pokemon to the map adapted from maddhatter PR1079.
Adding support for Encounters introduced in PR1272

The lured Pokemon is added to the pokemon table with a null spawnpoint_id. map.js marks Pokemon with no spawnpoint_id as lured on the info popup for the Pokemon. Other than the addition of "Lured Pokemon" to their popup, there is no front-end distinction between lured and normal Pokemon.
## Motivation and Context

Adding support for Lured Pokemon again
## How Has This Been Tested?

Tested on my running system with mariadb and with and without encounters enabled
## Screenshots (if appropriate):

screenshot from 2016-09-29 22-34-35
screenshot from 2016-09-29 22-34-47
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by beck** [comment]
For the sake of attribution, it would be nice if https://github.com/PokemonGoMap/PokemonGo-Map/pull/1079 lands before this one.

Or move your changes to their own commits and rebase this pull off of @maddhatter's

**Comment by manzarek123** [comment]
They don't merge if it is more than fixing typo in doc or in css

**Comment by kbtbc** [comment]
Does this pr work with spawnpoint scanning?

**Comment by wobblybobz** [comment]
Not at the moment, it is something that I am happy to work on getting added. Just need to workout how to add the pokestop locations to the spawnpoint scheduler while it is lured and how to get it to scan again for next lured pokemon a couple of seconds after the current one has timed out

**Comment by Flyin-Ryan** [comment]
Trying this out right now. It scans fine on any area that isn't lured, but when it scans a lured pokestop, I get this error. 
untitled

**Comment by beanhedge** [comment]
Any chance you could fix this for new api?

**Comment by wobblybobz** [comment]
Yeah, Will try and pump it out shortly

**Comment by wobblybobz** [comment]
Rebase done, Tested and still appears to be working

**Comment by SkOODaT** [comment]
anychance this could be setup to work with PR https://github.com/PokemonGoMap/PokemonGo-Map/pull/1530 i tried to get it to work togeather but just failed lol

**Comment by onilton** [comment]
@SkOODaT If you want I have a branch that I updated with #1530 and lured pokemon (and some other branches). But I warn you that I think #1530 won't be updated anymore.

https://github.com/onilton/PokemonGo-Map/tree/updated-lured-pokemon-with-1530

**Comment by SkOODaT** [comment]
@onilton awesome dude all i need is your modified commiti should be able to add it to my map i like 1530 better its less captchas ill redo my entire map after mapping goe down and if it ever comes back i thin this week and gen 2 will mark the end of it for a while again

**Comment by onilton** [comment]
I rebased this branch with the current develop branch and fixed the conflits. You can find the changes here:
#1633

**Comment by onilton** [comment]
@wobblybobz  Hi man. Do you still plan to work on this? If not, can you close this pull request?

**Comment by sebastienvercammen** [comment]
We're cleaning up some old PRs that have been left around from before we had the time to handle everything properly. With the last few weeks going fantastically well, cleaning up the PR and issue queue will let us move forward again :) If this PR is still valid, don't hesitate to re-open and poke us.

**Pull request closed without merging**
