### PR TITLE
Add append action to webhooks

### PR DESCRIPTION
**Pull request by invisiblek**

### CODE REVIEW

**Comment by Chlodochar** [comment]
`default=False` should be `default=[]`

**Comment by invisiblek** [comment]
looks like everything else was designed for this to be used this way, which is nice

**Comment by Chlodochar** [comment]
`nargs='*',` should be removed to make this work. Otherwise python will make a list of lists for `args.webhooks`. However, I do not know what the behavior was before this PR. Maybe `--webhook http://first/ http://second/ http://third/` was possible?

**Comment by rollin** [comment]
> Maybe --webhook http://first/ http://second/ http://third/ was possible?

It's the only way that works now actually.

**Comment by Chlodochar** [comment]
So, deprecate the previous method and use this pr instead? Personally I think `args=*` shouldn't be used at all, as it would be confusing when multiple options start accepting these.

**Comment by thatsweater** [comment]
I tried this out and it doesn't seem to work, PokeAlarm doesn't update as an example either with one or two webhooks.

**Comment by Chlodochar** [comment]
Did you try removing nargs?

**Comment by thatsweater** [comment]
Removing nargs makes a single webhook run, with normal syntax, if i try to run both, either in the way rollin suggested, or separated by commas, or as ["http://first","http://second"] under webhook: in config, program runs but neither webhook is detected.

**Comment by rollin** [comment]
I meant it works this way `-wh wh1 wh2` now, without this PR. Also it works only from the command line, I couldn't set up two webhooks from the config file at all.

**Comment by Albert62** [comment]
@rollin how where you able to do it?
I just tried this, but It doesn't work on command line

**Comment by justsomedudeonthenet** [comment]
Closing because it has merge conflicts and hasn't been updated in 22 days.  If this is still an issue feel free to resubmit an updated PR.

**Pull request closed without merging**
