### PR TITLE
Optimize stat heatmap

### PR DESCRIPTION
**Pull request by aldarund**
## Description
Dynamically load appearances times when its requested
Calculate number of pokemon on spawnpoint in python (mysql actually), not js. So no long arrays of data passed from backend, only lat long count spawnpoint_id.

## Motivation and Context
Because loading all location slow and transfer a lot of data.
## How Has This Been Tested?
my city map

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by aldarund** [comment]
Also fixes https://github.com/PokemonGoMap/PokemonGo-Map/issues/1001

**Comment by Zerotask** [comment]
I have 1.5 mio finds and I'm using MariaDB 10.1 and I don't notice any speed improvements.

It should bundle the requests.
image

**Comment by aldarund** [comment]
@Zerotask um. This pr  has nothing to do with page load.This is optimization for all location button. And it certainly dont do 142requests. There like 2 json requests to backend that are repeated every few seconds. 142 requests are for the images on the stat page.

**Comment by Zerotask** [comment]
oh the images, yeah right. I just hoped that this PR reduces the page load because, as you wrote, you load the appearances first when a heat map is requested. Maybe you want to look after my problem and how to reduce the page load

**Comment by aldarund** [comment]
@Zerotask hm  i was sure i wrote answer here, but seems like i didnt post it. I guess the main load time for stat page is a long db query that is counting all pokemons. For 142 request it should use same spite as main map.   But this pr begin to work when a all locations link clicked not before.

**Comment by justsomedudeonthenet** [comment]
**This makes heatmaps usable again**

Trying to load rattata heatmap for year without this patch:  Tries to transfer 20MB **every few seconds**

With this patch:  Loads a few KB.  Incredibly fast, doesn't kill my internet, doesn't freeze my browser.

Merge this now pl0x!

**Comment by j16sdiz** [comment]
this is incompatible with sql_mode=only_full_group_by

**Comment by erikssonk** [comment]
Had the same as @j16sdiz needed to remove only_full_group_by to get this working.

**Comment by aldarund** [comment]
@j16sdiz @erikssonk will make a pr with fix today, good catch

**Pull request merged**
