### PR TITLE
Docker Fixups

### PR DESCRIPTION
**Pull request by chuyskywalker**
Combining a few things:

1. @tkSimon 's work for cleaner exit
2. @tkSimon 's also fixing up package install...mostly
3. Adding ENV hooks for EVERY CONFIG VALUE

Supersedes #930, #595, #590

### CODE REVIEW

**Comment by Ashex** [comment]
You don't need to add env_var for each argument. You can configure a global prefix that is picked up  automatically. I'd also vote for POGOM instead for the prefix ;-)

**Comment by chuyskywalker** [comment]
Damnit, where's the config setup for that?

**Comment by chuyskywalker** [comment]
nm, found it.

**Comment by Ashex** [comment]
I'm a little confused regarding dumb-init. It's in the pip requirements but is called as a command. Any reason it's not being installed via apk?

**Comment by chuyskywalker** [comment]
It's not `apk` instal;able... (is it?)

**Comment by Ashex** [comment]
Yep you're correct, I took a look and a package isn't available. Carry on!

**Comment by Ashex** [comment]
That said, it doesn't really belong in the requirements file since it's only used by the Dockerfile, it should be part of the run statement installing the base deps like git. 

(sorry about the double comments, I'm on my phone heading to the airport)

**Comment by chuyskywalker** [comment]
Agreed. Fixed.

**Comment by creatingwake** [comment]
Thanks @chuyskywalker - this is just what I'd been looking for as I'm running this in a dokku environment.  Big help.
I did try playing around with the code to get the config.ini file loaded instead of using ENV vars but couldn't get it working.  With multiple accounts dropping everything into the $EXTRA_ARGS ENV variable is a PITA.  

Do you know if its possible to replicate in Docker the native python install where the config file is read, but command line (ENV) vars take precedence?

**Comment by Ashex** [comment]
@creatingwake The order of precedence is thus: `command line > environment variables > config file values > defaults`

**Comment by creatingwake** [comment]
@Ashex yes, you would think so but the config.ini file values weren't being used at all on my dokku deployment. I had to replicate everything in ENV vars.  Hence I started hacking Utils.py (unsuccessfully)

**Comment by Ashex** [comment]
That is a bit curious, I've been able to override config.ini settings via argument. I'm not familiar with dokku but perhaps you need to verify the working directory it was running from.

**Pull request merged**
