### PR TITLE
set focus on password field in status page

### PR DESCRIPTION
**Pull request by simonbuehler**
always focus password field in status page

## Description
minor focus fix

## Motivation and Context
was really bothering me everytime

## How Has This Been Tested?
by me

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Dcstegg228** [comment]
What does this even mean?

**Comment by simonbuehler** [comment]
updated description to make it clear, its just saves me from always clicking into the password field before i can start typing

**Comment by Duplic1ty** [comment]
Pls merge this is gold

**Comment by simonbuehler** [comment]
@FrostTheFox please commit, this is a no brainer

**Comment by pve83** [comment]
simple nice, and works great pls merge this fox

**Comment by Bart274** [comment]
this is great, now it would be nice if we could somehow add a cookie for this status page so our login is kept?

**Pull request merged**
