### PR TITLE
Add Linux 32bit x86/ARM

### PR DESCRIPTION
**Pull request by marauder37**
Two more architectures. This is a WIP commit, the code will not pick these up automatically yet, need people with those archs to help modify the code

### CODE REVIEW

**Comment by EdenGottlieb** [comment]
This is exactly what I need! I have a 32 bit linux, how can I assist you?

**Comment by marauder37** [comment]
I will try and add some code to detect linux bitness and get you to test it out

**Comment by EdenGottlieb** [comment]
Tell me when to pull

**Comment by hasosoft** [comment]
You can look at [platform.architecture](https://docs.python.org/3/library/platform.html#platform.architecture)

**Comment by marauder37** [comment]
platform.architecture doesn't help with ARM vs x86

**Comment by marauder37** [comment]
I'm going to try elif os.uname()[4].startswith("arm") and platform.architecture()[0] == '32bit'

**Comment by marauder37** [comment]
@EdenGottlieb give that a go

**Comment by Gagaro** [comment]
For information, here is the output of os.uname() and platform.articheture() on my RPi:

```
>>> os.uname()
('Linux', 'raspberrypi', '4.4.13+', '#894 Mon Jun 13 12:43:26 BST 2016', 'armv6l')
>>> platform.architecture()
('32bit', 'ELF')
```

**Comment by marauder37** [comment]
Thanks @Gagaro , are you able to test the PR? My condition should work with your uname

**Comment by Gagaro** [comment]
I have another issue ATM:

```
2016-08-07 13:39:23,675 [ search_worker_0][        search][   ERROR] Exception in search_worker:
Traceback (most recent call last):
  File "/home/pi/PokemonGo-Map/pogom/search.py", line 219, in search_worker_thread
    check_login(args, account, api, step_location)
  File "/home/pi/PokemonGo-Map/pogom/search.py", line 266, in check_login
    api.set_authentication(provider = account['auth_service'], username = account['username'], password = account['password'])
  File "/home/pi/PokemonGo-Map/venv/src/pgoapi/pgoapi/pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError
```

**Comment by marauder37** [comment]
pip install --upgrade -r requirements.txt and make sure it fetches a new pgoapi

**Comment by EdenGottlieb** [comment]
I'm pulling

**Comment by Gagaro** [comment]
I think I just need to reinstall pgoapi, I'll try your PR just after.

**Comment by EdenGottlieb** [comment]
Seems to stall at
`2016-08-07 13:45:17,934 [ search_worker_0][connectionpool][    INFO] Starting new HTTPS connection (1): pgorelease.nianticlabs.com`
Maybe it's because it's too heavy (I'm running a Raspberry Pi A 1st gen with 256 MB of RAM), somebody else with 32 bit should try

**Comment by Gagaro** [comment]
It scanned once and then my RPi froze. But this one scan worked.

**Comment by Gagaro** [comment]
I have a B+.

**Comment by EdenGottlieb** [comment]
@Gagaro Probably two heavy, the new API probably requires a lot of processing power to bypass the new protections

**Comment by nsimons** [comment]
Can confirm that RPi B 1GB works with the 32bit ARM library.

**Comment by Gagaro** [comment]
I rebooted it and it works fine now.

**Comment by Gagaro** [comment]
Thanks for the fix @marauder37 :+1:

**Comment by EdenGottlieb** [comment]
Still stuck on RPi Model A+. Probably too old

**Comment by Mr-Groch** [comment]
>>> os.uname()
('Linux', 'Groch-NAS', '3.2.40', '#7393 Thu Jun 2 19:48:42 CST 2016', 'armv7l')

>>> platform.architecture()
('32bit', '')

This is Synology NAS.

When I start the script:

2016-08-07 17:43:07,101 [ search_worker_1][        search][ WARNING] Exception while downloading map: /volume1/homes/groch/PokemonGo-Map/pogom/libencrypt-linux-arm-32.so: internal error

Where can I find src for manual build of this lib?

**Comment by viperfx** [comment]
Can someone share a so for iOS? arm64, I believe.

**Comment by Alasio** [comment]
I'm running x64 ARM and needing to get the encrypt to work.

`>>> os.uname()                                                                                                                   ('Linux', 'localhost.localdomain', '3.10.65-7-pine64-longsleep', '#28 SMP PREEMPT Sat Apr 23 20:13:25 CEST 2016', 'aarch64')     >>> platform.architecture()                                                                                                      ('64bit', 'ELF')  `

Assistance would be greatly appreciated!

**Pull request merged**
