### PR TITLE
Add number of nearby to parsing log

### PR DESCRIPTION
**Pull request by averylarry**
## Description
Just added the number of nearby pokemon to the parsing log line.
## Motivation and Context
It's nice to know.  Also, if there are 0 pokemon and 0 nearby you can speculate that it is likely due to a speed limit violation.
With another PR this can also give context to 0/0/0 scans.
## How Has This Been Tested?
On my small windows system.  It's not much of a change.
## Screenshots (if appropriate):
capture

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by forcewill** [comment]
+1

**Comment by averylarry** [comment]
I did think about making it a little more clear:
Parsing found 1 wild Pokémon, 3 nearby Pokémon, 2 pokestops, and 5 gyms.
But I wasn't sure if wild would be confusing.
Parsing found 3 encounterable Pokémon, . . .
That sounds odd.
Parsing found 3 Pokémon that can be encountered, . . .
I figured I was just trying too hard at that point.

**Comment by Spurlex** [comment]
+1

**Comment by rhaj** [comment]
Please don't use diacritic, maybe fine in Windows but Linux sometimes hate it. So "Pokémon" is problem in Linux and I had to change it manually back in my server. It leads to errors in application log.

**Pull request merged**
