### PR TITLE
Tool to minimize overlapped spawnpoint scans

### PR DESCRIPTION
**Pull request by sf302**
Tool that works with spawnpoint data from MySQL-only databases to cover as many spawnpoints as possible with the fewest scans. Uses heatmaps surrounding each spawnpoint to find a point with the best coverage.

May trip teleport detection with large enough step sizes unless the order in the CSV is optimized either by hand or by something that solves traveling salesman problem and accounts for average speed.

## Description
Added script to Tools directory. Also added an option in utils.py to pass csv path, and added a section in search.py to replace generated locations with data loaded from csv.

## Motivation and Context
Drastically reduces number of scans in spawnpoint scanning modes. For the two locations I was personally running this with, 56 scans covered 204 spawnpoints and 50 scans covered 167 spawnpoints, respectively.

## How Has This Been Tested?
Originally wrote csv file input and this script (in PHP) for personal use weeks ago, ported over to Python today.

## Screenshots (if appropriate):
optimized

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by hklcf** [comment]
:+1:

**Comment by peter-bonanni** [comment]
I tested this and the tool works great however ~75% of my accounts I used in the test were softbanned for teleportation so I think it needs some work if being used with multiple accounts. The use case tested is a 2.8km radius with 2,750 spawn points to do an entire city with 300+ accounts through any of ~600 rotating IPs. 

As a data point with 10 heatmap slices it took ~1.5 hours to do the csv generation.

**Comment by sf302** [comment]
>As a data point with 10 heatmap slices it took ~1.5 hours to do the csv generation.

Ick that's painful. Not entirely unexpected though since it's a bruteforce approximation for a set cover problem across thousands of points.

For such a large step radius, it might be worthwhile to use the beehive generator tool to determine your centers using a small leapsize (3 or so?) and then running this tool for each location. You'd then pass the CSV for each beehive center to its respective worker to optimize the scans for each hex in that grid.

**Comment by JWess** [comment]
What do you think about his idea as an alternative:

Iterate through each spawn point. Only scan for that point if it does not fall inside a previous scan's radius. This would not be nearly as optimized as your solution, but it would work for any size set of spawn points, and it would not require any up-front computation. It would prevent what is seen in the attached screenshot.
image

**Comment by averylarry** [comment]
Are you modifying beehive scannning, spawnpoint scanning, or both?

**Comment by sf302** [comment]
Neither. As it stands this just adds a third option. The enhancements made to spawnpoint scanning would have created incompatibilities had I integrated into that.



On Thu, Aug 25, 2016 at 9:37 PM -0700, "averylarry" <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you modifying beehive scannning, spawnpoint scanning, or both?

-

**Comment by averylarry** [comment]
This would not account for spawn time, right?  It's a way of scanning fewer locations but you still cycle through them on a loop.  A better version of --spawnpoints-only.

JWess -- that looks like full spawnpoint scanning -ss.  The reason for the overlaps is that spawnpoint scanning scans each individual spawnpoint WHEN it spawns.  See PR #765 as a first step to reducing spawnpoint scans and there are several PRs talking about clustering and generally optimizing the spawnpoint scanning model.

**Comment by cecca00** [comment]
this may be very useful for gym scanning

**Comment by cecca00** [comment]
Hello, I tried running the script on gym locations, changing input table from pokemon to gym and splat from 70 to 900, and running `python spawncovergym.py --lat 46.1319 --lng  11.22716 -st 3 --slices 100` but I get bad results:
bad
good
red dots are the gyms, yellow circles the output of the script, green circles what i was expecting

**Comment by gabrielsoldani** [comment]
@cecca00 consider modifying the script from #990 which was merged into the develop branch.

**Comment by cecca00** [comment]
@gabrielsoldani this the result running the script you mentioned, it's good but still not optimal, got 8 scan locations instead of 7. This one from @sf302 is supposed to give better results, any idea on why it's not working for me?
tool

**Comment by gabrielsoldani** [comment]
@cecca00 Both algorithms find the local optimum, not the global optimum. #990  with spawn points and time windows the difference is normally very close (~3%), so it's good enough.

If you want the global optimum, shuffle the list of gyms and re-run the algorithm until you're satisfied with the results, or consider using a different algorithm (look into the [geoometric set cover problem](https://en.wikipedia.org/wiki/Geometric_set_cover_problem) if you want to dig deeper).

**Comment by krummrey** [comment]
Why does this still show up as a PR?
Looks like it has been merged?

**Comment by gabrielsoldani** [comment]
@krummrey #990, which serves the same purpose, was the one merged.

**Comment by krummrey** [comment]
Shouldn't this be closed then? Just to make it easier to keep track of relevant PRs?

**Comment by primaxius** [comment]
Closed as alternative was merged https://github.com/PokemonGoMap/PokemonGo-Map/pull/990

**Pull request closed without merging**
